// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class BottomNavigationComponentHandle extends ffai.ProjectComponentHandle<BottomNavigationParams, BottomNavigationState> {
  BottomNavigationComponentHandle()
    : super(
        name: "BottomNavigation",
        key: "Container_qcukazkv",
        params: const BottomNavigationParams(),
        state: const BottomNavigationState(),
        widgets: BottomNavigationWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "onItemTapped": ffai.json,
          "selectedIndex": ffai.int_,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? onItemTapped = ffai.kUnsetComponentArg,
    Object? selectedIndex = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(onItemTapped)) "onItemTapped": onItemTapped,
        if (!ffai.isUnsetComponentArg(selectedIndex)) "selectedIndex": selectedIndex,
      },
    );
  }
}

final class BottomNavigationParams {
  const BottomNavigationParams();
  ffai.ProjectParamHandle get onItemTapped =>
      const ffai.ProjectParamHandle(
        name: "onItemTapped",
        key: "xayx0hji",
        typeName: "Action",
      );
  ffai.ProjectParamHandle get selectedIndex =>
      const ffai.ProjectParamHandle(
        name: "selectedIndex",
        key: "9mj01kal",
        typeName: "Integer",
      );
}

final class BottomNavigationState {
  const BottomNavigationState();
}

abstract final class BottomNavigationWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_qcukazkv",
      type: "Container",
      path: "BottomNavigation",
      name: "BottomNavigation",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_vzee1njo",
          type: "Container",
          path: "BottomNavigation.children[0]",
          name: "NavSurface",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Row_sydsdhur",
              type: "Row",
              path: "BottomNavigation.children[0].children[0]",
              name: "NavRow",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_hiyxty50",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[0]",
                  name: "NavHomeOff",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_wk2eo17j",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[0].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Container_nex6txmi",
                          type: "Container",
                          path: "BottomNavigation.children[0].children[0].children[0].children[0].children[0]",
                          name: "Icon_home_muted",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_tk9w5sz7",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[0].children[0].children[1]",
                          name: "NavHomeOffLabel",
                          text: "Home",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_lrwf24qv",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[1]",
                  name: "NavHomeOn",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_zdf6ku3s",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[1].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Container_ags2tu3m",
                          type: "Container",
                          path: "BottomNavigation.children[0].children[0].children[1].children[0].children[0]",
                          name: "Icon_home_forest",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_w9ibett2",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[1].children[0].children[1]",
                          name: "NavHomeOnLabel",
                          text: "Home",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_5655yc9k",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[2]",
                  name: "NavInventoryOff",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_pzaa9dwh",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[2].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Container_pala6lni",
                          type: "Container",
                          path: "BottomNavigation.children[0].children[0].children[2].children[0].children[0]",
                          name: "Icon_inventory_muted",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_gl848fnc",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[2].children[0].children[1]",
                          name: "NavInventoryOffLabel",
                          text: "Inventory",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_hly39zp0",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[3]",
                  name: "NavInventoryOn",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_8f85vyvq",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[3].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Container_nhan0sxx",
                          type: "Container",
                          path: "BottomNavigation.children[0].children[0].children[3].children[0].children[0]",
                          name: "Icon_inventory_forest",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_givlcfr0",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[3].children[0].children[1]",
                          name: "NavInventoryOnLabel",
                          text: "Inventory",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_la20rste",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[4]",
                  name: "NavScan",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_3aes6r96",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[4].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Container_g6x780zz",
                          type: "Container",
                          path: "BottomNavigation.children[0].children[0].children[4].children[0].children[0]",
                          name: "Icon_scan_white",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_novzu6xc",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[4].children[0].children[1]",
                          name: "NavScanLabel",
                          text: "Scan",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_g22rgmnj",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[5]",
                  name: "NavRecipesOff",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_ehoxc7n8",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[5].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Container_kr0go8r7",
                          type: "Container",
                          path: "BottomNavigation.children[0].children[0].children[5].children[0].children[0]",
                          name: "Icon_recipes_muted",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_mgx036uo",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[5].children[0].children[1]",
                          name: "NavRecipesOffLabel",
                          text: "Recipes",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_nw7ya156",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[6]",
                  name: "NavRecipesOn",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_6m2mcs6d",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[6].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Container_5ynve8ge",
                          type: "Container",
                          path: "BottomNavigation.children[0].children[0].children[6].children[0].children[0]",
                          name: "Icon_recipes_forest",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_56qab6x5",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[6].children[0].children[1]",
                          name: "NavRecipesOnLabel",
                          text: "Recipes",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_4gob7dc0",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[7]",
                  name: "NavProfileOff",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_k9k37wyj",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[7].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Container_ukalh4q4",
                          type: "Container",
                          path: "BottomNavigation.children[0].children[0].children[7].children[0].children[0]",
                          name: "Icon_profile_muted",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_teq9j1ef",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[7].children[0].children[1]",
                          name: "NavProfileOffLabel",
                          text: "Profile",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_se4ybds2",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[8]",
                  name: "NavProfileOn",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_imhymzn0",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[8].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Container_026hayu7",
                          type: "Container",
                          path: "BottomNavigation.children[0].children[0].children[8].children[0].children[0]",
                          name: "Icon_profile_forest",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_lhmv76xv",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[8].children[0].children[1]",
                          name: "NavProfileOnLabel",
                          text: "Profile",
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

