// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class BottomNavigationComponentHandle extends ffai.ProjectComponentHandle<BottomNavigationParams, BottomNavigationState> {
  BottomNavigationComponentHandle()
    : super(
        name: "BottomNavigation",
        key: "Container_qcukazkv",
        params: const BottomNavigationParams(),
        state: const BottomNavigationState(),
        widgets: BottomNavigationWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "onItemTapped": ffai.json,
          "selectedIndex": ffai.int_,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? onItemTapped = ffai.kUnsetComponentArg,
    Object? selectedIndex = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(onItemTapped)) "onItemTapped": onItemTapped,
        if (!ffai.isUnsetComponentArg(selectedIndex)) "selectedIndex": selectedIndex,
      },
    );
  }
}

final class BottomNavigationParams {
  const BottomNavigationParams();
  ffai.ProjectParamHandle get onItemTapped =>
      const ffai.ProjectParamHandle(
        name: "onItemTapped",
        key: "xayx0hji",
        typeName: "Action",
      );
  ffai.ProjectParamHandle get selectedIndex =>
      const ffai.ProjectParamHandle(
        name: "selectedIndex",
        key: "9mj01kal",
        typeName: "Integer",
      );
}

final class BottomNavigationState {
  const BottomNavigationState();
}

abstract final class BottomNavigationWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_qcukazkv",
      type: "Container",
      path: "BottomNavigation",
      name: "BottomNavigation",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_vzee1njo",
          type: "Container",
          path: "BottomNavigation.children[0]",
          name: "NavSurface",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Row_rik5xlzm",
              type: "Row",
              path: "BottomNavigation.children[0].children[0]",
              name: "Row",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_fq09ja0v",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[0]",
                  name: "NavHomeOff",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_9ek8wp69",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[0].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Icon_m0lwb7v7",
                          type: "Icon",
                          path: "BottomNavigation.children[0].children[0].children[0].children[0].children[0]",
                          name: "Icon",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_e346dmb2",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[0].children[0].children[1]",
                          name: "NavHomeOffLabel",
                          text: "Home",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_inqgng6u",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[1]",
                  name: "NavHomeOn",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_8cago9r5",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[1].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Icon_h09kzoyz",
                          type: "Icon",
                          path: "BottomNavigation.children[0].children[0].children[1].children[0].children[0]",
                          name: "Icon",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_8h1rvf4u",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[1].children[0].children[1]",
                          name: "NavHomeOnLabel",
                          text: "Home",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_0vqspwpl",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[2]",
                  name: "NavInventoryOff",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_55qruq6p",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[2].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Icon_c7i5k812",
                          type: "Icon",
                          path: "BottomNavigation.children[0].children[0].children[2].children[0].children[0]",
                          name: "Icon",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_uci281y6",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[2].children[0].children[1]",
                          name: "NavInventoryOffLabel",
                          text: "Inventory",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_iiaffhm4",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[3]",
                  name: "NavInventoryOn",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_yz026p8d",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[3].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Icon_4adnq8c0",
                          type: "Icon",
                          path: "BottomNavigation.children[0].children[0].children[3].children[0].children[0]",
                          name: "Icon",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_wjbs6bcy",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[3].children[0].children[1]",
                          name: "NavInventoryOnLabel",
                          text: "Inventory",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_538qmqo5",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[4]",
                  name: "NavScan",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_b9ydtxes",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[4].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Icon_exa9nuap",
                          type: "Icon",
                          path: "BottomNavigation.children[0].children[0].children[4].children[0].children[0]",
                          name: "Icon",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_3ymdi124",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[4].children[0].children[1]",
                          name: "NavScanLabel",
                          text: "Scan",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_kk86ksap",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[5]",
                  name: "NavRecipesOff",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_daw6bcpp",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[5].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Icon_pamx9lj3",
                          type: "Icon",
                          path: "BottomNavigation.children[0].children[0].children[5].children[0].children[0]",
                          name: "Icon",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_xibwuukc",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[5].children[0].children[1]",
                          name: "NavRecipesOffLabel",
                          text: "Recipes",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_8mqgteu0",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[6]",
                  name: "NavRecipesOn",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_lotcvwxo",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[6].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Icon_7k2efc6b",
                          type: "Icon",
                          path: "BottomNavigation.children[0].children[0].children[6].children[0].children[0]",
                          name: "Icon",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_gxvztcvf",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[6].children[0].children[1]",
                          name: "NavRecipesOnLabel",
                          text: "Recipes",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_8uhryom9",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[7]",
                  name: "NavProfileOff",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_rc55ndxv",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[7].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Icon_ptf8k6ot",
                          type: "Icon",
                          path: "BottomNavigation.children[0].children[0].children[7].children[0].children[0]",
                          name: "Icon",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_cun70vx1",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[7].children[0].children[1]",
                          name: "NavProfileOffLabel",
                          text: "Profile",
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_839ykx25",
                  type: "Container",
                  path: "BottomNavigation.children[0].children[0].children[8]",
                  name: "NavProfileOn",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_5tmmyubu",
                      type: "Column",
                      path: "BottomNavigation.children[0].children[0].children[8].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Icon_w09qsies",
                          type: "Icon",
                          path: "BottomNavigation.children[0].children[0].children[8].children[0].children[0]",
                          name: "Icon",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_ux08mpq9",
                          type: "Text",
                          path: "BottomNavigation.children[0].children[0].children[8].children[0].children[1]",
                          name: "NavProfileOnLabel",
                          text: "Profile",
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

