// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class EmptyStateCardComponentHandle extends ffai.ProjectComponentHandle<EmptyStateCardParams, EmptyStateCardState> {
  EmptyStateCardComponentHandle()
    : super(
        name: "EmptyStateCard",
        key: "Container_1ismh9c6",
        params: const EmptyStateCardParams(),
        state: const EmptyStateCardState(),
        widgets: EmptyStateCardWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "message": ffai.string,
          "title": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? message = ffai.kUnsetComponentArg,
    Object? title = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(message)) "message": message,
        if (!ffai.isUnsetComponentArg(title)) "title": title,
      },
    );
  }
}

final class EmptyStateCardParams {
  const EmptyStateCardParams();
  ffai.ProjectParamHandle get message =>
      const ffai.ProjectParamHandle(
        name: "message",
        key: "ouq5hkgy",
        typeName: "String",
      );
  ffai.ProjectParamHandle get title =>
      const ffai.ProjectParamHandle(
        name: "title",
        key: "3wozbdg7",
        typeName: "String",
      );
}

final class EmptyStateCardState {
  const EmptyStateCardState();
}

abstract final class EmptyStateCardWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_1ismh9c6",
      type: "Container",
      path: "EmptyStateCard",
      name: "EmptyStateCard",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_igd87orl",
          type: "Container",
          path: "EmptyStateCard.children[0]",
          name: "Container",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Column_hxch19vm",
              type: "Column",
              path: "EmptyStateCard.children[0].children[0]",
              name: "Column",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Icon_h0a031nq",
                  type: "Icon",
                  path: "EmptyStateCard.children[0].children[0].children[0]",
                  name: "Icon",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Text_mttnvyt3",
                  type: "Text",
                  path: "EmptyStateCard.children[0].children[0].children[1]",
                  name: "Text",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Text_b1vuibop",
                  type: "Text",
                  path: "EmptyStateCard.children[0].children[0].children[2]",
                  name: "Text",
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

