// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class FoodCardComponentHandle extends ffai.ProjectComponentHandle<FoodCardParams, FoodCardState> {
  FoodCardComponentHandle()
    : super(
        name: "FoodCard",
        key: "Container_2z551u2y",
        params: const FoodCardParams(),
        state: const FoodCardState(),
        widgets: FoodCardWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "dateLine": ffai.string,
          "itemName": ffai.string,
          "meta": ffai.string,
          "statusLabel": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? dateLine = ffai.kUnsetComponentArg,
    Object? itemName = ffai.kUnsetComponentArg,
    Object? meta = ffai.kUnsetComponentArg,
    Object? statusLabel = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(dateLine)) "dateLine": dateLine,
        if (!ffai.isUnsetComponentArg(itemName)) "itemName": itemName,
        if (!ffai.isUnsetComponentArg(meta)) "meta": meta,
        if (!ffai.isUnsetComponentArg(statusLabel)) "statusLabel": statusLabel,
      },
    );
  }
}

final class FoodCardParams {
  const FoodCardParams();
  ffai.ProjectParamHandle get dateLine =>
      const ffai.ProjectParamHandle(
        name: "dateLine",
        key: "xuljl8ub",
        typeName: "String",
      );
  ffai.ProjectParamHandle get itemName =>
      const ffai.ProjectParamHandle(
        name: "itemName",
        key: "h61w3vvu",
        typeName: "String",
      );
  ffai.ProjectParamHandle get meta =>
      const ffai.ProjectParamHandle(
        name: "meta",
        key: "9fzoykyj",
        typeName: "String",
      );
  ffai.ProjectParamHandle get statusLabel =>
      const ffai.ProjectParamHandle(
        name: "statusLabel",
        key: "p75if01k",
        typeName: "String",
      );
}

final class FoodCardState {
  const FoodCardState();
}

abstract final class FoodCardWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_2z551u2y",
      type: "Container",
      path: "FoodCard",
      name: "FoodCard",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_tgg5sw2c",
          type: "Container",
          path: "FoodCard.children[0]",
          name: "FoodCardShell",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Row_pay5iz05",
              type: "Row",
              path: "FoodCard.children[0].children[0]",
              name: "Row",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_iq5mkie8",
                  type: "Container",
                  path: "FoodCard.children[0].children[0].children[0]",
                  name: "FoodCardTile",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Icon_7loifm3t",
                      type: "Icon",
                      path: "FoodCard.children[0].children[0].children[0].children[0]",
                      name: "FoodCardTileIcon",
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Column_twlipksn",
                  type: "Column",
                  path: "FoodCard.children[0].children[0].children[1]",
                  name: "Column",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Text_4w3pol9v",
                      type: "Text",
                      path: "FoodCard.children[0].children[0].children[1].children[0]",
                      name: "FoodCardName",
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Text_i4a99c68",
                      type: "Text",
                      path: "FoodCard.children[0].children[0].children[1].children[1]",
                      name: "FoodCardMeta",
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Container_hdadgapt",
                      type: "Container",
                      path: "FoodCard.children[0].children[0].children[1].children[2]",
                      name: "FoodCardStatus",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Text_8y9y7rf9",
                          type: "Text",
                          path: "FoodCard.children[0].children[0].children[1].children[2].children[0]",
                          name: "FoodCardStatusLabel",
                        ),
                      ],
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Text_qq63qpcb",
                      type: "Text",
                      path: "FoodCard.children[0].children[0].children[1].children[3]",
                      name: "FoodCardDateLine",
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Icon_fzsou170",
                  type: "Icon",
                  path: "FoodCard.children[0].children[0].children[2]",
                  name: "FoodCardChevron",
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

