// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class FoodCardComponentHandle extends ffai.ProjectComponentHandle<FoodCardParams, FoodCardState> {
  FoodCardComponentHandle()
    : super(
        name: "FoodCard",
        key: "Container_2z551u2y",
        params: const FoodCardParams(),
        state: const FoodCardState(),
        widgets: FoodCardWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "imageUrl": ffai.string,
          "itemName": ffai.string,
          "meta": ffai.string,
          "status": ffai.string,
          "statusLabel": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? imageUrl = ffai.kUnsetComponentArg,
    Object? itemName = ffai.kUnsetComponentArg,
    Object? meta = ffai.kUnsetComponentArg,
    Object? status = ffai.kUnsetComponentArg,
    Object? statusLabel = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(imageUrl)) "imageUrl": imageUrl,
        if (!ffai.isUnsetComponentArg(itemName)) "itemName": itemName,
        if (!ffai.isUnsetComponentArg(meta)) "meta": meta,
        if (!ffai.isUnsetComponentArg(status)) "status": status,
        if (!ffai.isUnsetComponentArg(statusLabel)) "statusLabel": statusLabel,
      },
    );
  }
}

final class FoodCardParams {
  const FoodCardParams();
  ffai.ProjectParamHandle get imageUrl =>
      const ffai.ProjectParamHandle(
        name: "imageUrl",
        key: "uzkjvfgk",
        typeName: "String",
      );
  ffai.ProjectParamHandle get itemName =>
      const ffai.ProjectParamHandle(
        name: "itemName",
        key: "h61w3vvu",
        typeName: "String",
      );
  ffai.ProjectParamHandle get meta =>
      const ffai.ProjectParamHandle(
        name: "meta",
        key: "9fzoykyj",
        typeName: "String",
      );
  ffai.ProjectParamHandle get status =>
      const ffai.ProjectParamHandle(
        name: "status",
        key: "so2nmbfc",
        typeName: "String",
      );
  ffai.ProjectParamHandle get statusLabel =>
      const ffai.ProjectParamHandle(
        name: "statusLabel",
        key: "p75if01k",
        typeName: "String",
      );
}

final class FoodCardState {
  const FoodCardState();
}

abstract final class FoodCardWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_2z551u2y",
      type: "Container",
      path: "FoodCard",
      name: "FoodCard",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_tgg5sw2c",
          type: "Container",
          path: "FoodCard.children[0]",
          name: "FoodCardShell",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Column_m59gw96z",
              type: "Column",
              path: "FoodCard.children[0].children[0]",
              name: "FoodCardBody",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Image_n8bgan0c",
                  type: "Image",
                  path: "FoodCard.children[0].children[0].children[0]",
                  name: "FoodCardPhoto",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_z68tu08r",
                  type: "Container",
                  path: "FoodCard.children[0].children[0].children[1]",
                  name: "FoodCardCaption",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_wfafm06b",
                      type: "Column",
                      path: "FoodCard.children[0].children[0].children[1].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Text_1z7byqkb",
                          type: "Text",
                          path: "FoodCard.children[0].children[0].children[1].children[0].children[0]",
                          name: "FoodCardTitle",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Row_r8dlnmb3",
                          type: "Row",
                          path: "FoodCard.children[0].children[0].children[1].children[0].children[1]",
                          name: "Row",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Container_q262ozqb",
                              type: "Container",
                              path: "FoodCard.children[0].children[0].children[1].children[0].children[1].children[0]",
                              name: "FoodCardBadge",
                            ),
                            ffai.ProjectWidgetHandle(
                              key: "Text_ius096yz",
                              type: "Text",
                              path: "FoodCard.children[0].children[0].children[1].children[0].children[1].children[1]",
                              name: "FoodCardQuantity",
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

