// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class SectionHeadingComponentHandle extends ffai.ProjectComponentHandle<SectionHeadingParams, SectionHeadingState> {
  SectionHeadingComponentHandle()
    : super(
        name: "SectionHeading",
        key: "Container_cn6wjana",
        params: const SectionHeadingParams(),
        state: const SectionHeadingState(),
        widgets: SectionHeadingWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "action": ffai.string,
          "title": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? action = ffai.kUnsetComponentArg,
    Object? title = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(action)) "action": action,
        if (!ffai.isUnsetComponentArg(title)) "title": title,
      },
    );
  }
}

final class SectionHeadingParams {
  const SectionHeadingParams();
  ffai.ProjectParamHandle get action =>
      const ffai.ProjectParamHandle(
        name: "action",
        key: "hoizwm5f",
        typeName: "String",
      );
  ffai.ProjectParamHandle get title =>
      const ffai.ProjectParamHandle(
        name: "title",
        key: "slgvc4u4",
        typeName: "String",
      );
}

final class SectionHeadingState {
  const SectionHeadingState();
}

abstract final class SectionHeadingWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_cn6wjana",
      type: "Container",
      path: "SectionHeading",
      name: "SectionHeading",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Row_lo388rgt",
          type: "Row",
          path: "SectionHeading.children[0]",
          name: "SectionHeadingRow",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Text_j4jcy8xi",
              type: "Text",
              path: "SectionHeading.children[0].children[0]",
              name: "SectionHeadingTitle",
            ),
            ffai.ProjectWidgetHandle(
              key: "Text_wslvw530",
              type: "Text",
              path: "SectionHeading.children[0].children[1]",
              name: "SectionHeadingAction",
            ),
          ],
        ),
      ],
    ),
  );
}

