// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class StatusBadgeComponentHandle extends ffai.ProjectComponentHandle<StatusBadgeParams, StatusBadgeState> {
  StatusBadgeComponentHandle()
    : super(
        name: "StatusBadge",
        key: "Container_zdlm65ar",
        params: const StatusBadgeParams(),
        state: const StatusBadgeState(),
        widgets: StatusBadgeWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "label": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? label = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(label)) "label": label,
      },
    );
  }
}

final class StatusBadgeParams {
  const StatusBadgeParams();
  ffai.ProjectParamHandle get label =>
      const ffai.ProjectParamHandle(
        name: "label",
        key: "f3i5gmwo",
        typeName: "String",
      );
}

final class StatusBadgeState {
  const StatusBadgeState();
}

abstract final class StatusBadgeWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_zdlm65ar",
      type: "Container",
      path: "StatusBadge",
      name: "StatusBadge",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_2jkdhftw",
          type: "Container",
          path: "StatusBadge.children[0]",
          name: "StatusBadgeShell",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Text_t3r2bpht",
              type: "Text",
              path: "StatusBadge.children[0].children[0]",
              name: "StatusBadgeLabel",
            ),
          ],
        ),
      ],
    ),
  );
}

