// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final addFoodReviewPageHandle = ffai.ProjectPageHandle<AddFoodReviewPageParams, AddFoodReviewPageState>(
  name: "AddFoodReviewPage",
  key: "Scaffold_z21mdazd",
  route: "review-item",
  params: const AddFoodReviewPageParams(),
  state: const AddFoodReviewPageState(),
  widgets: AddFoodReviewPageWidgets.tree,
);

final class AddFoodReviewPageParams {
  const AddFoodReviewPageParams();
  ffai.ProjectParamHandle get category =>
      const ffai.ProjectParamHandle(
        name: "category",
        key: "jm4pq547",
        typeName: "String",
      );
  ffai.ProjectParamHandle get locationId =>
      const ffai.ProjectParamHandle(
        name: "locationId",
        key: "8f15ggly",
        typeName: "String",
      );
  ffai.ProjectParamHandle get locationLabel =>
      const ffai.ProjectParamHandle(
        name: "locationLabel",
        key: "ytrnj552",
        typeName: "String",
      );
  ffai.ProjectParamHandle get name =>
      const ffai.ProjectParamHandle(
        name: "name",
        key: "o9wb2a3y",
        typeName: "String",
      );
  ffai.ProjectParamHandle get printedDate =>
      const ffai.ProjectParamHandle(
        name: "printedDate",
        key: "5fgqrxdh",
        typeName: "DateTime",
      );
  ffai.ProjectParamHandle get printedDateType =>
      const ffai.ProjectParamHandle(
        name: "printedDateType",
        key: "szbxeadc",
        typeName: "String",
      );
}

final class AddFoodReviewPageState {
  const AddFoodReviewPageState();
}

abstract final class AddFoodReviewPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_z21mdazd",
      type: "Scaffold",
      path: "AddFoodReviewPage",
      name: "AddFoodReviewPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_p29no9vx",
            type: "Container",
            path: "AddFoodReviewPage.body[0]",
            name: "ReviewBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_6zarqkgm",
                type: "Column",
                path: "AddFoodReviewPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_56j51xw7",
                    type: "Row",
                    path: "AddFoodReviewPage.body[0].children[0].children[0]",
                    name: "ReviewBackRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_5f6ticb3",
                        type: "Container",
                        path: "AddFoodReviewPage.body[0].children[0].children[0].children[0]",
                        name: "ReviewBack",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_xe6lzahh",
                            type: "Icon",
                            path: "AddFoodReviewPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Icon",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_e57k4pd5",
                    type: "Text",
                    path: "AddFoodReviewPage.body[0].children[0].children[1]",
                    name: "ReviewHeadline",
                    text: "Ready to add?",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_09l0707x",
                    type: "Text",
                    path: "AddFoodReviewPage.body[0].children[0].children[2]",
                    name: "ReviewLede",
                    text: "This is what will be recorded.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_htyl8fk4",
                    type: "Container",
                    path: "AddFoodReviewPage.body[0].children[0].children[3]",
                    name: "Review_name",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_s3a17qup",
                        type: "Column",
                        path: "AddFoodReviewPage.body[0].children[0].children[3].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_u08472em",
                            type: "Text",
                            path: "AddFoodReviewPage.body[0].children[0].children[3].children[0].children[0]",
                            name: "ReviewLabel_name",
                            text: "WHAT IT IS",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_3tdp3luh",
                            type: "Text",
                            path: "AddFoodReviewPage.body[0].children[0].children[3].children[0].children[1]",
                            name: "ReviewValue_name",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_b259xmmb",
                    type: "Container",
                    path: "AddFoodReviewPage.body[0].children[0].children[4]",
                    name: "Review_category",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_fay5ks9r",
                        type: "Column",
                        path: "AddFoodReviewPage.body[0].children[0].children[4].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_8cx87uld",
                            type: "Text",
                            path: "AddFoodReviewPage.body[0].children[0].children[4].children[0].children[0]",
                            name: "ReviewLabel_category",
                            text: "CATEGORY",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_03tav600",
                            type: "Text",
                            path: "AddFoodReviewPage.body[0].children[0].children[4].children[0].children[1]",
                            name: "ReviewValue_category",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_40ouo8us",
                    type: "Container",
                    path: "AddFoodReviewPage.body[0].children[0].children[5]",
                    name: "Review_where",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_xcvbeymu",
                        type: "Column",
                        path: "AddFoodReviewPage.body[0].children[0].children[5].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_7xxsrqga",
                            type: "Text",
                            path: "AddFoodReviewPage.body[0].children[0].children[5].children[0].children[0]",
                            name: "ReviewLabel_where",
                            text: "WHERE IT GOES",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_hqbjqumh",
                            type: "Text",
                            path: "AddFoodReviewPage.body[0].children[0].children[5].children[0].children[1]",
                            name: "ReviewValue_where",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_o9vo7l5m",
                    type: "Container",
                    path: "AddFoodReviewPage.body[0].children[0].children[6]",
                    name: "Review_date",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_3xlrg2iy",
                        type: "Column",
                        path: "AddFoodReviewPage.body[0].children[0].children[6].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_xr58cv6i",
                            type: "Text",
                            path: "AddFoodReviewPage.body[0].children[0].children[6].children[0].children[0]",
                            name: "ReviewLabel_date",
                            text: "THE DATE",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_780el5wc",
                            type: "Text",
                            path: "AddFoodReviewPage.body[0].children[0].children[6].children[0].children[1]",
                            name: "ReviewValue_date",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_xkib7ah7",
                    type: "Container",
                    path: "AddFoodReviewPage.body[0].children[0].children[7]",
                    name: "ReviewDateNote",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_t144zlcl",
                        type: "Text",
                        path: "AddFoodReviewPage.body[0].children[0].children[7].children[0]",
                        name: "ReviewDateNoteText",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_sm2avojh",
                    type: "Button",
                    path: "AddFoodReviewPage.body[0].children[0].children[8]",
                    name: "ReviewConfirm",
                    text: "Add to my kitchen",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_44domhde",
                    type: "Container",
                    path: "AddFoodReviewPage.body[0].children[0].children[9]",
                    name: "ReviewEdit",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_a1dfflnr",
                        type: "Text",
                        path: "AddFoodReviewPage.body[0].children[0].children[9].children[0]",
                        name: "ReviewEditLabel",
                        text: "Back to edit",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

