// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final cameraPageHandle = ffai.ProjectPageHandle<CameraPageParams, CameraPageState>(
  name: "CameraPage",
  key: "Scaffold_gtnn4ywk",
  route: "camera",
  params: const CameraPageParams(),
  state: const CameraPageState(),
  widgets: CameraPageWidgets.tree,
);

final class CameraPageParams {
  const CameraPageParams();
  ffai.ProjectParamHandle get mode =>
      const ffai.ProjectParamHandle(
        name: "mode",
        key: "o2bi8h8l",
        typeName: "String",
      );
}

final class CameraPageState {
  const CameraPageState();
}

abstract final class CameraPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_gtnn4ywk",
      type: "Scaffold",
      path: "CameraPage",
      name: "CameraPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_o0i4trjp",
            type: "Container",
            path: "CameraPage.body[0]",
            name: "CameraView",
          ),
        ],
      },
    ),
  );
}

