// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final editItemPageHandle = ffai.ProjectPageHandle<EditItemPageParams, EditItemPageState>(
  name: "EditItemPage",
  key: "Scaffold_ilk9qew4",
  route: "edit-item",
  params: const EditItemPageParams(),
  state: const EditItemPageState(),
  widgets: EditItemPageWidgets.tree,
);

final class EditItemPageParams {
  const EditItemPageParams();
  ffai.ProjectParamHandle get itemId =>
      const ffai.ProjectParamHandle(
        name: "itemId",
        key: "1ynh3fe6",
        typeName: "String",
      );
}

final class EditItemPageState {
  const EditItemPageState();
}

abstract final class EditItemPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ilk9qew4",
      type: "Scaffold",
      path: "EditItemPage",
      name: "EditItemPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_ao5ii9rt",
            type: "Container",
            path: "EditItemPage.body[0]",
            name: "EditItemBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_dz7w5eg8",
                type: "Column",
                path: "EditItemPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_atxg8icd",
                    type: "Row",
                    path: "EditItemPage.body[0].children[0].children[0]",
                    name: "EditItemBackRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_xpyatbln",
                        type: "Container",
                        path: "EditItemPage.body[0].children[0].children[0].children[0]",
                        name: "EditItemBack",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_lksk2swf",
                            type: "Icon",
                            path: "EditItemPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Icon",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_8dtytb3k",
                    type: "Text",
                    path: "EditItemPage.body[0].children[0].children[1]",
                    name: "EditItemHeadline",
                    text: "Fix the details.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_5l8kvj2p",
                    type: "Text",
                    path: "EditItemPage.body[0].children[0].children[2]",
                    name: "EditItemLede",
                    text: "Anything the app guessed, or left blank when you added it in a hurry.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_colj4ubr",
                    type: "Container",
                    path: "EditItemPage.body[0].children[0].children[3]",
                    name: "EditItemPanel",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_nvf99yhf",
                    type: "Button",
                    path: "EditItemPage.body[0].children[0].children[4]",
                    name: "EditItemSave",
                    text: "Save changes",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

