// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final foodItemPageHandle = ffai.ProjectPageHandle<FoodItemPageParams, FoodItemPageState>(
  name: "FoodItemPage",
  key: "Scaffold_eifl8vzj",
  route: "item",
  params: const FoodItemPageParams(),
  state: const FoodItemPageState(),
  widgets: FoodItemPageWidgets.tree,
);

final class FoodItemPageParams {
  const FoodItemPageParams();
  ffai.ProjectParamHandle get itemId =>
      const ffai.ProjectParamHandle(
        name: "itemId",
        key: "8cjoltn4",
        typeName: "String",
      );
}

final class FoodItemPageState {
  const FoodItemPageState();
  ffai.ProjectStateFieldHandle get item =>
      const ffai.ProjectStateFieldHandle(
        name: "item",
        key: "mt18fvfi",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get loadedOk =>
      const ffai.ProjectStateFieldHandle(
        name: "loadedOk",
        key: "37asiomq",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get offline =>
      const ffai.ProjectStateFieldHandle(
        name: "offline",
        key: "xawmk3r7",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get replace =>
      const ffai.ProjectStateFieldHandle(
        name: "replace",
        key: "9om3awkj",
        typeName: "Boolean",
      );
}

abstract final class FoodItemPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_eifl8vzj",
      type: "Scaffold",
      path: "FoodItemPage",
      name: "FoodItemPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_2mxze0vq",
            type: "Column",
            path: "FoodItemPage.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Stack_5f32p9ma",
                type: "Stack",
                path: "FoodItemPage.body[0].children[0]",
                name: "ItemHeroStack",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Image_al6h3jl1",
                    type: "Image",
                    path: "FoodItemPage.body[0].children[0].children[0]",
                    name: "ItemPhoto",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_oubu3mhc",
                    type: "Container",
                    path: "FoodItemPage.body[0].children[0].children[1]",
                    name: "ItemBackButton Margin",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_v69a9d7p",
                        type: "Container",
                        path: "FoodItemPage.body[0].children[0].children[1].children[0]",
                        name: "ItemBackButton",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_ih3c8fgl",
                            type: "Icon",
                            path: "FoodItemPage.body[0].children[0].children[1].children[0].children[0]",
                            name: "Icon",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_xst4bt2r",
                type: "Container",
                path: "FoodItemPage.body[0].children[1]",
                name: "ItemBody",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_wt6avp00",
                    type: "Column",
                    path: "FoodItemPage.body[0].children[1].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_4oc4iodb",
                        type: "Text",
                        path: "FoodItemPage.body[0].children[1].children[0].children[0]",
                        name: "ItemName",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_d1vf3f1i",
                        type: "Container",
                        path: "FoodItemPage.body[0].children[1].children[0].children[1]",
                        name: "ItemBadge",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_5gldqe50",
                        type: "Text",
                        path: "FoodItemPage.body[0].children[1].children[0].children[2]",
                        name: "ItemDetail",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_19g4bdfl",
                        type: "Container",
                        path: "FoodItemPage.body[0].children[1].children[0].children[3]",
                        name: "Fact_date",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_vqns0s2m",
                            type: "Column",
                            path: "FoodItemPage.body[0].children[1].children[0].children[3].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_z0f4axer",
                                type: "Text",
                                path: "FoodItemPage.body[0].children[1].children[0].children[3].children[0].children[0]",
                                name: "FactLabel_date",
                                text: "THE DATE",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_6r4uynpk",
                                type: "Text",
                                path: "FoodItemPage.body[0].children[1].children[0].children[3].children[0].children[1]",
                                name: "FactValue_date",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_m4r7jjet",
                        type: "Container",
                        path: "FoodItemPage.body[0].children[1].children[0].children[4]",
                        name: "Fact_dateSource",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_n1kzavrw",
                            type: "Column",
                            path: "FoodItemPage.body[0].children[1].children[0].children[4].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_c3r3u35b",
                                type: "Text",
                                path: "FoodItemPage.body[0].children[1].children[0].children[4].children[0].children[0]",
                                name: "FactLabel_dateSource",
                                text: "WHERE THAT CAME FROM",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_o46gtnpr",
                                type: "Text",
                                path: "FoodItemPage.body[0].children[1].children[0].children[4].children[0].children[1]",
                                name: "FactValue_dateSource",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_sd04zugr",
                        type: "Container",
                        path: "FoodItemPage.body[0].children[1].children[0].children[5]",
                        name: "Fact_basis",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_hx4s7c3j",
                            type: "Column",
                            path: "FoodItemPage.body[0].children[1].children[0].children[5].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_tmd2g824",
                                type: "Text",
                                path: "FoodItemPage.body[0].children[1].children[0].children[5].children[0].children[0]",
                                name: "FactLabel_basis",
                                text: "HOW THIS WAS WORKED OUT",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_qqnk9qi2",
                                type: "Text",
                                path: "FoodItemPage.body[0].children[1].children[0].children[5].children[0].children[1]",
                                name: "FactValue_basis",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_bxp4bdnx",
                        type: "Container",
                        path: "FoodItemPage.body[0].children[1].children[0].children[6]",
                        name: "Fact_quantity",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_fvnzmha3",
                            type: "Column",
                            path: "FoodItemPage.body[0].children[1].children[0].children[6].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_qhmwbxbe",
                                type: "Text",
                                path: "FoodItemPage.body[0].children[1].children[0].children[6].children[0].children[0]",
                                name: "FactLabel_quantity",
                                text: "HOW MUCH",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_jjsuw1lz",
                                type: "Text",
                                path: "FoodItemPage.body[0].children[1].children[0].children[6].children[0].children[1]",
                                name: "FactValue_quantity",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_8o782doc",
                        type: "Container",
                        path: "FoodItemPage.body[0].children[1].children[0].children[7]",
                        name: "Fact_where",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_939jd6pn",
                            type: "Column",
                            path: "FoodItemPage.body[0].children[1].children[0].children[7].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_bkyh2d6p",
                                type: "Text",
                                path: "FoodItemPage.body[0].children[1].children[0].children[7].children[0].children[0]",
                                name: "FactLabel_where",
                                text: "WHERE IT IS KEPT",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_q764rx5q",
                                type: "Text",
                                path: "FoodItemPage.body[0].children[1].children[0].children[7].children[0].children[1]",
                                name: "FactValue_where",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_hxwaktck",
                        type: "Container",
                        path: "FoodItemPage.body[0].children[1].children[0].children[8]",
                        name: "Fact_category",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_lihsva4p",
                            type: "Column",
                            path: "FoodItemPage.body[0].children[1].children[0].children[8].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_ndtgb32l",
                                type: "Text",
                                path: "FoodItemPage.body[0].children[1].children[0].children[8].children[0].children[0]",
                                name: "FactLabel_category",
                                text: "CATEGORY",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_ir7hz6a3",
                                type: "Text",
                                path: "FoodItemPage.body[0].children[1].children[0].children[8].children[0].children[1]",
                                name: "FactValue_category",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_de2f9ked",
                        type: "Container",
                        path: "FoodItemPage.body[0].children[1].children[0].children[9]",
                        name: "Fact_added",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_z69hqk9r",
                            type: "Column",
                            path: "FoodItemPage.body[0].children[1].children[0].children[9].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_atnxqwey",
                                type: "Text",
                                path: "FoodItemPage.body[0].children[1].children[0].children[9].children[0].children[0]",
                                name: "FactLabel_added",
                                text: "ADDED",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_xeil70jj",
                                type: "Text",
                                path: "FoodItemPage.body[0].children[1].children[0].children[9].children[0].children[1]",
                                name: "FactValue_added",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Column_01lid1tp",
                        type: "Column",
                        path: "FoodItemPage.body[0].children[1].children[0].children[10]",
                        name: "ItemActions",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_twamrhpx",
                            type: "Container",
                            path: "FoodItemPage.body[0].children[1].children[0].children[10].children[0]",
                            name: "ItemReplaceToggle",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_i47w4bjl",
                                type: "Row",
                                path: "FoodItemPage.body[0].children[1].children[0].children[10].children[0].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_emavulm8",
                                    type: "Icon",
                                    path: "FoodItemPage.body[0].children[1].children[0].children[10].children[0].children[0].children[0]",
                                    name: "ItemReplaceOff",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_69sqo82c",
                                    type: "Icon",
                                    path: "FoodItemPage.body[0].children[1].children[0].children[10].children[0].children[0].children[1]",
                                    name: "ItemReplaceOn",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_rdeflnkr",
                                    type: "Text",
                                    path: "FoodItemPage.body[0].children[1].children[0].children[10].children[0].children[0].children[2]",
                                    name: "ItemReplaceLabel",
                                    text: "Put it on the shopping list",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_q7rrsu3l",
                            type: "Button",
                            path: "FoodItemPage.body[0].children[1].children[0].children[10].children[1]",
                            name: "ItemUsed",
                            text: "I used it",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_fdabmnbe",
                            type: "Button",
                            path: "FoodItemPage.body[0].children[1].children[0].children[10].children[2]",
                            name: "ItemDiscarded",
                            text: "Throw it out",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

