// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final foodPreferencesPageHandle = ffai.ProjectPageHandle<FoodPreferencesPageParams, FoodPreferencesPageState>(
  name: "FoodPreferencesPage",
  key: "Scaffold_7xtddziv",
  route: "food-preferences",
  params: const FoodPreferencesPageParams(),
  state: const FoodPreferencesPageState(),
  widgets: FoodPreferencesPageWidgets.tree,
);

final class FoodPreferencesPageParams {
  const FoodPreferencesPageParams();
}

final class FoodPreferencesPageState {
  const FoodPreferencesPageState();
}

abstract final class FoodPreferencesPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_7xtddziv",
      type: "Scaffold",
      path: "FoodPreferencesPage",
      name: "FoodPreferencesPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_1p1blo9c",
            type: "Container",
            path: "FoodPreferencesPage.body[0]",
            name: "FoodPrefsBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_azv927dt",
                type: "Column",
                path: "FoodPreferencesPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_tvqf62eh",
                    type: "Row",
                    path: "FoodPreferencesPage.body[0].children[0].children[0]",
                    name: "FoodPrefsBackRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_tvw0171g",
                        type: "Container",
                        path: "FoodPreferencesPage.body[0].children[0].children[0].children[0]",
                        name: "FoodPrefsBack",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_35g0lwhl",
                            type: "Icon",
                            path: "FoodPreferencesPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Icon",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_k681zh92",
                    type: "Text",
                    path: "FoodPreferencesPage.body[0].children[0].children[1]",
                    name: "FoodPrefsHeadline",
                    text: "What you leave out.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_i81g1xxk",
                    type: "Text",
                    path: "FoodPreferencesPage.body[0].children[0].children[2]",
                    name: "FoodPrefsLede",
                    text: "Meal ideas will not use these foods. Nothing else in the app changes: your kitchen still holds whatever you put in it.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_gqlu1eef",
                    type: "Container",
                    path: "FoodPreferencesPage.body[0].children[0].children[3]",
                    name: "FoodPrefsPanel",
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

