// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final foodItemPageHandle = ffai.ProjectPageHandle<FoodItemPageParams, FoodItemPageState>(
  name: "FoodItemPage",
  key: "Scaffold_eifl8vzj",
  route: "item",
  params: const FoodItemPageParams(),
  state: const FoodItemPageState(),
  widgets: FoodItemPageWidgets.tree,
);

final class FoodItemPageParams {
  const FoodItemPageParams();
  ffai.ProjectParamHandle get itemId =>
      const ffai.ProjectParamHandle(
        name: "itemId",
        key: "8cjoltn4",
        typeName: "String",
      );
}

final class FoodItemPageState {
  const FoodItemPageState();
  ffai.ProjectStateFieldHandle get item =>
      const ffai.ProjectStateFieldHandle(
        name: "item",
        key: "mt18fvfi",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get loadedOk =>
      const ffai.ProjectStateFieldHandle(
        name: "loadedOk",
        key: "37asiomq",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get offline =>
      const ffai.ProjectStateFieldHandle(
        name: "offline",
        key: "xawmk3r7",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get replace =>
      const ffai.ProjectStateFieldHandle(
        name: "replace",
        key: "9om3awkj",
        typeName: "Boolean",
      );
}

abstract final class FoodItemPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_eifl8vzj",
      type: "Scaffold",
      path: "FoodItemPage",
      name: "FoodItemPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_2mxze0vq",
            type: "Column",
            path: "FoodItemPage.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_dfeqi091",
                type: "Container",
                path: "FoodItemPage.body[0].children[0]",
                name: "ItemDetailView",
              ),
            ],
          ),
        ],
      },
    ),
  );
}

