// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final homePageHandle = ffai.ProjectPageHandle<HomePageParams, HomePageState>(
  name: "HomePage",
  key: "Scaffold_0rpboyb7",
  route: "home",
  params: const HomePageParams(),
  state: const HomePageState(),
  widgets: HomePageWidgets.tree,
);

final class HomePageParams {
  const HomePageParams();
}

final class HomePageState {
  const HomePageState();
  ffai.ProjectStateFieldHandle get households =>
      const ffai.ProjectStateFieldHandle(
        name: "households",
        key: "s1y2brwm",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get me =>
      const ffai.ProjectStateFieldHandle(
        name: "me",
        key: "pzg06la1",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get useFirst =>
      const ffai.ProjectStateFieldHandle(
        name: "useFirst",
        key: "0qf8gp0g",
        typeName: "List<PostgresRow>",
      );
}

abstract final class HomePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_0rpboyb7",
      type: "Scaffold",
      path: "HomePage",
      name: "HomePage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_t21ep1yw",
            type: "Container",
            path: "HomePage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_9dwex63d",
                type: "Column",
                path: "HomePage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_xyvkhbda",
                    type: "Text",
                    path: "HomePage.body[0].children[0].children[0]",
                    name: "HomeEyebrow",
                    text: "OUR HOUSEHOLD",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_rlrqu2rp",
                    type: "Text",
                    path: "HomePage.body[0].children[0].children[1]",
                    name: "Text",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_00bqjarl",
                    type: "Text",
                    path: "HomePage.body[0].children[0].children[2]",
                    name: "Text",
                    text: "Let's make the most of what's in your kitchen.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_t5almqv2",
                    type: "Container",
                    path: "HomePage.body[0].children[0].children[3]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_nofrif9v",
                        type: "Column",
                        path: "HomePage.body[0].children[0].children[3].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_n2b0dcap",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[3].children[0].children[0]",
                            name: "Text",
                            text: "Finish setting up",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_gw34xuv1",
                            type: "Button",
                            path: "HomePage.body[0].children[0].children[3].children[0].children[1]",
                            name: "GoToOnboardingButton",
                            text: "Complete your profile",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_lff9ip91",
                            type: "Button",
                            path: "HomePage.body[0].children[0].children[3].children[0].children[2]",
                            name: "GoToHouseholdButton",
                            text: "Create or join a household",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_jxfk0s3t",
                    type: "Text",
                    path: "HomePage.body[0].children[0].children[4]",
                    name: "Text",
                    text: "Use first",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_rgq7we0r",
                    type: "Column",
                    path: "HomePage.body[0].children[0].children[5]",
                    name: "UseFirstSection",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "ListView_5iwxgrya",
                        type: "ListView",
                        path: "HomePage.body[0].children[0].children[5].children[0]",
                        name: "UseFirstList",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_ej56ame1",
                            type: "Container",
                            path: "HomePage.body[0].children[0].children[5].children[0].children[0]",
                            name: "UseFirstCard",
                            componentName: "FoodCard",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_trjyf20l",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[5].children[1]",
                        name: "UseFirstEmpty",
                        componentName: "EmptyStateCard",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_gdmfh6k7",
                    type: "Text",
                    path: "HomePage.body[0].children[0].children[6]",
                    name: "Text",
                    text: "Quick add",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_gpb5q4p0",
                    type: "Button",
                    path: "HomePage.body[0].children[0].children[7]",
                    name: "QuickAddManualButton",
                    text: "Add your first item",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_rnehja5c",
                    type: "Button",
                    path: "HomePage.body[0].children[0].children[8]",
                    name: "QuickAddScanButton",
                    text: "Scan an item instead",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

