// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final homePageHandle = ffai.ProjectPageHandle<HomePageParams, HomePageState>(
  name: "HomePage",
  key: "Scaffold_0rpboyb7",
  route: "home",
  params: const HomePageParams(),
  state: const HomePageState(),
  widgets: HomePageWidgets.tree,
);

final class HomePageParams {
  const HomePageParams();
}

final class HomePageState {
  const HomePageState();
  ffai.ProjectStateFieldHandle get households =>
      const ffai.ProjectStateFieldHandle(
        name: "households",
        key: "s1y2brwm",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get loadedOk =>
      const ffai.ProjectStateFieldHandle(
        name: "loadedOk",
        key: "rj7l9p51",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get me =>
      const ffai.ProjectStateFieldHandle(
        name: "me",
        key: "pzg06la1",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get offline =>
      const ffai.ProjectStateFieldHandle(
        name: "offline",
        key: "pypa27ar",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get useFirst =>
      const ffai.ProjectStateFieldHandle(
        name: "useFirst",
        key: "0qf8gp0g",
        typeName: "List<PostgresRow>",
      );
}

abstract final class HomePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_0rpboyb7",
      type: "Scaffold",
      path: "HomePage",
      name: "HomePage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_t21ep1yw",
            type: "Container",
            path: "HomePage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_9dwex63d",
                type: "Column",
                path: "HomePage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_8bi8tamu",
                    type: "Column",
                    path: "HomePage.body[0].children[0].children[0]",
                    name: "HomeGreetingBlock",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_0np1ttgt",
                        type: "Text",
                        path: "HomePage.body[0].children[0].children[0].children[0]",
                        name: "HomeHi",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_oafkeib3",
                        type: "Text",
                        path: "HomePage.body[0].children[0].children[0].children[1]",
                        name: "HomeHeadline",
                        text: "Fresh today.",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_o4p946lo",
                    type: "Container",
                    path: "HomePage.body[0].children[0].children[1]",
                    name: "HomeOffline",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_ih1rqql1",
                        type: "Column",
                        path: "HomePage.body[0].children[0].children[1].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_l8nd0rd7",
                            type: "Icon",
                            path: "HomePage.body[0].children[0].children[1].children[0].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_ngdbkege",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[1].children[0].children[1]",
                            name: "HomeOfflineTitle",
                            text: "Can’t reach your kitchen.",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_mldw7ojs",
                            type: "Text",
                            path: "HomePage.body[0].children[0].children[1].children[0].children[2]",
                            name: "HomeOfflineBody",
                            text: "No signal, or the connection dropped. Your food will show again as soon as you are back online.",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_gktxl0e1",
                            type: "Button",
                            path: "HomePage.body[0].children[0].children[1].children[0].children[3]",
                            name: "HomeOfflineRetry",
                            text: "Try again",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_y8xn4win",
                    type: "Container",
                    path: "HomePage.body[0].children[0].children[2]",
                    name: "HomeHouseholdPrompt",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_r8oy2bz0",
                        type: "Row",
                        path: "HomePage.body[0].children[0].children[2].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_g6f9ym74",
                            type: "Container",
                            path: "HomePage.body[0].children[0].children[2].children[0].children[0]",
                            name: "HomePromptTile",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_dhsxgx9f",
                                type: "Icon",
                                path: "HomePage.body[0].children[0].children[2].children[0].children[0].children[0]",
                                name: "Icon",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_26yyidqy",
                            type: "Column",
                            path: "HomePage.body[0].children[0].children[2].children[0].children[1]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_g6p17oou",
                                type: "Text",
                                path: "HomePage.body[0].children[0].children[2].children[0].children[1].children[0]",
                                name: "HomePromptTitle",
                                text: "Set up your kitchen",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_ped1qycr",
                                type: "Text",
                                path: "HomePage.body[0].children[0].children[2].children[0].children[1].children[1]",
                                name: "HomePromptPurpose",
                                text: "Create a household, or join your family’s",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Icon_e0aqenvf",
                            type: "Icon",
                            path: "HomePage.body[0].children[0].children[2].children[0].children[2]",
                            name: "Icon",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_m5nwt3o5",
                    type: "Container",
                    path: "HomePage.body[0].children[0].children[3]",
                    name: "UseNextHero",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Stack_82vmib4z",
                        type: "Stack",
                        path: "HomePage.body[0].children[0].children[3].children[0]",
                        name: "UseNextStack",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Image_0k1wg65m",
                            type: "Image",
                            path: "HomePage.body[0].children[0].children[3].children[0].children[0]",
                            name: "UseNextPhoto",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_2k3wzln6",
                            type: "Container",
                            path: "HomePage.body[0].children[0].children[3].children[0].children[1]",
                            name: "UseNextCaption",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_dpcs26r2",
                                type: "Column",
                                path: "HomePage.body[0].children[0].children[3].children[0].children[1].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_yivvkbqk",
                                    type: "Text",
                                    path: "HomePage.body[0].children[0].children[3].children[0].children[1].children[0].children[0]",
                                    name: "UseNextTitle",
                                    text: "Use these next",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_8ju54nwh",
                                    type: "Text",
                                    path: "HomePage.body[0].children[0].children[3].children[0].children[1].children[0].children[1]",
                                    name: "UseNextCount",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "GridView_pmh36not",
                    type: "GridView",
                    path: "HomePage.body[0].children[0].children[4]",
                    name: "UseFirstGrid",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_9s4vzoib",
                        type: "Container",
                        path: "HomePage.body[0].children[0].children[4].children[0]",
                        name: "UseFirstCard",
                        componentName: "FoodCard",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_gpb5q4p0",
                    type: "Button",
                    path: "HomePage.body[0].children[0].children[5]",
                    name: "QuickAddManualButton",
                    text: "Add food",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

