// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final householdSetupPageHandle = ffai.ProjectPageHandle<HouseholdSetupPageParams, HouseholdSetupPageState>(
  name: "HouseholdSetupPage",
  key: "Scaffold_pl25zxp2",
  route: "household-setup",
  params: const HouseholdSetupPageParams(),
  state: const HouseholdSetupPageState(),
  widgets: HouseholdSetupPageWidgets.tree,
);

final class HouseholdSetupPageParams {
  const HouseholdSetupPageParams();
}

final class HouseholdSetupPageState {
  const HouseholdSetupPageState();
  ffai.ProjectStateFieldHandle get householdName =>
      const ffai.ProjectStateFieldHandle(
        name: "householdName",
        key: "jsk2z92z",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get households =>
      const ffai.ProjectStateFieldHandle(
        name: "households",
        key: "f3mrtzk6",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get inviteCode =>
      const ffai.ProjectStateFieldHandle(
        name: "inviteCode",
        key: "my34x81c",
        typeName: "String",
      );
}

abstract final class HouseholdSetupPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_pl25zxp2",
      type: "Scaffold",
      path: "HouseholdSetupPage",
      name: "HouseholdSetupPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_ba1jxr92",
            type: "AppBar",
            path: "HouseholdSetupPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_623b3cbj",
                  type: "Text",
                  path: "HouseholdSetupPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Your household",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_x7z8gm24",
            type: "Container",
            path: "HouseholdSetupPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_2z6ha7oe",
                type: "Column",
                path: "HouseholdSetupPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_evhk120h",
                    type: "Text",
                    path: "HouseholdSetupPage.body[0].children[0].children[0]",
                    name: "Text",
                    text: "A household is the shared space where your fridge, freezer, and pantry live. Create one, or join your family’s.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_rjw3nhre",
                    type: "Container",
                    path: "HouseholdSetupPage.body[0].children[0].children[1]",
                    name: "CurrentHouseholdCard",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_daw44ybq",
                        type: "Column",
                        path: "HouseholdSetupPage.body[0].children[0].children[1].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_qo9kzsbp",
                            type: "Text",
                            path: "HouseholdSetupPage.body[0].children[0].children[1].children[0].children[0]",
                            name: "CurrentHouseholdEyebrow",
                            text: "YOUR HOUSEHOLD",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_8892i0cu",
                            type: "Text",
                            path: "HouseholdSetupPage.body[0].children[0].children[1].children[0].children[1]",
                            name: "CurrentHouseholdName",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_p60364nb",
                            type: "Text",
                            path: "HouseholdSetupPage.body[0].children[0].children[1].children[0].children[2]",
                            name: "CurrentHouseholdHint",
                            text: "Share this code so someone can join you.",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_q5god8h1",
                            type: "Text",
                            path: "HouseholdSetupPage.body[0].children[0].children[1].children[0].children[3]",
                            name: "CurrentHouseholdCode",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_exwspk68",
                    type: "Container",
                    path: "HouseholdSetupPage.body[0].children[0].children[2]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_pb7l6jb8",
                        type: "Column",
                        path: "HouseholdSetupPage.body[0].children[0].children[2].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_ric2g3cm",
                            type: "Text",
                            path: "HouseholdSetupPage.body[0].children[0].children[2].children[0].children[0]",
                            name: "Text",
                            text: "Create a household",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "TextField_cg0goaa0",
                            type: "TextField",
                            path: "HouseholdSetupPage.body[0].children[0].children[2].children[0].children[1]",
                            name: "HouseholdNameField",
                            text: "Household name",
                            triggers: const <String>[
                              "ON_TEXTFIELD_CHANGE",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_2y0hi6fk",
                            type: "Button",
                            path: "HouseholdSetupPage.body[0].children[0].children[2].children[0].children[2]",
                            name: "CreateHouseholdButton",
                            text: "Create household",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_ueg1a899",
                    type: "Container",
                    path: "HouseholdSetupPage.body[0].children[0].children[3]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_727faqnq",
                        type: "Column",
                        path: "HouseholdSetupPage.body[0].children[0].children[3].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_7r01imgg",
                            type: "Text",
                            path: "HouseholdSetupPage.body[0].children[0].children[3].children[0].children[0]",
                            name: "Text",
                            text: "Join with an invite code",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "TextField_pmsdcf3h",
                            type: "TextField",
                            path: "HouseholdSetupPage.body[0].children[0].children[3].children[0].children[1]",
                            name: "InviteCodeField",
                            text: "Invite code",
                            triggers: const <String>[
                              "ON_TEXTFIELD_CHANGE",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_wnnhah32",
                            type: "Button",
                            path: "HouseholdSetupPage.body[0].children[0].children[3].children[0].children[2]",
                            name: "JoinHouseholdButton",
                            text: "Join household",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

