// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final inventoryPageHandle = ffai.ProjectPageHandle<InventoryPageParams, InventoryPageState>(
  name: "InventoryPage",
  key: "Scaffold_2n83y1be",
  route: "inventory",
  params: const InventoryPageParams(),
  state: const InventoryPageState(),
  widgets: InventoryPageWidgets.tree,
);

final class InventoryPageParams {
  const InventoryPageParams();
}

final class InventoryPageState {
  const InventoryPageState();
  ffai.ProjectStateFieldHandle get allItems =>
      const ffai.ProjectStateFieldHandle(
        name: "allItems",
        key: "7qp1zzza",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get filter =>
      const ffai.ProjectStateFieldHandle(
        name: "filter",
        key: "5ibv1jdw",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get items =>
      const ffai.ProjectStateFieldHandle(
        name: "items",
        key: "ehauywrm",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get loadedOk =>
      const ffai.ProjectStateFieldHandle(
        name: "loadedOk",
        key: "c64xadp9",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get offline =>
      const ffai.ProjectStateFieldHandle(
        name: "offline",
        key: "1t1e0n1i",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get query =>
      const ffai.ProjectStateFieldHandle(
        name: "query",
        key: "j6r1qgcr",
        typeName: "String",
      );
}

abstract final class InventoryPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_2n83y1be",
      type: "Scaffold",
      path: "InventoryPage",
      name: "InventoryPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_9u8bwt59",
            type: "Container",
            path: "InventoryPage.body[0]",
            name: "InventoryBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_29fevh38",
                type: "Column",
                path: "InventoryPage.body[0].children[0]",
                name: "InventoryColumn",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_hg1a3ug3",
                    type: "Text",
                    path: "InventoryPage.body[0].children[0].children[0]",
                    name: "InventoryHeading",
                    text: "Your kitchen.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_jgkpr2qd",
                    type: "Text",
                    path: "InventoryPage.body[0].children[0].children[1]",
                    name: "InventoryLede",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Row_4o91f3id",
                    type: "Row",
                    path: "InventoryPage.body[0].children[0].children[2]",
                    name: "InventoryFilterChips",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_o0f2kwf5",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[0]",
                        name: "Chip_all_rest",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_bfd7c8uc",
                            type: "Row",
                            path: "InventoryPage.body[0].children[0].children[2].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_jxdezv8h",
                                type: "Container",
                                path: "InventoryPage.body[0].children[0].children[2].children[0].children[0].children[0]",
                                name: "ChipIcon_all_rest",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_8bppzasa",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[2].children[0].children[0].children[1]",
                                name: "ChipLabel_all_rest",
                                text: "All",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_726hfj4s",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[1]",
                        name: "Chip_all_on",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_4w4dxict",
                            type: "Row",
                            path: "InventoryPage.body[0].children[0].children[2].children[1].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_88vu18od",
                                type: "Container",
                                path: "InventoryPage.body[0].children[0].children[2].children[1].children[0].children[0]",
                                name: "ChipIcon_all_on",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_7awgn5wq",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[2].children[1].children[0].children[1]",
                                name: "ChipLabel_all_on",
                                text: "All",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_cf48xcnh",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[2]",
                        name: "Chip_fridge_rest",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_2hxajinz",
                            type: "Row",
                            path: "InventoryPage.body[0].children[0].children[2].children[2].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_pl5zxwr6",
                                type: "Container",
                                path: "InventoryPage.body[0].children[0].children[2].children[2].children[0].children[0]",
                                name: "ChipIcon_fridge_rest",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_p37z7a30",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[2].children[2].children[0].children[1]",
                                name: "ChipLabel_fridge_rest",
                                text: "Fridge",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_q2ue06qm",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[3]",
                        name: "Chip_fridge_on",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_e5qoome3",
                            type: "Row",
                            path: "InventoryPage.body[0].children[0].children[2].children[3].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_v21g862s",
                                type: "Container",
                                path: "InventoryPage.body[0].children[0].children[2].children[3].children[0].children[0]",
                                name: "ChipIcon_fridge_on",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_zxpz0wru",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[2].children[3].children[0].children[1]",
                                name: "ChipLabel_fridge_on",
                                text: "Fridge",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_co7mms6l",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[4]",
                        name: "Chip_freezer_rest",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_gzdvtlpy",
                            type: "Row",
                            path: "InventoryPage.body[0].children[0].children[2].children[4].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_h6m1q7r0",
                                type: "Container",
                                path: "InventoryPage.body[0].children[0].children[2].children[4].children[0].children[0]",
                                name: "ChipIcon_freezer_rest",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_ny9jxe9m",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[2].children[4].children[0].children[1]",
                                name: "ChipLabel_freezer_rest",
                                text: "Freezer",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_9j1jtsme",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[5]",
                        name: "Chip_freezer_on",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_tw9g5j9f",
                            type: "Row",
                            path: "InventoryPage.body[0].children[0].children[2].children[5].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_mbsr54n9",
                                type: "Container",
                                path: "InventoryPage.body[0].children[0].children[2].children[5].children[0].children[0]",
                                name: "ChipIcon_freezer_on",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_arhn79ad",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[2].children[5].children[0].children[1]",
                                name: "ChipLabel_freezer_on",
                                text: "Freezer",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_hth5c484",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[6]",
                        name: "Chip_pantry_rest",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_k5jtry6d",
                            type: "Row",
                            path: "InventoryPage.body[0].children[0].children[2].children[6].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_irtbaffp",
                                type: "Container",
                                path: "InventoryPage.body[0].children[0].children[2].children[6].children[0].children[0]",
                                name: "ChipIcon_pantry_rest",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_5m5ey9qw",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[2].children[6].children[0].children[1]",
                                name: "ChipLabel_pantry_rest",
                                text: "Pantry",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_8okmv3pe",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[7]",
                        name: "Chip_pantry_on",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_b4cmh1hh",
                            type: "Row",
                            path: "InventoryPage.body[0].children[0].children[2].children[7].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_5timodsx",
                                type: "Container",
                                path: "InventoryPage.body[0].children[0].children[2].children[7].children[0].children[0]",
                                name: "ChipIcon_pantry_on",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_8q5ucvs6",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[2].children[7].children[0].children[1]",
                                name: "ChipLabel_pantry_on",
                                text: "Pantry",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_t5kqz20a",
                    type: "Container",
                    path: "InventoryPage.body[0].children[0].children[3]",
                    name: "InventorySearch",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_wgtao0m0",
                        type: "Row",
                        path: "InventoryPage.body[0].children[0].children[3].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_tdh6uucj",
                            type: "Container",
                            path: "InventoryPage.body[0].children[0].children[3].children[0].children[0]",
                            name: "SearchIcon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "TextField_1xwrix4n",
                            type: "TextField",
                            path: "InventoryPage.body[0].children[0].children[3].children[0].children[1]",
                            name: "InventorySearchField",
                            text: "Search your food",
                            triggers: const <String>[
                              "ON_TEXTFIELD_CHANGE",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "GridView_elxnrddg",
                    type: "GridView",
                    path: "InventoryPage.body[0].children[0].children[4]",
                    name: "InventoryGrid",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_j90wwotm",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[4].children[0]",
                        name: "InventoryCard",
                        componentName: "FoodCard",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_rti5uqk1",
                    type: "Column",
                    path: "InventoryPage.body[0].children[0].children[5]",
                    name: "InventoryStates",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_k0lv8uta",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[5].children[0]",
                        name: "InventoryOffline",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_du9igfju",
                            type: "Column",
                            path: "InventoryPage.body[0].children[0].children[5].children[0].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_6c1ocbwz",
                                type: "Icon",
                                path: "InventoryPage.body[0].children[0].children[5].children[0].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_tgcmvfav",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[5].children[0].children[0].children[1]",
                                name: "InventoryOfflineTitle",
                                text: "Can’t reach your kitchen.",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_laaa54b2",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[5].children[0].children[0].children[2]",
                                name: "InventoryOfflineBody",
                                text: "No signal, or the connection dropped. Your food will show again as soon as you are back online.",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_1sq96ljg",
                                type: "Button",
                                path: "InventoryPage.body[0].children[0].children[5].children[0].children[0].children[3]",
                                name: "InventoryOfflineRetry",
                                text: "Try again",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_dfajl791",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[5].children[1]",
                        name: "InventoryLoading",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "ProgressBar_1h6m3foq",
                            type: "ProgressBar",
                            path: "InventoryPage.body[0].children[0].children[5].children[1].children[0]",
                            name: "InventorySpinner",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_4l0ewk2n",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[5].children[2]",
                        name: "InventoryEmptyKitchen",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_cv33qief",
                            type: "Column",
                            path: "InventoryPage.body[0].children[0].children[5].children[2].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_4fme33x8",
                                type: "Container",
                                path: "InventoryPage.body[0].children[0].children[5].children[2].children[0].children[0]",
                                name: "InventoryEmptyTile",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_8fdbv52b",
                                    type: "Container",
                                    path: "InventoryPage.body[0].children[0].children[5].children[2].children[0].children[0].children[0]",
                                    name: "InventoryEmptyIcon",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_xonowixw",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[5].children[2].children[0].children[1]",
                                name: "InventoryEmptyTitle",
                                text: "Your fresh start.",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_4re19ngo",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[5].children[2].children[0].children[2]",
                                name: "InventoryEmptyBody",
                                text: "Add a few things you already have and this is where they will live.",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_d423zwm0",
                                type: "Button",
                                path: "InventoryPage.body[0].children[0].children[5].children[2].children[0].children[3]",
                                name: "InventoryEmptyAdd",
                                text: "Add your first item",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_h8k9k2yy",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[5].children[3]",
                        name: "InventoryNoMatches",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_c941as6y",
                            type: "Column",
                            path: "InventoryPage.body[0].children[0].children[5].children[3].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_l32z39cj",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[5].children[3].children[0].children[0]",
                                name: "InventoryNoMatchesTitle",
                                text: "No matching items",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_dcdlerjz",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[5].children[3].children[0].children[1]",
                                name: "InventoryNoMatchesBody",
                                text: "Nothing here matches that search or filter.",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_3nuogwb1",
                                type: "Button",
                                path: "InventoryPage.body[0].children[0].children[5].children[3].children[0].children[2]",
                                name: "InventoryClearFilters",
                                text: "Clear filters",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

