// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final inventoryPageHandle = ffai.ProjectPageHandle<InventoryPageParams, InventoryPageState>(
  name: "InventoryPage",
  key: "Scaffold_2n83y1be",
  route: "inventory",
  params: const InventoryPageParams(),
  state: const InventoryPageState(),
  widgets: InventoryPageWidgets.tree,
);

final class InventoryPageParams {
  const InventoryPageParams();
}

final class InventoryPageState {
  const InventoryPageState();
  ffai.ProjectStateFieldHandle get allItems =>
      const ffai.ProjectStateFieldHandle(
        name: "allItems",
        key: "7qp1zzza",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get filter =>
      const ffai.ProjectStateFieldHandle(
        name: "filter",
        key: "5ibv1jdw",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get items =>
      const ffai.ProjectStateFieldHandle(
        name: "items",
        key: "ehauywrm",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get query =>
      const ffai.ProjectStateFieldHandle(
        name: "query",
        key: "j6r1qgcr",
        typeName: "String",
      );
}

abstract final class InventoryPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_2n83y1be",
      type: "Scaffold",
      path: "InventoryPage",
      name: "InventoryPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_9u8bwt59",
            type: "Container",
            path: "InventoryPage.body[0]",
            name: "InventoryBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_29fevh38",
                type: "Column",
                path: "InventoryPage.body[0].children[0]",
                name: "InventoryColumn",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_hg1a3ug3",
                    type: "Text",
                    path: "InventoryPage.body[0].children[0].children[0]",
                    name: "InventoryHeading",
                    text: "Your kitchen.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_403jzbco",
                    type: "Text",
                    path: "InventoryPage.body[0].children[0].children[1]",
                    name: "InventoryLede",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Row_s57bi5d1",
                    type: "Row",
                    path: "InventoryPage.body[0].children[0].children[2]",
                    name: "InventoryFilterChips",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_n46f3tsc",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[0]",
                        name: "Chip_all_rest",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_gzj6xpco",
                            type: "Text",
                            path: "InventoryPage.body[0].children[0].children[2].children[0].children[0]",
                            name: "ChipLabel_all_rest",
                            text: "All",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_8ycngcyi",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[1]",
                        name: "Chip_all_on",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_nal9okg1",
                            type: "Text",
                            path: "InventoryPage.body[0].children[0].children[2].children[1].children[0]",
                            name: "ChipLabel_all_on",
                            text: "All",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_eegrtxh1",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[2]",
                        name: "Chip_fridge_rest",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_qokercm5",
                            type: "Text",
                            path: "InventoryPage.body[0].children[0].children[2].children[2].children[0]",
                            name: "ChipLabel_fridge_rest",
                            text: "Fridge",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_uy4c7vbp",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[3]",
                        name: "Chip_fridge_on",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_ysgk047z",
                            type: "Text",
                            path: "InventoryPage.body[0].children[0].children[2].children[3].children[0]",
                            name: "ChipLabel_fridge_on",
                            text: "Fridge",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_tmk7tl64",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[4]",
                        name: "Chip_freezer_rest",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_vuxkupm7",
                            type: "Text",
                            path: "InventoryPage.body[0].children[0].children[2].children[4].children[0]",
                            name: "ChipLabel_freezer_rest",
                            text: "Freezer",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_yltp1lgm",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[5]",
                        name: "Chip_freezer_on",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_goufnb6p",
                            type: "Text",
                            path: "InventoryPage.body[0].children[0].children[2].children[5].children[0]",
                            name: "ChipLabel_freezer_on",
                            text: "Freezer",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_kwne5zo2",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[6]",
                        name: "Chip_pantry_rest",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_7at15roq",
                            type: "Text",
                            path: "InventoryPage.body[0].children[0].children[2].children[6].children[0]",
                            name: "ChipLabel_pantry_rest",
                            text: "Pantry",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_pinyznaj",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[2].children[7]",
                        name: "Chip_pantry_on",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_oegd9qt6",
                            type: "Text",
                            path: "InventoryPage.body[0].children[0].children[2].children[7].children[0]",
                            name: "ChipLabel_pantry_on",
                            text: "Pantry",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_t5kqz20a",
                    type: "Container",
                    path: "InventoryPage.body[0].children[0].children[3]",
                    name: "InventorySearch",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_wgtao0m0",
                        type: "Row",
                        path: "InventoryPage.body[0].children[0].children[3].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_md74t2io",
                            type: "Icon",
                            path: "InventoryPage.body[0].children[0].children[3].children[0].children[0]",
                            name: "SearchIcon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "TextField_1xwrix4n",
                            type: "TextField",
                            path: "InventoryPage.body[0].children[0].children[3].children[0].children[1]",
                            name: "InventorySearchField",
                            text: "Search your food",
                            triggers: const <String>[
                              "ON_TEXTFIELD_CHANGE",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "GridView_elxnrddg",
                    type: "GridView",
                    path: "InventoryPage.body[0].children[0].children[4]",
                    name: "InventoryGrid",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_j90wwotm",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[4].children[0]",
                        name: "InventoryCard",
                        componentName: "FoodCard",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_rti5uqk1",
                    type: "Column",
                    path: "InventoryPage.body[0].children[0].children[5]",
                    name: "InventoryStates",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_dfajl791",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[5].children[0]",
                        name: "InventoryLoading",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "ProgressBar_1h6m3foq",
                            type: "ProgressBar",
                            path: "InventoryPage.body[0].children[0].children[5].children[0].children[0]",
                            name: "InventorySpinner",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_4l0ewk2n",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[5].children[1]",
                        name: "InventoryEmptyKitchen",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_cv33qief",
                            type: "Column",
                            path: "InventoryPage.body[0].children[0].children[5].children[1].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_4fme33x8",
                                type: "Container",
                                path: "InventoryPage.body[0].children[0].children[5].children[1].children[0].children[0]",
                                name: "InventoryEmptyTile",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_xrtogq74",
                                    type: "Icon",
                                    path: "InventoryPage.body[0].children[0].children[5].children[1].children[0].children[0].children[0]",
                                    name: "Icon",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_xonowixw",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[5].children[1].children[0].children[1]",
                                name: "InventoryEmptyTitle",
                                text: "Your fresh start.",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_4re19ngo",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[5].children[1].children[0].children[2]",
                                name: "InventoryEmptyBody",
                                text: "Add a few things you already have and this is where they will live.",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_d423zwm0",
                                type: "Button",
                                path: "InventoryPage.body[0].children[0].children[5].children[1].children[0].children[3]",
                                name: "InventoryEmptyAdd",
                                text: "Add your first item",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_h8k9k2yy",
                        type: "Container",
                        path: "InventoryPage.body[0].children[0].children[5].children[2]",
                        name: "InventoryNoMatches",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_c941as6y",
                            type: "Column",
                            path: "InventoryPage.body[0].children[0].children[5].children[2].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_l32z39cj",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[5].children[2].children[0].children[0]",
                                name: "InventoryNoMatchesTitle",
                                text: "No matching items",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_dcdlerjz",
                                type: "Text",
                                path: "InventoryPage.body[0].children[0].children[5].children[2].children[0].children[1]",
                                name: "InventoryNoMatchesBody",
                                text: "Nothing here matches that search or filter.",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_3nuogwb1",
                                type: "Button",
                                path: "InventoryPage.body[0].children[0].children[5].children[2].children[0].children[2]",
                                name: "InventoryClearFilters",
                                text: "Clear filters",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

