// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final mapReviewPageHandle = ffai.ProjectPageHandle<MapReviewPageParams, MapReviewPageState>(
  name: "MapReviewPage",
  key: "Scaffold_v3ckkpfd",
  route: "shelf-review",
  params: const MapReviewPageParams(),
  state: const MapReviewPageState(),
  widgets: MapReviewPageWidgets.tree,
);

final class MapReviewPageParams {
  const MapReviewPageParams();
}

final class MapReviewPageState {
  const MapReviewPageState();
}

abstract final class MapReviewPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_v3ckkpfd",
      type: "Scaffold",
      path: "MapReviewPage",
      name: "MapReviewPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_s7nljyxz",
            type: "Container",
            path: "MapReviewPage.body[0]",
            name: "MapReviewBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_7tkkjrae",
                type: "Column",
                path: "MapReviewPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_4hvy88ix",
                    type: "Row",
                    path: "MapReviewPage.body[0].children[0].children[0]",
                    name: "MapReviewBackRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_zawn4kzw",
                        type: "Container",
                        path: "MapReviewPage.body[0].children[0].children[0].children[0]",
                        name: "MapReviewBack",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_es41tzuj",
                            type: "Icon",
                            path: "MapReviewPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Icon",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_621h98c8",
                    type: "Text",
                    path: "MapReviewPage.body[0].children[0].children[1]",
                    name: "MapReviewHeadline",
                    text: "Check what we found.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_gunn8ze6",
                    type: "Text",
                    path: "MapReviewPage.body[0].children[0].children[2]",
                    name: "MapReviewLede",
                    text: "Tap an outline or its line: ✓ to add it, ✕ to leave it out, or tap the name to fix it.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_bh11gbi4",
                    type: "Container",
                    path: "MapReviewPage.body[0].children[0].children[3]",
                    name: "MapReading",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_k1k1imxi",
                        type: "Row",
                        path: "MapReviewPage.body[0].children[0].children[3].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "ProgressBar_9gj3r7hi",
                            type: "ProgressBar",
                            path: "MapReviewPage.body[0].children[0].children[3].children[0].children[0]",
                            name: "ProgressBar",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_m5mqjtkg",
                            type: "Text",
                            path: "MapReviewPage.body[0].children[0].children[3].children[0].children[1]",
                            name: "MapReadingText",
                            text: "Reading your photo. This takes a few seconds.",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_km24grqo",
                    type: "Container",
                    path: "MapReviewPage.body[0].children[0].children[4]",
                    name: "MapReviewMap",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_414bq0ps",
                    type: "Button",
                    path: "MapReviewPage.body[0].children[0].children[5]",
                    name: "MapReviewAnother",
                    text: "+ Add another photo",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_h6jd0a8x",
                    type: "Text",
                    path: "MapReviewPage.body[0].children[0].children[6]",
                    name: "MapReviewKeeps",
                    text: "No dates to type. Each food gets a typical keep time for where it is kept. Add a printed date later if you want an exact reminder.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_j1ribpzp",
                    type: "Text",
                    path: "MapReviewPage.body[0].children[0].children[7]",
                    name: "MapReviewNoneTicked",
                    text: "Tick at least one food to add it.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_w6qln0ju",
                    type: "Button",
                    path: "MapReviewPage.body[0].children[0].children[8]",
                    name: "MapReviewAdd",
                    text: "Add the ticked foods to your kitchen",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

