// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final profilePageHandle = ffai.ProjectPageHandle<ProfilePageParams, ProfilePageState>(
  name: "ProfilePage",
  key: "Scaffold_vzfr6iuh",
  route: "profile",
  params: const ProfilePageParams(),
  state: const ProfilePageState(),
  widgets: ProfilePageWidgets.tree,
);

final class ProfilePageParams {
  const ProfilePageParams();
}

final class ProfilePageState {
  const ProfilePageState();
  ffai.ProjectStateFieldHandle get households =>
      const ffai.ProjectStateFieldHandle(
        name: "households",
        key: "cqyzxb2m",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get loadedOk =>
      const ffai.ProjectStateFieldHandle(
        name: "loadedOk",
        key: "6fi2z1dr",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get me =>
      const ffai.ProjectStateFieldHandle(
        name: "me",
        key: "28v6rr7u",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get offline =>
      const ffai.ProjectStateFieldHandle(
        name: "offline",
        key: "hppjwquy",
        typeName: "Boolean",
      );
}

abstract final class ProfilePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_vzfr6iuh",
      type: "Scaffold",
      path: "ProfilePage",
      name: "ProfilePage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_mquvfrfw",
            type: "Container",
            path: "ProfilePage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_k59nd9hp",
                type: "Column",
                path: "ProfilePage.body[0].children[0]",
                name: "ProfileColumn",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_1127ahyn",
                    type: "Text",
                    path: "ProfilePage.body[0].children[0].children[0]",
                    name: "ProfileHeadline",
                    text: "Your space.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Row_b5rptfl4",
                    type: "Row",
                    path: "ProfilePage.body[0].children[0].children[1]",
                    name: "ProfileIdentity",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_lrqeercs",
                        type: "Container",
                        path: "ProfilePage.body[0].children[0].children[1].children[0]",
                        name: "ProfileAvatar",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_xsk3jrii",
                            type: "Text",
                            path: "ProfilePage.body[0].children[0].children[1].children[0].children[0]",
                            name: "ProfileAvatarLetter",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Column_g3h34dxz",
                        type: "Column",
                        path: "ProfilePage.body[0].children[0].children[1].children[1]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_dpg55zl2",
                            type: "Text",
                            path: "ProfilePage.body[0].children[0].children[1].children[1].children[0]",
                            name: "ProfileName",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_h1mmqqcq",
                            type: "Text",
                            path: "ProfilePage.body[0].children[0].children[1].children[1].children[1]",
                            name: "ProfileHouseholdLine",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_p89i895i",
                    type: "Container",
                    path: "ProfilePage.body[0].children[0].children[2]",
                    name: "ProfileEdit",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_h53xw5ar",
                        type: "Container",
                        path: "ProfilePage.body[0].children[0].children[2].children[0]",
                        name: "ProfileEditRow",
                        componentName: "MenuRow",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_74x3budk",
                    type: "Container",
                    path: "ProfilePage.body[0].children[0].children[3]",
                    name: "ProfileFoodPrefs",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_4woh88af",
                        type: "Container",
                        path: "ProfilePage.body[0].children[0].children[3].children[0]",
                        name: "ProfileFoodPrefsRow",
                        componentName: "MenuRow",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_895szec5",
                    type: "Container",
                    path: "ProfilePage.body[0].children[0].children[4]",
                    name: "ProfileHousehold",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_zpa30x0u",
                        type: "Container",
                        path: "ProfilePage.body[0].children[0].children[4].children[0]",
                        name: "ProfileHouseholdRow",
                        componentName: "MenuRow",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_2sbghpgj",
                    type: "Container",
                    path: "ProfilePage.body[0].children[0].children[5]",
                    name: "ProfileStorage",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_e5hs2wlq",
                        type: "Container",
                        path: "ProfilePage.body[0].children[0].children[5].children[0]",
                        name: "ProfileStorageRow",
                        componentName: "MenuRow",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_nm6yylvz",
                    type: "Container",
                    path: "ProfilePage.body[0].children[0].children[6]",
                    name: "ProfileSecurity",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_a8playwh",
                        type: "Container",
                        path: "ProfilePage.body[0].children[0].children[6].children[0]",
                        name: "ProfileSecurityRow",
                        componentName: "MenuRow",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_kc7jzzk5",
                    type: "Container",
                    path: "ProfilePage.body[0].children[0].children[7]",
                    name: "ProfileShopping",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_0uk7dn99",
                        type: "Container",
                        path: "ProfilePage.body[0].children[0].children[7].children[0]",
                        name: "ProfileShoppingRow",
                        componentName: "MenuRow",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_pxukv1g3",
                    type: "Container",
                    path: "ProfilePage.body[0].children[0].children[8]",
                    name: "ProfileHistory",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_f0gvv0l3",
                        type: "Container",
                        path: "ProfilePage.body[0].children[0].children[8].children[0]",
                        name: "ProfileHistoryRow",
                        componentName: "MenuRow",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_k6ji4lje",
                    type: "Container",
                    path: "ProfilePage.body[0].children[0].children[9]",
                    name: "ProfileReminders",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_4bj4vp89",
                        type: "Container",
                        path: "ProfilePage.body[0].children[0].children[9].children[0]",
                        name: "ProfileRemindersRow",
                        componentName: "MenuRow",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_47tb7tt1",
                    type: "Text",
                    path: "ProfilePage.body[0].children[0].children[10]",
                    name: "ProfileSafetyNote",
                    text: "Use It Fresh provides general food-management guidance, not a guarantee of safety. When in doubt — especially with high-risk food — throw it out and follow local food-safety advice.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_0azlsggn",
                    type: "Container",
                    path: "ProfilePage.body[0].children[0].children[11]",
                    name: "ProfileAppVersion",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_pv4flta3",
                    type: "Container",
                    path: "ProfilePage.body[0].children[0].children[12]",
                    name: "ProfileSignOut",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_vvxnrys1",
                        type: "Text",
                        path: "ProfilePage.body[0].children[0].children[12].children[0]",
                        name: "ProfileSignOutLabel",
                        text: "Sign out",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

