// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final recipesPageHandle = ffai.ProjectPageHandle<RecipesPageParams, RecipesPageState>(
  name: "RecipesPage",
  key: "Scaffold_irmocg01",
  route: "recipes",
  params: const RecipesPageParams(),
  state: const RecipesPageState(),
  widgets: RecipesPageWidgets.tree,
);

final class RecipesPageParams {
  const RecipesPageParams();
}

final class RecipesPageState {
  const RecipesPageState();
}

abstract final class RecipesPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_irmocg01",
      type: "Scaffold",
      path: "RecipesPage",
      name: "RecipesPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_tkuj2pby",
            type: "AppBar",
            path: "RecipesPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_ljff3bhv",
                  type: "Text",
                  path: "RecipesPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Recipes",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_pntz5j54",
            type: "Container",
            path: "RecipesPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_9ydja5ba",
                type: "Column",
                path: "RecipesPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_8nqmvvxy",
                    type: "Container",
                    path: "RecipesPage.body[0].children[0].children[0]",
                    name: "EmptyStateCard",
                    componentName: "EmptyStateCard",
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

