// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final recipesPageHandle = ffai.ProjectPageHandle<RecipesPageParams, RecipesPageState>(
  name: "RecipesPage",
  key: "Scaffold_irmocg01",
  route: "recipes",
  params: const RecipesPageParams(),
  state: const RecipesPageState(),
  widgets: RecipesPageWidgets.tree,
);

final class RecipesPageParams {
  const RecipesPageParams();
}

final class RecipesPageState {
  const RecipesPageState();
}

abstract final class RecipesPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_irmocg01",
      type: "Scaffold",
      path: "RecipesPage",
      name: "RecipesPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_m6w557p6",
            type: "Container",
            path: "RecipesPage.body[0]",
            name: "IdeasPage",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_9ctjs712",
                type: "Column",
                path: "RecipesPage.body[0].children[0]",
                name: "IdeasList",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_myeufboy",
                    type: "Text",
                    path: "RecipesPage.body[0].children[0].children[0]",
                    name: "IdeasTitle",
                    text: "What looks good?",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_7jnnzoek",
                    type: "Container",
                    path: "RecipesPage.body[0].children[0].children[1]",
                    name: "RecipesBody",
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

