// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final remindersPageHandle = ffai.ProjectPageHandle<RemindersPageParams, RemindersPageState>(
  name: "RemindersPage",
  key: "Scaffold_61htb4gi",
  route: "reminders",
  params: const RemindersPageParams(),
  state: const RemindersPageState(),
  widgets: RemindersPageWidgets.tree,
);

final class RemindersPageParams {
  const RemindersPageParams();
}

final class RemindersPageState {
  const RemindersPageState();
  ffai.ProjectStateFieldHandle get daysBefore =>
      const ffai.ProjectStateFieldHandle(
        name: "daysBefore",
        key: "cq1jstgt",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get note =>
      const ffai.ProjectStateFieldHandle(
        name: "note",
        key: "afylbqll",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get remindOn =>
      const ffai.ProjectStateFieldHandle(
        name: "remindOn",
        key: "1mc9zo7v",
        typeName: "Boolean",
      );
}

abstract final class RemindersPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_61htb4gi",
      type: "Scaffold",
      path: "RemindersPage",
      name: "RemindersPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_94z2ve9s",
            type: "Container",
            path: "RemindersPage.body[0]",
            name: "RemindersBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_43s2anej",
                type: "Column",
                path: "RemindersPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_gzn65r89",
                    type: "Row",
                    path: "RemindersPage.body[0].children[0].children[0]",
                    name: "RemindersBackRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_sl9y7pc9",
                        type: "Container",
                        path: "RemindersPage.body[0].children[0].children[0].children[0]",
                        name: "RemindersBack",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_3qxgcarm",
                            type: "Icon",
                            path: "RemindersPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Icon",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_udvfbz96",
                    type: "Text",
                    path: "RemindersPage.body[0].children[0].children[1]",
                    name: "RemindersHeadline",
                    text: "Reminders.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_ynqtb18p",
                    type: "Text",
                    path: "RemindersPage.body[0].children[0].children[2]",
                    name: "RemindersLede",
                    text: "A nudge before something needs using, while there is still time to cook it.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_ksgnt69t",
                    type: "Container",
                    path: "RemindersPage.body[0].children[0].children[3]",
                    name: "RemindersToggle",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_pimlvlyi",
                        type: "Row",
                        path: "RemindersPage.body[0].children[0].children[3].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_ck4kf3bw",
                            type: "Icon",
                            path: "RemindersPage.body[0].children[0].children[3].children[0].children[0]",
                            name: "RemindersOff",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Icon_5utfg2al",
                            type: "Icon",
                            path: "RemindersPage.body[0].children[0].children[3].children[0].children[1]",
                            name: "RemindersOn",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_u204u5bk",
                            type: "Text",
                            path: "RemindersPage.body[0].children[0].children[3].children[0].children[2]",
                            name: "RemindersToggleLabel",
                            text: "Remind me before food goes off",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_a5wz78w1",
                    type: "Text",
                    path: "RemindersPage.body[0].children[0].children[4]",
                    name: "RemindersWhenLabel",
                    text: "HOW LONG BEFORE",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Row_t8fmzxuf",
                    type: "Row",
                    path: "RemindersPage.body[0].children[0].children[5]",
                    name: "RemindersDaysRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_9s0r909y",
                        type: "Container",
                        path: "RemindersPage.body[0].children[0].children[5].children[0]",
                        name: "RemindersDay1",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_h8jw5oei",
                            type: "Text",
                            path: "RemindersPage.body[0].children[0].children[5].children[0].children[0]",
                            name: "RemindersDayLabel1",
                            text: "1 day",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_flygp3ri",
                        type: "Container",
                        path: "RemindersPage.body[0].children[0].children[5].children[1]",
                        name: "RemindersDay2",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_2hrhfomb",
                            type: "Text",
                            path: "RemindersPage.body[0].children[0].children[5].children[1].children[0]",
                            name: "RemindersDayLabel2",
                            text: "2 days",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_txvf3xzl",
                        type: "Container",
                        path: "RemindersPage.body[0].children[0].children[5].children[2]",
                        name: "RemindersDay3",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_qu4hxc7b",
                            type: "Text",
                            path: "RemindersPage.body[0].children[0].children[5].children[2].children[0]",
                            name: "RemindersDayLabel3",
                            text: "3 days",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_90c44vso",
                        type: "Container",
                        path: "RemindersPage.body[0].children[0].children[5].children[3]",
                        name: "RemindersDay5",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_3gcs8qbd",
                            type: "Text",
                            path: "RemindersPage.body[0].children[0].children[5].children[3].children[0]",
                            name: "RemindersDayLabel5",
                            text: "5 days",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_u6p07e91",
                    type: "Container",
                    path: "RemindersPage.body[0].children[0].children[6]",
                    name: "RemindersNote",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_mbxv11v4",
                        type: "Text",
                        path: "RemindersPage.body[0].children[0].children[6].children[0]",
                        name: "RemindersNoteText",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_5cm71fhm",
                    type: "Button",
                    path: "RemindersPage.body[0].children[0].children[7]",
                    name: "RemindersSave",
                    text: "Save reminders",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_lolarpje",
                    type: "Container",
                    path: "RemindersPage.body[0].children[0].children[8]",
                    name: "RemindersHonesty",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_7xvynvsm",
                        type: "Text",
                        path: "RemindersPage.body[0].children[0].children[8].children[0]",
                        name: "RemindersHonestyText",
                        text: "Reminders are set on this phone, so nothing about your kitchen is sent anywhere to make them work. They are refreshed whenever you open the app.",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

