// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final remindersPageHandle = ffai.ProjectPageHandle<RemindersPageParams, RemindersPageState>(
  name: "RemindersPage",
  key: "Scaffold_61htb4gi",
  route: "reminders",
  params: const RemindersPageParams(),
  state: const RemindersPageState(),
  widgets: RemindersPageWidgets.tree,
);

final class RemindersPageParams {
  const RemindersPageParams();
}

final class RemindersPageState {
  const RemindersPageState();
  ffai.ProjectStateFieldHandle get daysBefore =>
      const ffai.ProjectStateFieldHandle(
        name: "daysBefore",
        key: "cq1jstgt",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get note =>
      const ffai.ProjectStateFieldHandle(
        name: "note",
        key: "afylbqll",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get remindOn =>
      const ffai.ProjectStateFieldHandle(
        name: "remindOn",
        key: "1mc9zo7v",
        typeName: "Boolean",
      );
}

abstract final class RemindersPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_61htb4gi",
      type: "Scaffold",
      path: "RemindersPage",
      name: "RemindersPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_94z2ve9s",
            type: "Container",
            path: "RemindersPage.body[0]",
            name: "RemindersBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_43s2anej",
                type: "Column",
                path: "RemindersPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_gzn65r89",
                    type: "Row",
                    path: "RemindersPage.body[0].children[0].children[0]",
                    name: "RemindersBackRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_sl9y7pc9",
                        type: "Container",
                        path: "RemindersPage.body[0].children[0].children[0].children[0]",
                        name: "RemindersBack",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_3qxgcarm",
                            type: "Icon",
                            path: "RemindersPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Icon",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_udvfbz96",
                    type: "Text",
                    path: "RemindersPage.body[0].children[0].children[1]",
                    name: "RemindersHeadline",
                    text: "Reminders.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_98k68p6t",
                    type: "Container",
                    path: "RemindersPage.body[0].children[0].children[2]",
                    name: "ReminderControls",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_lolarpje",
                    type: "Container",
                    path: "RemindersPage.body[0].children[0].children[3]",
                    name: "RemindersHonesty",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_7xvynvsm",
                        type: "Text",
                        path: "RemindersPage.body[0].children[0].children[3].children[0]",
                        name: "RemindersHonestyText",
                        text: "Reminders are set on this phone, so nothing about your kitchen is sent anywhere to make them work. They are refreshed whenever you open the app.",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

