// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final resetPasswordPageHandle = ffai.ProjectPageHandle<ResetPasswordPageParams, ResetPasswordPageState>(
  name: "ResetPasswordPage",
  key: "Scaffold_vmsn4d5n",
  route: "reset-password",
  params: const ResetPasswordPageParams(),
  state: const ResetPasswordPageState(),
  widgets: ResetPasswordPageWidgets.tree,
);

final class ResetPasswordPageParams {
  const ResetPasswordPageParams();
}

final class ResetPasswordPageState {
  const ResetPasswordPageState();
  ffai.ProjectStateFieldHandle get email =>
      const ffai.ProjectStateFieldHandle(
        name: "email",
        key: "0xbo3xu0",
        typeName: "String",
      );
}

abstract final class ResetPasswordPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_vmsn4d5n",
      type: "Scaffold",
      path: "ResetPasswordPage",
      name: "ResetPasswordPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_4d197xfu",
            type: "AppBar",
            path: "ResetPasswordPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_5gqmhayx",
                  type: "Text",
                  path: "ResetPasswordPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Reset password",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_zfraerpg",
            type: "Container",
            path: "ResetPasswordPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_8fs5345k",
                type: "Column",
                path: "ResetPasswordPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_bwujcpe5",
                    type: "Text",
                    path: "ResetPasswordPage.body[0].children[0].children[0]",
                    name: "Text",
                    text: "Enter your email and we will send you a reset link.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_sybqsats",
                    type: "TextField",
                    path: "ResetPasswordPage.body[0].children[0].children[1]",
                    name: "ResetEmailField",
                    text: "Email",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_d4zdk87a",
                    type: "Button",
                    path: "ResetPasswordPage.body[0].children[0].children[2]",
                    name: "SendResetLinkButton",
                    text: "Send reset link",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

