// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final scanAddPageHandle = ffai.ProjectPageHandle<ScanAddPageParams, ScanAddPageState>(
  name: "ScanAddPage",
  key: "Scaffold_fyll5txt",
  route: "scan",
  params: const ScanAddPageParams(),
  state: const ScanAddPageState(),
  widgets: ScanAddPageWidgets.tree,
);

final class ScanAddPageParams {
  const ScanAddPageParams();
}

final class ScanAddPageState {
  const ScanAddPageState();
}

abstract final class ScanAddPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_fyll5txt",
      type: "Scaffold",
      path: "ScanAddPage",
      name: "ScanAddPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_7xfvm3wq",
            type: "Container",
            path: "ScanAddPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_uwpmhn9p",
                type: "Column",
                path: "ScanAddPage.body[0].children[0]",
                name: "ScanAddColumn",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_93bjh6n7",
                    type: "Text",
                    path: "ScanAddPage.body[0].children[0].children[0]",
                    name: "ScanHeadline",
                    text: "What are we adding?",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_pyqu6bbj",
                    type: "Text",
                    path: "ScanAddPage.body[0].children[0].children[1]",
                    name: "ScanLede",
                    text: "A quick photo, a barcode, or a few words.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_221th4ru",
                    type: "Container",
                    path: "ScanAddPage.body[0].children[0].children[2]",
                    name: "Mode_camera",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_epdnamtk",
                        type: "Container",
                        path: "ScanAddPage.body[0].children[0].children[2].children[0]",
                        name: "Mode_cameraRow",
                        componentName: "MenuRow",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_hqur4q94",
                    type: "Container",
                    path: "ScanAddPage.body[0].children[0].children[3]",
                    name: "Mode_barcode",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_rcqm7fx4",
                        type: "Container",
                        path: "ScanAddPage.body[0].children[0].children[3].children[0]",
                        name: "Mode_barcodeRow",
                        componentName: "MenuRow",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_g7jwjr0v",
                    type: "Container",
                    path: "ScanAddPage.body[0].children[0].children[4]",
                    name: "Mode_receipt",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_t984ljsh",
                        type: "Container",
                        path: "ScanAddPage.body[0].children[0].children[4].children[0]",
                        name: "Mode_receiptRow",
                        componentName: "MenuRow",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_u78daphn",
                    type: "Container",
                    path: "ScanAddPage.body[0].children[0].children[5]",
                    name: "Mode_fridge",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_1eajl0m0",
                        type: "Container",
                        path: "ScanAddPage.body[0].children[0].children[5].children[0]",
                        name: "Mode_fridgeRow",
                        componentName: "MenuRow",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_qrmzs15z",
                    type: "Container",
                    path: "ScanAddPage.body[0].children[0].children[6]",
                    name: "Mode_manual",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_ogceshjv",
                        type: "Container",
                        path: "ScanAddPage.body[0].children[0].children[6].children[0]",
                        name: "Mode_manualRow",
                        componentName: "MenuRow",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_2in9cemq",
                    type: "Container",
                    path: "ScanAddPage.body[0].children[0].children[7]",
                    name: "ScanReassurance",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_obbncl68",
                        type: "Text",
                        path: "ScanAddPage.body[0].children[0].children[7].children[0]",
                        name: "ScanReassuranceText",
                        text: "You'll review every suggestion before anything is added.",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_lddb5xy5",
                    type: "Text",
                    path: "ScanAddPage.body[0].children[0].children[8]",
                    name: "ScanSmallPrint",
                    text: "Only scan food and packaging you want to add.",
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

