// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final scanAddPageHandle = ffai.ProjectPageHandle<ScanAddPageParams, ScanAddPageState>(
  name: "ScanAddPage",
  key: "Scaffold_fyll5txt",
  route: "scan",
  params: const ScanAddPageParams(),
  state: const ScanAddPageState(),
  widgets: ScanAddPageWidgets.tree,
);

final class ScanAddPageParams {
  const ScanAddPageParams();
}

final class ScanAddPageState {
  const ScanAddPageState();
}

abstract final class ScanAddPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_fyll5txt",
      type: "Scaffold",
      path: "ScanAddPage",
      name: "ScanAddPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_7xfvm3wq",
            type: "Container",
            path: "ScanAddPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_uwpmhn9p",
                type: "Column",
                path: "ScanAddPage.body[0].children[0]",
                name: "ScanAddColumn",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_93bjh6n7",
                    type: "Text",
                    path: "ScanAddPage.body[0].children[0].children[0]",
                    name: "ScanHeadline",
                    text: "Add something fresh.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_kvfzstpf",
                    type: "Container",
                    path: "ScanAddPage.body[0].children[0].children[1]",
                    name: "ScanReading",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_9ufmg9nz",
                        type: "Row",
                        path: "ScanAddPage.body[0].children[0].children[1].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_117n105i",
                            type: "Container",
                            path: "ScanAddPage.body[0].children[0].children[1].children[0].children[0]",
                            name: "ScanReadingSpinner",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_xhxsnt5h",
                            type: "Text",
                            path: "ScanAddPage.body[0].children[0].children[1].children[0].children[1]",
                            name: "ScanReadingText",
                            text: "Reading your photo. This takes a few seconds.",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_lsglggig",
                    type: "Container",
                    path: "ScanAddPage.body[0].children[0].children[2]",
                    name: "ScanOptions",
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

