// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final scanLinePageHandle = ffai.ProjectPageHandle<ScanLinePageParams, ScanLinePageState>(
  name: "ScanLinePage",
  key: "Scaffold_yh7361y8",
  route: "scan-line",
  params: const ScanLinePageParams(),
  state: const ScanLinePageState(),
  widgets: ScanLinePageWidgets.tree,
);

final class ScanLinePageParams {
  const ScanLinePageParams();
  ffai.ProjectParamHandle get category =>
      const ffai.ProjectParamHandle(
        name: "category",
        key: "p8v0nq8m",
        typeName: "String",
      );
  ffai.ProjectParamHandle get detail =>
      const ffai.ProjectParamHandle(
        name: "detail",
        key: "m9ge5e54",
        typeName: "String",
      );
  ffai.ProjectParamHandle get index =>
      const ffai.ProjectParamHandle(
        name: "index",
        key: "y7kh2uu8",
        typeName: "Integer",
      );
  ffai.ProjectParamHandle get name =>
      const ffai.ProjectParamHandle(
        name: "name",
        key: "72ftk2bq",
        typeName: "String",
      );
  ffai.ProjectParamHandle get place =>
      const ffai.ProjectParamHandle(
        name: "place",
        key: "x0bvfkl5",
        typeName: "String",
      );
  ffai.ProjectParamHandle get quantity =>
      const ffai.ProjectParamHandle(
        name: "quantity",
        key: "77wz35j4",
        typeName: "Integer",
      );
}

final class ScanLinePageState {
  const ScanLinePageState();
}

abstract final class ScanLinePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_yh7361y8",
      type: "Scaffold",
      path: "ScanLinePage",
      name: "ScanLinePage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_e1vn6xk9",
            type: "Container",
            path: "ScanLinePage.body[0]",
            name: "ScanLineBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_2fd9i9bj",
                type: "Column",
                path: "ScanLinePage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_6vy0pj1m",
                    type: "Row",
                    path: "ScanLinePage.body[0].children[0].children[0]",
                    name: "ScanLineBackRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_5duj1sna",
                        type: "Container",
                        path: "ScanLinePage.body[0].children[0].children[0].children[0]",
                        name: "ScanLineBack",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_p2obob8l",
                            type: "Icon",
                            path: "ScanLinePage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Icon",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_tm9id5o3",
                    type: "Text",
                    path: "ScanLinePage.body[0].children[0].children[1]",
                    name: "ScanLineHeadline",
                    text: "Fix this line.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_5iad50zq",
                    type: "Container",
                    path: "ScanLinePage.body[0].children[0].children[2]",
                    name: "ScanLineFields",
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

