// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final scanAddPageHandle = ffai.ProjectPageHandle<ScanAddPageParams, ScanAddPageState>(
  name: "ScanAddPage",
  key: "Scaffold_fyll5txt",
  route: "scan",
  params: const ScanAddPageParams(),
  state: const ScanAddPageState(),
  widgets: ScanAddPageWidgets.tree,
);

final class ScanAddPageParams {
  const ScanAddPageParams();
}

final class ScanAddPageState {
  const ScanAddPageState();
}

abstract final class ScanAddPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_fyll5txt",
      type: "Scaffold",
      path: "ScanAddPage",
      name: "ScanAddPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_fuxewsji",
            type: "AppBar",
            path: "ScanAddPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_rgv9lvci",
                  type: "Text",
                  path: "ScanAddPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Add food",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_7xfvm3wq",
            type: "Container",
            path: "ScanAddPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_5mfz9q3e",
                type: "Column",
                path: "ScanAddPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_onudj8en",
                    type: "Text",
                    path: "ScanAddPage.body[0].children[0].children[0]",
                    name: "Text",
                    text: "Five ways to add food. AI capture lands in Phase 3 — manual entry in Phase 2.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_qs53ip2g",
                    type: "Button",
                    path: "ScanAddPage.body[0].children[0].children[1]",
                    name: "ScanItemButton",
                    text: "Photograph one item",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_es0elad8",
                    type: "Button",
                    path: "ScanAddPage.body[0].children[0].children[2]",
                    name: "ScanBarcodeButton",
                    text: "Scan a barcode",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_9woc6w2b",
                    type: "Button",
                    path: "ScanAddPage.body[0].children[0].children[3]",
                    name: "ScanReceiptButton",
                    text: "Scan a receipt",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_yzxqbens",
                    type: "Button",
                    path: "ScanAddPage.body[0].children[0].children[4]",
                    name: "ScanFridgeButton",
                    text: "Scan your fridge",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_t3tag9d4",
                    type: "Button",
                    path: "ScanAddPage.body[0].children[0].children[5]",
                    name: "AddManualButton",
                    text: "Add manually",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

