// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final scanReviewPageHandle = ffai.ProjectPageHandle<ScanReviewPageParams, ScanReviewPageState>(
  name: "ScanReviewPage",
  key: "Scaffold_hmqrc4zp",
  route: "scan-review",
  params: const ScanReviewPageParams(),
  state: const ScanReviewPageState(),
  widgets: ScanReviewPageWidgets.tree,
);

final class ScanReviewPageParams {
  const ScanReviewPageParams();
}

final class ScanReviewPageState {
  const ScanReviewPageState();
}

abstract final class ScanReviewPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_hmqrc4zp",
      type: "Scaffold",
      path: "ScanReviewPage",
      name: "ScanReviewPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_0hakyj8n",
            type: "Container",
            path: "ScanReviewPage.body[0]",
            name: "ScanReviewBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_l4z3754m",
                type: "Column",
                path: "ScanReviewPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_ab1r5mf3",
                    type: "Row",
                    path: "ScanReviewPage.body[0].children[0].children[0]",
                    name: "ScanReviewBackRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_1inx1t5p",
                        type: "Container",
                        path: "ScanReviewPage.body[0].children[0].children[0].children[0]",
                        name: "ScanReviewBack",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_ybki16qj",
                            type: "Icon",
                            path: "ScanReviewPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Icon",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_df6nbduo",
                    type: "Text",
                    path: "ScanReviewPage.body[0].children[0].children[1]",
                    name: "ScanReviewHeadline",
                    text: "Check what we found.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_2o71ld7d",
                    type: "Text",
                    path: "ScanReviewPage.body[0].children[0].children[2]",
                    name: "ScanReviewCount",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_j8zpcm8j",
                    type: "Text",
                    path: "ScanReviewPage.body[0].children[0].children[3]",
                    name: "ScanReviewLede",
                    text: "Tap a line to fix its name, or ✕ to remove it. Nothing is added until you tap Add.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListView_qk68i5tv",
                    type: "ListView",
                    path: "ScanReviewPage.body[0].children[0].children[4]",
                    name: "ScanReviewItems",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_1gma093s",
                        type: "Container",
                        path: "ScanReviewPage.body[0].children[0].children[4].children[0]",
                        name: "ScanReviewItem",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_36u2x4z8",
                            type: "Row",
                            path: "ScanReviewPage.body[0].children[0].children[4].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_d7rd59ib",
                                type: "Column",
                                path: "ScanReviewPage.body[0].children[0].children[4].children[0].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_ozj1tr50",
                                    type: "Text",
                                    path: "ScanReviewPage.body[0].children[0].children[4].children[0].children[0].children[0].children[0]",
                                    name: "ScanReviewItemName",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_wxfu0tdg",
                                    type: "Text",
                                    path: "ScanReviewPage.body[0].children[0].children[4].children[0].children[0].children[0].children[1]",
                                    name: "ScanReviewItemDetail",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_ubw6de6f",
                                type: "Container",
                                path: "ScanReviewPage.body[0].children[0].children[4].children[0].children[0].children[1]",
                                name: "ScanReviewRemove",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_j2e6w3jg",
                                    type: "Icon",
                                    path: "ScanReviewPage.body[0].children[0].children[4].children[0].children[0].children[1].children[0]",
                                    name: "Icon",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_ogwzsu0v",
                    type: "Text",
                    path: "ScanReviewPage.body[0].children[0].children[5]",
                    name: "ScanReviewDates",
                    text: "Dates are not read from photos. Add them on each item if you want a reminder before it goes off.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_lx9oub52",
                    type: "Button",
                    path: "ScanReviewPage.body[0].children[0].children[6]",
                    name: "ScanReviewAdd",
                    text: "Add them to your kitchen",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

