// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final shoppingListPageHandle = ffai.ProjectPageHandle<ShoppingListPageParams, ShoppingListPageState>(
  name: "ShoppingListPage",
  key: "Scaffold_gkie2vxf",
  route: "shopping-list",
  params: const ShoppingListPageParams(),
  state: const ShoppingListPageState(),
  widgets: ShoppingListPageWidgets.tree,
);

final class ShoppingListPageParams {
  const ShoppingListPageParams();
}

final class ShoppingListPageState {
  const ShoppingListPageState();
  ffai.ProjectStateFieldHandle get items =>
      const ffai.ProjectStateFieldHandle(
        name: "items",
        key: "93r7pu85",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get listId =>
      const ffai.ProjectStateFieldHandle(
        name: "listId",
        key: "ec9o64j5",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get loaded =>
      const ffai.ProjectStateFieldHandle(
        name: "loaded",
        key: "ej1m6d7d",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get typed =>
      const ffai.ProjectStateFieldHandle(
        name: "typed",
        key: "dsmi1s9l",
        typeName: "String",
      );
}

abstract final class ShoppingListPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_gkie2vxf",
      type: "Scaffold",
      path: "ShoppingListPage",
      name: "ShoppingListPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_4glbkz6a",
            type: "Container",
            path: "ShoppingListPage.body[0]",
            name: "ShoppingBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_2zkllu94",
                type: "Column",
                path: "ShoppingListPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_gp06rf90",
                    type: "Row",
                    path: "ShoppingListPage.body[0].children[0].children[0]",
                    name: "ShoppingBackRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_tro5zleo",
                        type: "Container",
                        path: "ShoppingListPage.body[0].children[0].children[0].children[0]",
                        name: "ShoppingBack",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_ci8pbd6r",
                            type: "Icon",
                            path: "ShoppingListPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Icon",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_ez7qs242",
                    type: "Text",
                    path: "ShoppingListPage.body[0].children[0].children[1]",
                    name: "ShoppingHeadline",
                    text: "Shopping list.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_u1l2bnfa",
                    type: "Container",
                    path: "ShoppingListPage.body[0].children[0].children[2]",
                    name: "ShoppingLive",
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

