// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final shoppingListPageHandle = ffai.ProjectPageHandle<ShoppingListPageParams, ShoppingListPageState>(
  name: "ShoppingListPage",
  key: "Scaffold_gkie2vxf",
  route: "shopping-list",
  params: const ShoppingListPageParams(),
  state: const ShoppingListPageState(),
  widgets: ShoppingListPageWidgets.tree,
);

final class ShoppingListPageParams {
  const ShoppingListPageParams();
}

final class ShoppingListPageState {
  const ShoppingListPageState();
  ffai.ProjectStateFieldHandle get items =>
      const ffai.ProjectStateFieldHandle(
        name: "items",
        key: "93r7pu85",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get listId =>
      const ffai.ProjectStateFieldHandle(
        name: "listId",
        key: "ec9o64j5",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get loaded =>
      const ffai.ProjectStateFieldHandle(
        name: "loaded",
        key: "ej1m6d7d",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get typed =>
      const ffai.ProjectStateFieldHandle(
        name: "typed",
        key: "dsmi1s9l",
        typeName: "String",
      );
}

abstract final class ShoppingListPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_gkie2vxf",
      type: "Scaffold",
      path: "ShoppingListPage",
      name: "ShoppingListPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_4glbkz6a",
            type: "Container",
            path: "ShoppingListPage.body[0]",
            name: "ShoppingBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_2zkllu94",
                type: "Column",
                path: "ShoppingListPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_gp06rf90",
                    type: "Row",
                    path: "ShoppingListPage.body[0].children[0].children[0]",
                    name: "ShoppingBackRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_tro5zleo",
                        type: "Container",
                        path: "ShoppingListPage.body[0].children[0].children[0].children[0]",
                        name: "ShoppingBack",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_ci8pbd6r",
                            type: "Icon",
                            path: "ShoppingListPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Icon",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_ez7qs242",
                    type: "Text",
                    path: "ShoppingListPage.body[0].children[0].children[1]",
                    name: "ShoppingHeadline",
                    text: "Shopping list.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_7ux9bowu",
                    type: "Text",
                    path: "ShoppingListPage.body[0].children[0].children[2]",
                    name: "ShoppingCount",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_jqd2at07",
                    type: "TextField",
                    path: "ShoppingListPage.body[0].children[0].children[3]",
                    name: "ShoppingAddField",
                    text: "Add something",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_t5no00a1",
                    type: "Button",
                    path: "ShoppingListPage.body[0].children[0].children[4]",
                    name: "ShoppingAddButton",
                    text: "Add to the list",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_x640ykvr",
                    type: "Container",
                    path: "ShoppingListPage.body[0].children[0].children[5]",
                    name: "ShoppingEmpty",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_n2atoucd",
                        type: "Column",
                        path: "ShoppingListPage.body[0].children[0].children[5].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_0go8aiq5",
                            type: "Text",
                            path: "ShoppingListPage.body[0].children[0].children[5].children[0].children[0]",
                            name: "ShoppingEmptyTitle",
                            text: "Nothing to buy yet.",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_vl7pqto7",
                            type: "Text",
                            path: "ShoppingListPage.body[0].children[0].children[5].children[0].children[1]",
                            name: "ShoppingEmptyLede",
                            text: "Add what you have run out of, and it will be here when you are at the shops.",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListView_omu6zj3c",
                    type: "ListView",
                    path: "ShoppingListPage.body[0].children[0].children[6]",
                    name: "ShoppingItems",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_rp2q4vft",
                        type: "Container",
                        path: "ShoppingListPage.body[0].children[0].children[6].children[0]",
                        name: "ShoppingItem",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_defhxmxh",
                            type: "Row",
                            path: "ShoppingListPage.body[0].children[0].children[6].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_l5zp0hvc",
                                type: "Container",
                                path: "ShoppingListPage.body[0].children[0].children[6].children[0].children[0].children[0]",
                                name: "ShoppingTick",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_ekc7lwx1",
                                    type: "Icon",
                                    path: "ShoppingListPage.body[0].children[0].children[6].children[0].children[0].children[0].children[0]",
                                    name: "ShoppingTickMark",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_rnznlvtu",
                                type: "Text",
                                path: "ShoppingListPage.body[0].children[0].children[6].children[0].children[0].children[1]",
                                name: "ShoppingItemName",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_u0uimeod",
                                type: "Text",
                                path: "ShoppingListPage.body[0].children[0].children[6].children[0].children[0].children[2]",
                                name: "ShoppingItemDone",
                                text: "In the basket",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_a486up98",
                                type: "Container",
                                path: "ShoppingListPage.body[0].children[0].children[6].children[0].children[0].children[3]",
                                name: "ShoppingRemove",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_oggzyoxi",
                                    type: "Icon",
                                    path: "ShoppingListPage.body[0].children[0].children[6].children[0].children[0].children[3].children[0]",
                                    name: "Icon",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_048pv1kp",
                    type: "Button",
                    path: "ShoppingListPage.body[0].children[0].children[7]",
                    name: "ShoppingBasketToKitchen",
                    text: "Put the basket in my kitchen",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

