// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final signInPageHandle = ffai.ProjectPageHandle<SignInPageParams, SignInPageState>(
  name: "SignInPage",
  key: "Scaffold_ile9sdkk",
  route: "",
  params: const SignInPageParams(),
  state: const SignInPageState(),
  widgets: SignInPageWidgets.tree,
);

final class SignInPageParams {
  const SignInPageParams();
}

final class SignInPageState {
  const SignInPageState();
  ffai.ProjectStateFieldHandle get email =>
      const ffai.ProjectStateFieldHandle(
        name: "email",
        key: "jkljho48",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get formShown =>
      const ffai.ProjectStateFieldHandle(
        name: "formShown",
        key: "kfnwvyj8",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get introPending =>
      const ffai.ProjectStateFieldHandle(
        name: "introPending",
        key: "vtg6ylvd",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get introPlaying =>
      const ffai.ProjectStateFieldHandle(
        name: "introPlaying",
        key: "ermn8v3e",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get password =>
      const ffai.ProjectStateFieldHandle(
        name: "password",
        key: "cppcy4nv",
        typeName: "String",
      );
}

abstract final class SignInPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ile9sdkk",
      type: "Scaffold",
      path: "SignInPage",
      name: "SignInPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Stack_24m7nxy8",
            type: "Stack",
            path: "SignInPage.body[0]",
            name: "SignInStack",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Image_sdgiq17v",
                type: "Image",
                path: "SignInPage.body[0].children[0]",
                name: "SignInBackdrop",
              ),
              ffai.ProjectWidgetHandle(
                key: "VideoPlayer_ajavvhaa",
                type: "VideoPlayer",
                path: "SignInPage.body[0].children[1]",
                name: "FridgeOpeningClip",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_o5pu6w5t",
                type: "Container",
                path: "SignInPage.body[0].children[2]",
                name: "ClosedFridgeTapTarget",
                triggers: const <String>[
                  "ON_TAP",
                ],
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "VideoPlayer_b93v1rf2",
                    type: "VideoPlayer",
                    path: "SignInPage.body[0].children[2].children[0]",
                    name: "ClosedFridgeGlint",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_wxfl51lx",
                type: "Container",
                path: "SignInPage.body[0].children[3]",
                name: "SignInFormPanel Margin",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_yyjai4fl",
                    type: "Container",
                    path: "SignInPage.body[0].children[3].children[0]",
                    name: "SignInFormPanel",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_0rhs6apx",
                        type: "Column",
                        path: "SignInPage.body[0].children[3].children[0].children[0]",
                        name: "SignInForm",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_b2xtyddb",
                            type: "Text",
                            path: "SignInPage.body[0].children[3].children[0].children[0].children[0]",
                            name: "SignInBrand",
                            text: "Use It Fresh",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_udt733oh",
                            type: "Text",
                            path: "SignInPage.body[0].children[3].children[0].children[0].children[1]",
                            name: "SignInSlogan",
                            text: "Use what you have. Waste less.",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "TextField_o2faty06",
                            type: "TextField",
                            path: "SignInPage.body[0].children[3].children[0].children[0].children[2]",
                            name: "SignInEmailField",
                            text: "Email",
                            triggers: const <String>[
                              "ON_TEXTFIELD_CHANGE",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "TextField_kadw7ppq",
                            type: "TextField",
                            path: "SignInPage.body[0].children[3].children[0].children[0].children[3]",
                            name: "SignInPasswordField",
                            text: "Password",
                            triggers: const <String>[
                              "ON_TEXTFIELD_CHANGE",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_tkcn9h16",
                            type: "Button",
                            path: "SignInPage.body[0].children[3].children[0].children[0].children[4]",
                            name: "SignInButton",
                            text: "Sign In",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_8ubf8p2a",
                            type: "Button",
                            path: "SignInPage.body[0].children[3].children[0].children[0].children[5]",
                            name: "CreateAccountButton",
                            text: "Create Account",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_8kjdoo65",
                            type: "Button",
                            path: "SignInPage.body[0].children[3].children[0].children[0].children[6]",
                            name: "ForgotPasswordButton",
                            text: "Forgot password?",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

