// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final signUpPageHandle = ffai.ProjectPageHandle<SignUpPageParams, SignUpPageState>(
  name: "SignUpPage",
  key: "Scaffold_6n92ru75",
  route: "sign-up",
  params: const SignUpPageParams(),
  state: const SignUpPageState(),
  widgets: SignUpPageWidgets.tree,
);

final class SignUpPageParams {
  const SignUpPageParams();
}

final class SignUpPageState {
  const SignUpPageState();
  ffai.ProjectStateFieldHandle get confirmPassword =>
      const ffai.ProjectStateFieldHandle(
        name: "confirmPassword",
        key: "lonarwwc",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get email =>
      const ffai.ProjectStateFieldHandle(
        name: "email",
        key: "fezi8qyk",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get password =>
      const ffai.ProjectStateFieldHandle(
        name: "password",
        key: "fxoh0ux7",
        typeName: "String",
      );
}

abstract final class SignUpPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_6n92ru75",
      type: "Scaffold",
      path: "SignUpPage",
      name: "SignUpPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_qy4byny7",
            type: "AppBar",
            path: "SignUpPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_p9oognqk",
                  type: "Text",
                  path: "SignUpPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Create account",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_9w5y70es",
            type: "Container",
            path: "SignUpPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_55z0b135",
                type: "Column",
                path: "SignUpPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "TextField_5z7qq1pu",
                    type: "TextField",
                    path: "SignUpPage.body[0].children[0].children[0]",
                    name: "SignUpEmailField",
                    text: "Email",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_bve20b4b",
                    type: "TextField",
                    path: "SignUpPage.body[0].children[0].children[1]",
                    name: "SignUpPasswordField",
                    text: "Password",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_fys6541l",
                    type: "TextField",
                    path: "SignUpPage.body[0].children[0].children[2]",
                    name: "SignUpConfirmField",
                    text: "Confirm password",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_2nryj8gx",
                    type: "Button",
                    path: "SignUpPage.body[0].children[0].children[3]",
                    name: "CreateAccountButton",
                    text: "Create account",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_5tocp7dj",
                    type: "Text",
                    path: "SignUpPage.body[0].children[0].children[4]",
                    name: "Text",
                    text: "By continuing you agree to our terms and acknowledge that Use It Fresh gives general food-management guidance, not a guarantee of safety.",
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

