// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final storageLocationsPageHandle = ffai.ProjectPageHandle<StorageLocationsPageParams, StorageLocationsPageState>(
  name: "StorageLocationsPage",
  key: "Scaffold_2ohwb2di",
  route: "storage-locations",
  params: const StorageLocationsPageParams(),
  state: const StorageLocationsPageState(),
  widgets: StorageLocationsPageWidgets.tree,
);

final class StorageLocationsPageParams {
  const StorageLocationsPageParams();
}

final class StorageLocationsPageState {
  const StorageLocationsPageState();
  ffai.ProjectStateFieldHandle get isEmpty =>
      const ffai.ProjectStateFieldHandle(
        name: "isEmpty",
        key: "z4pqm5sy",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get locations =>
      const ffai.ProjectStateFieldHandle(
        name: "locations",
        key: "o032miw4",
        typeName: "List<PostgresRow>",
      );
  ffai.ProjectStateFieldHandle get newName =>
      const ffai.ProjectStateFieldHandle(
        name: "newName",
        key: "dvpvnr5k",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get newType =>
      const ffai.ProjectStateFieldHandle(
        name: "newType",
        key: "kucmc2es",
        typeName: "String",
      );
}

abstract final class StorageLocationsPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_2ohwb2di",
      type: "Scaffold",
      path: "StorageLocationsPage",
      name: "StorageLocationsPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_ws394aa8",
            type: "AppBar",
            path: "StorageLocationsPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_gawigr09",
                  type: "Text",
                  path: "StorageLocationsPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Storage locations",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_sbynks9h",
            type: "Container",
            path: "StorageLocationsPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_xzv2a3d6",
                type: "Column",
                path: "StorageLocationsPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_j2h1yoxh",
                    type: "Text",
                    path: "StorageLocationsPage.body[0].children[0].children[0]",
                    name: "StorageLocationsIntro",
                    text: "Where do you keep food? These are used to sort your inventory and to work out how long things last.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListView_hj1izs2i",
                    type: "ListView",
                    path: "StorageLocationsPage.body[0].children[0].children[1]",
                    name: "StorageLocationsList",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_99buocdt",
                        type: "Container",
                        path: "StorageLocationsPage.body[0].children[0].children[1].children[0]",
                        name: "StorageLocationRow",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_lygiqgz7",
                            type: "Row",
                            path: "StorageLocationsPage.body[0].children[0].children[1].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "ListTile_vuj6wyqf",
                                type: "ListTile",
                                path: "StorageLocationsPage.body[0].children[0].children[1].children[0].children[0].children[0]",
                                name: "ListTile",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "IconButton_lyli1xe1",
                                type: "IconButton",
                                path: "StorageLocationsPage.body[0].children[0].children[1].children[0].children[0].children[1]",
                                name: "DeleteLocationButton",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Divider_iwmfoeu2",
                    type: "Divider",
                    path: "StorageLocationsPage.body[0].children[0].children[2]",
                    name: "AddLocationDivider",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_c44mmjf3",
                    type: "Text",
                    path: "StorageLocationsPage.body[0].children[0].children[3]",
                    name: "AddLocationHeading",
                    text: "Add a location",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_utlynq7w",
                    type: "TextField",
                    path: "StorageLocationsPage.body[0].children[0].children[4]",
                    name: "NewLocationNameField",
                    text: "Name",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "DropDown_0o0t8lwa",
                    type: "DropDown",
                    path: "StorageLocationsPage.body[0].children[0].children[5]",
                    name: "NewLocationTypeDropdown",
                    triggers: const <String>[
                      "ON_FORM_WIDGET_SELECTED",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_8lpqe4v9",
                    type: "Button",
                    path: "StorageLocationsPage.body[0].children[0].children[6]",
                    name: "AddLocationButton",
                    text: "Add location",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

