// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final updatePasswordPageHandle = ffai.ProjectPageHandle<UpdatePasswordPageParams, UpdatePasswordPageState>(
  name: "UpdatePasswordPage",
  key: "Scaffold_kucmred8",
  route: "update-password",
  params: const UpdatePasswordPageParams(),
  state: const UpdatePasswordPageState(),
  widgets: UpdatePasswordPageWidgets.tree,
);

final class UpdatePasswordPageParams {
  const UpdatePasswordPageParams();
}

final class UpdatePasswordPageState {
  const UpdatePasswordPageState();
  ffai.ProjectStateFieldHandle get confirmPassword =>
      const ffai.ProjectStateFieldHandle(
        name: "confirmPassword",
        key: "38p89ff2",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get password =>
      const ffai.ProjectStateFieldHandle(
        name: "password",
        key: "my21jls6",
        typeName: "String",
      );
}

abstract final class UpdatePasswordPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_kucmred8",
      type: "Scaffold",
      path: "UpdatePasswordPage",
      name: "UpdatePasswordPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_i2nkfjkm",
            type: "AppBar",
            path: "UpdatePasswordPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_8v9ynyn5",
                  type: "Text",
                  path: "UpdatePasswordPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Update password",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_6m19ntpu",
            type: "Container",
            path: "UpdatePasswordPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_ebld94es",
                type: "Column",
                path: "UpdatePasswordPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_yrohdcn1",
                    type: "Text",
                    path: "UpdatePasswordPage.body[0].children[0].children[0]",
                    name: "Text",
                    text: "Choose a new password. Use at least 8 characters.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_julyevbl",
                    type: "TextField",
                    path: "UpdatePasswordPage.body[0].children[0].children[1]",
                    name: "UpdatePasswordField",
                    text: "New password",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_6ekzr6it",
                    type: "TextField",
                    path: "UpdatePasswordPage.body[0].children[0].children[2]",
                    name: "ConfirmUpdatePasswordField",
                    text: "Confirm new password",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_wmi81uaz",
                    type: "Button",
                    path: "UpdatePasswordPage.body[0].children[0].children[3]",
                    name: "UpdatePasswordButton",
                    text: "Update password",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

