// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final useSoonPageHandle = ffai.ProjectPageHandle<UseSoonPageParams, UseSoonPageState>(
  name: "UseSoonPage",
  key: "Scaffold_nff6rub6",
  route: "use-soon",
  params: const UseSoonPageParams(),
  state: const UseSoonPageState(),
  widgets: UseSoonPageWidgets.tree,
);

final class UseSoonPageParams {
  const UseSoonPageParams();
}

final class UseSoonPageState {
  const UseSoonPageState();
}

abstract final class UseSoonPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_nff6rub6",
      type: "Scaffold",
      path: "UseSoonPage",
      name: "UseSoonPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_2ha7er4i",
            type: "Container",
            path: "UseSoonPage.body[0]",
            name: "UseSoonView",
          ),
        ],
      },
    ),
  );
}

