// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final wasteHistoryPageHandle = ffai.ProjectPageHandle<WasteHistoryPageParams, WasteHistoryPageState>(
  name: "WasteHistoryPage",
  key: "Scaffold_ogzq177i",
  route: "history",
  params: const WasteHistoryPageParams(),
  state: const WasteHistoryPageState(),
  widgets: WasteHistoryPageWidgets.tree,
);

final class WasteHistoryPageParams {
  const WasteHistoryPageParams();
}

final class WasteHistoryPageState {
  const WasteHistoryPageState();
}

abstract final class WasteHistoryPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ogzq177i",
      type: "Scaffold",
      path: "WasteHistoryPage",
      name: "WasteHistoryPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_i21ov6jg",
            type: "Container",
            path: "WasteHistoryPage.body[0]",
            name: "WasteBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_dc9cbn7l",
                type: "Column",
                path: "WasteHistoryPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_56sg9wma",
                    type: "Row",
                    path: "WasteHistoryPage.body[0].children[0].children[0]",
                    name: "WasteBackRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_rvppoglx",
                        type: "Container",
                        path: "WasteHistoryPage.body[0].children[0].children[0].children[0]",
                        name: "WasteBack",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_ywid62ed",
                            type: "Icon",
                            path: "WasteHistoryPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Icon",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_t8avr0b9",
                    type: "Text",
                    path: "WasteHistoryPage.body[0].children[0].children[1]",
                    name: "WasteHeadline",
                    text: "What you used.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_3oylzam0",
                    type: "Text",
                    path: "WasteHistoryPage.body[0].children[0].children[2]",
                    name: "WasteSummary",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_q7wpjpfd",
                    type: "Text",
                    path: "WasteHistoryPage.body[0].children[0].children[3]",
                    name: "WasteDetail",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Row_l9xgqat4",
                    type: "Row",
                    path: "WasteHistoryPage.body[0].children[0].children[4]",
                    name: "WasteFigures",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_6silahf2",
                        type: "Container",
                        path: "WasteHistoryPage.body[0].children[0].children[4].children[0]",
                        name: "WasteUsedTile",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_uhgg8k2j",
                            type: "Column",
                            path: "WasteHistoryPage.body[0].children[0].children[4].children[0].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_wgkk8la5",
                                type: "Text",
                                path: "WasteHistoryPage.body[0].children[0].children[4].children[0].children[0].children[0]",
                                name: "WasteUsedValue",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_hnzhqr1u",
                                type: "Text",
                                path: "WasteHistoryPage.body[0].children[0].children[4].children[0].children[0].children[1]",
                                name: "WasteUsedLabel",
                                text: "used up",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_zzsijve3",
                        type: "Container",
                        path: "WasteHistoryPage.body[0].children[0].children[4].children[1]",
                        name: "WasteBinnedTile",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_kap6meix",
                            type: "Column",
                            path: "WasteHistoryPage.body[0].children[0].children[4].children[1].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_ytt1hsi9",
                                type: "Text",
                                path: "WasteHistoryPage.body[0].children[0].children[4].children[1].children[0].children[0]",
                                name: "WasteBinnedValue",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_bn20fweb",
                                type: "Text",
                                path: "WasteHistoryPage.body[0].children[0].children[4].children[1].children[0].children[1]",
                                name: "WasteBinnedLabel",
                                text: "thrown out",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_ptodtv7j",
                    type: "Container",
                    path: "WasteHistoryPage.body[0].children[0].children[5]",
                    name: "WastePutItBack",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_hgnd8ev5",
                    type: "Container",
                    path: "WasteHistoryPage.body[0].children[0].children[6]",
                    name: "WasteWorstCard",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_zhcc6uyo",
                        type: "Column",
                        path: "WasteHistoryPage.body[0].children[0].children[6].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_4tml258v",
                            type: "Text",
                            path: "WasteHistoryPage.body[0].children[0].children[6].children[0].children[0]",
                            name: "WasteWorstLabel",
                            text: "MOST OFTEN THROWN OUT",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_cm44u6pb",
                            type: "Text",
                            path: "WasteHistoryPage.body[0].children[0].children[6].children[0].children[1]",
                            name: "WasteWorstValue",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_hrp5nigp",
                            type: "Text",
                            path: "WasteHistoryPage.body[0].children[0].children[6].children[0].children[2]",
                            name: "WasteWorstHint",
                            text: "Worth buying less of, or freezing sooner.",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_5uy9k60x",
                    type: "Container",
                    path: "WasteHistoryPage.body[0].children[0].children[7]",
                    name: "WasteTrendCard",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_qtby2sbe",
                        type: "Text",
                        path: "WasteHistoryPage.body[0].children[0].children[7].children[0]",
                        name: "WasteTrendText",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_b9yin71k",
                    type: "Container",
                    path: "WasteHistoryPage.body[0].children[0].children[8]",
                    name: "WasteEmptyNote",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_fprf0mkc",
                        type: "Text",
                        path: "WasteHistoryPage.body[0].children[0].children[8].children[0]",
                        name: "WasteEmptyText",
                        text: "This counts only things you have finished with — marked used up, or thrown out — from the item screen.",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

