"""Second wave of the food picture library (15 Sep): toward a complete grocery catalogue.

Same entry shape as library_catalogue.C. Items here come later in the index, so where a
phrase is shared with an earlier item that has no `needs`, the later (more specific) item
keeps the phrase (see library_catalogue.index_json).
"""
CANS = ["can", "canned", "tin", "tinned"]


def F(id_, subject, match, **o):
    return (id_, "fresh", subject, match, o)


def P(id_, subject, match, **o):
    return (id_, "pack", subject, match, o)


MORE_PROCESSED = ["crumbed", "battered", "dressing", "spread", "seeds", "seed", "ground", "salted", "instant"]

C2 = [
    # ---- more fruit
    F("apricots", "fresh ripe apricots, one halved showing the stone", ["apricot"]),
    F("figs", "fresh purple figs, one halved showing pink seeds", ["fig"], **{"not": ["dried", "jam"]}),
    F("lychees", "fresh lychees, a few peeled showing white flesh", ["lychee", "litchi"]),
    F("papaya", "a ripe papaya cut in half showing orange flesh and black seeds", ["papaya", "pawpaw", "paw paw"]),
    F("persimmons", "ripe orange persimmons, one sliced", ["persimmon", "sharon fruit"]),
    F("dragon-fruit", "a pink dragon fruit cut in half showing speckled white flesh", ["dragon fruit", "pitaya"]),
    F("guava", "fresh guavas, one halved showing pink flesh", ["guava"]),
    F("coconut", "a whole brown coconut and a halved coconut showing white flesh", ["coconut", "fresh coconut"], **{"not": ["milk", "cream", "water", "oil", "desiccated", "shredded", "flakes", "yoghurt", "yogurt", "sugar", "flour", "drink"]}),
    F("rhubarb", "a bunch of fresh pink-red rhubarb stalks", ["rhubarb"]),
    F("blood-oranges", "blood oranges, one cut showing deep crimson flesh", ["blood orange"]),
    F("plantains", "green and yellow plantains", ["plantain"]),
    F("kumquats", "fresh kumquats with a few leaves", ["kumquat", "cumquat"]),
    F("quinces", "fresh golden quinces", ["quince"], **{"not": ["paste"]}),
    F("nectarines", "ripe red nectarines, one halved", ["nectarine"]),
    F("cranberries", "fresh red cranberries in a small pile", ["cranberry"], **{"not": ["dried", "juice", "sauce"]}),
    F("red-grapefruit", "", [], skip=True),
    P("dates", "a small simple bowl of soft medjool dates", ["date", "medjool date", "medjool"], allow=["dried", "dry"], **{"not": ["best before", "use by", "expiry"]}),
    P("raisins", "a small simple bowl of raisins and sultanas", ["raisin", "sultana", "currant"], allow=["dried", "dry"], **{"not": ["toast", "bread", "bran", "cookie", "cookies", "red"]}),
    P("dried-apricots", "a small simple bowl of dried apricots", ["apricot"], needs=["dried", "dry"], allow=["dried", "dry"]),
    P("dried-cranberries", "a small simple bowl of dried cranberries", ["cranberry", "craisin"], needs=["dried", "dry", "craisin", "craisins"], allow=["dried", "dry"]),
    P("prunes", "a small simple bowl of prunes", ["prune", "dried plum"], allow=["dried"]),
    P("mixed-dried-fruit", "a small simple bowl of mixed dried fruit: raisins, apricots, figs and cranberries", ["dried fruit", "mixed fruit", "fruit mix", "trail mix", "dried mango", "dried fig"], allow=["dried", "dry"], **{"not": ["juice", "cake", "bar", "bars"]}),
    # ---- more vegetables
    F("parsnips", "fresh cream-coloured parsnips", ["parsnip"]),
    F("turnips", "fresh purple-topped turnips", ["turnip"]),
    F("swede", "fresh swedes rutabaga, one halved", ["swede", "rutabaga"]),
    F("celeriac", "a whole knobbly celeriac root, one slice cut", ["celeriac"]),
    F("fennel", "fresh fennel bulbs with feathery fronds", ["fennel", "fennel bulb"]),
    F("artichokes", "fresh globe artichokes", ["artichoke", "globe artichoke"], **{"not": ["jar", "marinated", "hearts", "heart"]}),
    F("okra", "fresh green okra pods, one sliced", ["okra", "ladies fingers"]),
    F("snow-peas", "fresh flat snow peas and sugar snap peas", ["snow pea", "sugar snap", "snap pea", "mangetout"]),
    F("bean-sprouts", "a pile of fresh crisp bean sprouts", ["bean sprout", "beansprout", "mung bean sprout"]),
    F("alfalfa-sprouts", "a small nest of fresh alfalfa sprouts", ["alfalfa", "alfalfa sprout", "sprouts mix"]),
    F("watercress", "a bunch of fresh watercress", ["watercress", "cress"]),
    F("silverbeet", "a bunch of fresh rainbow chard silverbeet with colourful stems", ["silverbeet", "silver beet", "chard", "swiss chard", "rainbow chard"]),
    F("choy-sum", "a bunch of fresh choy sum with small yellow flowers", ["choy sum", "choi sum"]),
    F("gai-lan", "a bunch of fresh gai lan chinese broccoli", ["gai lan", "chinese broccoli", "kai lan"]),
    F("wombok", "a fresh wombok napa cabbage, one halved", ["wombok", "napa cabbage", "chinese cabbage", "chinese leaf"]),
    F("daikon", "a fresh white daikon radish, a few slices cut", ["daikon", "white radish", "mooli"]),
    F("taro", "fresh taro roots, one cut", ["taro"]),
    F("cassava", "fresh cassava roots, one cut showing white flesh", ["cassava", "yuca", "manioc"]),
    F("baby-corn", "fresh baby corn spears", ["baby corn"]),
    F("butternut", "a whole butternut pumpkin and a halved one showing orange flesh", ["butternut", "butternut pumpkin", "butternut squash"]),
    F("kohlrabi", "fresh pale green kohlrabi with stems", ["kohlrabi"]),
    F("radicchio", "fresh radicchio and endive heads", ["radicchio", "endive", "chicory", "witlof"]),
    F("microgreens", "a small pile of fresh microgreens", ["microgreen", "micro herb", "micro herbs", "pea shoots", "pea shoot"]),
    F("broad-beans", "fresh broad bean pods, some open showing beans", ["broad bean", "fava bean"]),
    F("lemongrass", "fresh lemongrass stalks", ["lemongrass", "lemon grass"]),
    F("shiitake", "fresh shiitake mushrooms", ["shiitake", "shitake", "shiitake mushroom", "shitake mushroom"], **{"not": ["dried"]}),
    F("oyster-mushrooms", "fresh pale oyster mushrooms", ["oyster mushroom"]),
    F("enoki", "a bunch of fresh enoki mushrooms", ["enoki", "enoki mushroom"]),
    F("portobello", "large fresh portobello mushrooms, gills up", ["portobello", "portabella", "flat mushroom", "field mushroom", "portobello mushroom", "portabella mushroom"]),
    F("broccolini", "a bunch of fresh broccolini", ["broccolini", "tenderstem", "baby broccoli"]),
    F("squash", "fresh yellow pattypan squash and yellow zucchini", ["pattypan", "yellow squash", "summer squash", "baby squash"]),
    F("shallots", "fresh brown french shallots eschalots, one halved", ["eschalot", "french shallot", "brown shallot", "echalion"]),
    F("jalapenos", "fresh green jalapeno peppers", ["jalapeno"], **{"not": ["jar", "pickled", "sliced"]}),
    F("baby-potatoes", "fresh baby chat potatoes", ["baby potato", "chat potato", "new potato", "kipfler"]),
    F("purple-sweet-potato", "", [], skip=True),
    P("coleslaw-mix", "an open plain clear bag of shredded coleslaw mix: green and red cabbage and carrot", ["coleslaw mix", "slaw mix", "shredded cabbage"], allow=["salad"]),
    P("stir-fry-veg", "a plain clear tray of fresh cut stir fry vegetables: capsicum, broccoli, snow peas, carrot", ["stir fry mix", "stir fry veg", "stir fry vegetables", "stirfry mix", "veg mix", "vegetable mix"], **{"not": ["frozen"]}),
    P("water-chestnuts", "an opened plain unbranded metal tin of water chestnuts, some sliced beside", ["water chestnut"], allow=CANS),
    P("bamboo-shoots", "an opened plain unbranded metal tin of bamboo shoots", ["bamboo shoot"], allow=CANS),
    P("canned-beetroot", "an opened plain unbranded metal tin of sliced beetroot", ["beetroot", "beet"], needs=CANS + ["sliced"], allow=CANS),
    # ---- more herbs
    F("sage", "fresh sage leaves", ["sage"], **{"not": ["sausage"]}),
    F("oregano-fresh", "a bunch of fresh oregano", ["oregano", "fresh oregano", "marjoram"], **{"not": ["dried"]}),
    F("tarragon", "fresh tarragon sprigs", ["tarragon"]),
    F("lime-leaves", "fresh glossy kaffir lime leaves", ["kaffir lime leaves", "lime leaves", "makrut lime", "kaffir lime"]),
    F("curry-leaves", "a sprig of fresh curry leaves", ["curry leaves", "curry leaf"], allow=["curry"]),
    F("thai-basil", "a bunch of fresh thai basil with purple stems", ["thai basil", "holy basil"]),
    F("garlic-chives", "a bunch of fresh flat garlic chives", ["garlic chives", "chinese chives"]),
    # ---- spices and seasonings
    P("cinnamon", "cinnamon sticks and a small bowl of ground cinnamon", ["cinnamon", "cinnamon stick", "ground cinnamon"], allow=["ground"], **{"not": ["scroll", "scrolls", "roll", "rolls", "toast", "bun", "buns"]}),
    P("paprika", "a small simple bowl of bright red paprika", ["paprika", "smoked paprika", "sweet paprika"], allow=["smoked", "ground"]),
    P("turmeric", "a small bowl of ground turmeric and a few fresh turmeric roots", ["turmeric"], allow=["ground", "powder"]),
    P("cumin", "a small bowl of cumin seeds and a small bowl of ground cumin", ["cumin", "jeera"], allow=["ground", "seeds", "seed"]),
    P("chilli-flakes", "a small simple bowl of dried red chilli flakes", ["chilli flakes", "chili flakes", "red pepper flakes", "crushed chilli", "chilli powder", "chili powder", "cayenne"], allow=["flakes", "powder", "dried", "ground"]),
    P("black-pepper", "a small bowl of black peppercorns and a wooden pepper grinder", ["black pepper", "pepper", "peppercorn", "cracked pepper", "ground pepper", "white pepper"], allow=["ground"], **{"not": ["capsicum", "bell", "red", "green", "yellow", "chilli", "chili", "jalapeno", "sauce", "steak", "salami", "squid", "calamari", "prawns", "tofu", "chicken"]}),
    P("salt", "a small simple bowl of flaky sea salt with a tiny wooden spoon", ["salt", "sea salt", "table salt", "rock salt", "pink salt", "himalayan salt", "kosher salt", "salt flakes"], allow=["flakes"], **{"not": ["butter", "chips", "crisps", "vinegar", "celery", "garlic", "salted", "cod", "caramel", "pepper"]}),
    P("garlic-powder", "a small simple bowl of garlic powder and garlic granules", ["garlic powder", "garlic granules", "garlic salt", "onion powder", "onion flakes"], allow=["powder", "flakes"]),
    P("curry-powder", "a small simple bowl of golden curry powder", ["curry powder", "garam masala", "masala", "tandoori spice", "ras el hanout"], allow=["curry", "powder", "ground"]),
    P("nutmeg", "whole nutmegs, one grated, beside a small grater", ["nutmeg", "mace", "allspice"], allow=["ground"]),
    P("cloves", "a small simple bowl of whole cloves", ["cloves", "whole cloves"], allow=["ground"], **{"not": ["garlic"]}),
    P("star-anise", "star anise pods in a small simple bowl", ["star anise", "anise", "five spice", "chinese five spice"], allow=["ground"]),
    P("cardamom", "green cardamom pods in a small simple bowl", ["cardamom", "cardamon"], allow=["ground", "seeds"]),
    P("coriander-seeds", "a small simple bowl of coriander seeds", ["coriander seeds", "coriander seed", "ground coriander", "fennel seeds", "fennel seed", "caraway"], allow=["seeds", "seed", "ground"]),
    P("mustard-seeds", "a small simple bowl of yellow and brown mustard seeds", ["mustard seed", "mustard seeds", "mustard powder"], allow=["seeds", "seed", "powder"]),
    P("sesame-seeds", "a small simple bowl of white and black sesame seeds", ["sesame seed", "sesame seeds", "sesame"], allow=["seeds", "seed"], **{"not": ["oil", "bar", "bars", "snaps"]}),
    P("chia-seeds", "a small simple bowl of chia seeds", ["chia", "chia seed", "chia seeds"], allow=["seeds", "seed"], **{"not": ["pudding"]}),
    P("flaxseed", "a small simple bowl of golden and brown flaxseed linseed", ["flaxseed", "flax seed", "linseed", "lsa", "psyllium"], allow=["seeds", "seed", "ground"]),
    P("sunflower-seeds", "a small simple bowl of hulled sunflower seeds and pumpkin seeds pepitas", ["sunflower seed", "sunflower seeds", "pumpkin seed", "pumpkin seeds", "pepitas", "pepita", "mixed seeds", "seed mix"], allow=["seeds", "seed", "salted", "roasted"], **{"not": ["oil", "bread"]}),
    P("vanilla", "a small plain unlabelled glass bottle of vanilla extract and two vanilla pods", ["vanilla", "vanilla extract", "vanilla essence", "vanilla bean", "vanilla paste"], allow=["paste"], **{"not": ["ice", "yogurt", "yoghurt", "custard", "cake", "milk", "protein"]}),
    P("dried-herbs", "a small simple bowl of dried mixed italian herbs", ["mixed herbs", "dried herbs", "italian herbs", "italian seasoning", "herbes de provence", "dried oregano", "dried basil", "dried thyme", "dried parsley", "bay leaves", "bay leaf", "za atar", "zaatar", "seasoning"], allow=["dried", "ground"]),
    P("stock-cubes", "a few plain unwrapped stock cubes and a small bowl of stock powder", ["stock cube", "stock cubes", "bouillon", "stock powder", "oxo", "gravy powder", "gravy granules"], allow=["powder"]),
    P("saffron", "a tiny simple dish of red saffron threads", ["saffron"]),
    P("sumac", "a small simple bowl of deep red sumac", ["sumac", "dukkah", "dukka"], allow=["ground"]),
    # ---- more dairy and eggs
    F("cottage-cheese", "a simple bowl of cottage cheese", ["cottage cheese"]),
    F("ricotta", "a basket-shaped round of fresh white ricotta cheese", ["ricotta"]),
    F("mascarpone", "a simple bowl of smooth mascarpone with a spoon", ["mascarpone"]),
    F("goat-cheese", "a log of soft white goat cheese chevre, a few rounds sliced", ["goat cheese", "goats cheese", "chevre", "goat s cheese"]),
    F("blue-cheese", "a wedge of blue-veined cheese", ["blue cheese", "gorgonzola", "stilton", "roquefort", "danish blue"]),
    F("swiss-cheese", "a wedge of swiss cheese with holes and a few slices", ["swiss cheese", "jarlsberg", "emmental", "gruyere", "havarti"]),
    F("gouda", "a wheel of gouda cheese with a wedge cut, yellow wax rind", ["gouda", "edam", "colby", "manchego", "provolone"]),
    F("paneer", "a block of white paneer, a few cubes cut", ["paneer"]),
    F("labneh", "a simple bowl of thick labneh drizzled with olive oil", ["labneh", "quark", "skyr", "fromage frais"]),
    F("buttermilk", "a glass jug of buttermilk", ["buttermilk"], allow=["milk"]),
    F("kefir", "a plain unlabelled glass bottle of kefir and a glass of it", ["kefir"], allow=["milk"]),
    P("custard", "a simple bowl of smooth yellow vanilla custard", ["custard", "vanilla custard", "pudding", "dessert"], allow=["powder"], **{"not": ["apple", "tart", "tarts", "slice"]}),
    P("chocolate-milk", "a plain unlabelled bottle of chocolate milk and a glass of it", ["chocolate milk", "flavoured milk", "flavored milk", "iced coffee", "choc milk", "strawberry milk", "milk drink", "breaky drink"], allow=["milk"]),
    F("fruit-yogurt", "a simple bowl of pink strawberry yoghurt", ["fruit yogurt", "fruit yoghurt", "strawberry yogurt", "strawberry yoghurt", "flavoured yoghurt", "flavoured yogurt", "yoghurt tub", "yogurt pouch", "yoghurt pouch", "custard pot"]),
    P("condensed-milk", "an opened plain unbranded metal tin of thick sweetened condensed milk with a spoon", ["condensed milk", "evaporated milk", "sweetened condensed milk", "carnation"], allow=CANS + ["milk"]),
    P("milk-powder", "a small simple bowl of milk powder with a scoop", ["milk powder", "powdered milk", "skim milk powder", "formula", "infant formula", "baby formula"], allow=["milk", "powder"]),
    P("whipped-cream", "a simple bowl of fluffy whipped cream", ["whipped cream", "cream can", "spray cream", "aerosol cream"], allow=CANS),
    P("ghee", "an open plain unlabelled glass jar of golden ghee with a spoon", ["ghee", "clarified butter"], allow=["jar"]),
    P("margarine", "an open plain unlabelled tub of soft spreadable margarine with a butter knife", ["margarine", "butter spread", "spreadable", "dairy spread", "flora", "nuttelex"], allow=["spread"]),
    F("quail-eggs", "speckled quail eggs in a small bowl", ["quail egg", "duck egg"]),
    # ---- more meat
    F("chicken-wings", "raw chicken wings on a wooden board", ["chicken wing", "wingette", "chicken nibbles"]),
    F("drumsticks", "raw chicken drumsticks on a wooden board", ["drumstick", "chicken drumstick", "chicken leg", "maryland", "chicken maryland"]),
    F("turkey", "a raw turkey breast joint and turkey mince on a wooden board", ["turkey", "turkey breast", "turkey mince"], **{"not": ["sliced", "shaved", "deli", "ham", "roast", "cooked"]}),
    F("duck", "raw duck breasts with skin on a wooden board", ["duck", "duck breast", "duck leg"], **{"not": ["sauce", "egg", "eggs", "fat"]}),
    F("veal", "raw pale pink veal escalopes on a wooden board", ["veal", "veal schnitzel", "veal cutlet"], **{"not": ["crumbed"]}),
    F("beef-ribs", "raw beef short ribs on a wooden board", ["beef ribs", "short ribs", "short rib", "rib roast", "spare ribs", "spareribs"]),
    F("pork-ribs", "a raw rack of pork ribs on a wooden board", ["pork ribs", "baby back ribs", "pork spare ribs", "american ribs", "ribs"], **{"not": ["cooked", "bbq"]}),
    F("pork-belly", "a raw piece of pork belly with scored skin", ["pork belly"]),
    F("lamb-shanks", "raw lamb shanks on a wooden board", ["lamb shank", "shank"]),
    F("corned-beef", "a raw corned beef silverside joint", ["corned beef", "silverside", "brisket", "beef brisket"]),
    F("roast-joint", "a raw beef roasting joint tied with string, rosemary beside", ["roast beef", "beef roast", "topside", "roasting joint", "rolled roast", "lamb leg", "leg of lamb", "pork shoulder", "pork roast", "lamb roast", "beef joint"], allow=["roast"], **{"not": ["cooked", "sliced", "shaved"]}),
    F("stewing-beef", "raw diced gravy beef chuck pieces in a simple bowl", ["gravy beef", "chuck steak", "stewing beef", "casserole beef", "beef cubes", "diced lamb", "diced pork", "diced chicken", "osso bucco"], allow=["diced"]),
    F("kangaroo", "raw dark red kangaroo fillets on a wooden board", ["kangaroo", "roo", "venison", "game meat"]),
    F("liver", "raw chicken livers in a simple bowl", ["liver", "chicken liver", "lambs fry", "offal", "kidney"], **{"not": ["bean", "beans", "pate", "paté"]}),
    F("chorizo", "whole and sliced chorizo sausages on a board", ["chorizo", "cabanossi", "kabana", "kransky"], allow=["smoked"]),
    F("salami", "slices of salami arranged on a board", ["salami", "pepperoni", "sopressa", "mortadella", "cured meat"], allow=["smoked"]),
    F("prosciutto", "thin folded slices of prosciutto on a board", ["prosciutto", "parma ham", "jamon", "serrano"], allow=["smoked"]),
    F("frankfurts", "plain frankfurt hot dog sausages on a board", ["frankfurt", "frankfurter", "hot dog", "hotdog", "wiener", "cocktail frankfurt", "saveloy", "cheerio"], **{"not": ["roll", "rolls", "bun", "buns"]}),
    F("meatballs", "raw meatballs on a board", ["meatball", "rissole", "kofta"], **{"not": ["cooked", "sauce", "frozen"]}),
    F("burger-patties", "raw beef burger patties separated by paper on a board", ["burger patty", "burger patties", "beef patty", "beef patties", "hamburger", "burgers", "burger"], **{"not": ["bun", "buns", "roll", "rolls", "cooked"]}),
    F("schnitzel", "raw crumbed chicken schnitzels on a board", ["schnitzel", "crumbed chicken", "chicken kiev", "kiev", "cordon bleu", "crumbed steak", "crumbed veal", "crumbed lamb"], allow=["crumbed"], **{"not": ["cooked"]}),
    P("chicken-nuggets", "golden chicken nuggets on a simple plate", ["chicken nugget", "nugget", "chicken tenders", "popcorn chicken", "chicken strips"], allow=["crumbed", "battered", "frozen"]),
    P("roast-chicken", "a whole golden roast chicken on a board", ["roast chicken", "bbq chicken", "barbecue chicken", "rotisserie chicken", "cooked chicken", "chicken breast cooked", "shredded chicken", "chicken schnitzel cooked"], allow=["roast", "roasted", "cooked"]),
    P("deli-turkey", "thin slices of cooked turkey and chicken breast folded on a board", ["sliced turkey", "shaved turkey", "shaved chicken", "sliced chicken", "chicken slices", "deli chicken", "turkey slices", "chicken loaf", "luncheon meat", "devon", "pastrami", "roast beef slices", "shaved beef"], allow=["smoked", "roast", "cooked"]),
    # ---- more seafood
    F("tuna-steak", "raw deep red tuna steaks on a board with sesame", ["tuna steak", "sashimi tuna", "fresh tuna", "yellowfin", "sashimi", "kingfish", "swordfish"]),
    P("cooked-prawns", "cooked pink prawns in a simple bowl with a lemon wedge", ["cooked prawn", "cooked shrimp", "cooked prawns", "prawn cocktail"], allow=["cooked"]),
    F("mussels", "fresh black mussels in a simple bowl", ["mussel", "pipi", "pipis", "cockle", "clam", "vongole"]),
    F("oysters", "fresh oysters on the half shell on crushed ice with lemon", ["oyster"], **{"not": ["sauce", "mushroom", "mushrooms"]}),
    F("scallops", "fresh raw scallops on a simple plate", ["scallop"]),
    F("calamari", "raw squid tubes and rings on a board", ["calamari", "squid", "octopus", "cuttlefish"], **{"not": ["crumbed", "battered", "salt and pepper", "ink"]}),
    F("crab", "a whole cooked crab and crab claws on a board", ["crab", "blue swimmer", "mud crab", "lobster", "crayfish", "bug", "bugs", "moreton bay bug", "yabby"], **{"not": ["stick", "sticks", "cake", "cakes", "apple"]}),
    F("whole-fish", "a whole fresh raw snapper fish on a board with lemon", ["whole fish", "whole snapper", "whole trout", "whole barramundi", "mackerel", "sardine", "fresh sardines"], **{"not": CANS}),
    P("fish-fingers", "golden crumbed fish fingers on a simple plate", ["fish finger", "fish fingers", "fish cake", "fish cakes", "crumbed fish", "battered fish", "fish bites", "fish and chips"], allow=["crumbed", "battered", "frozen", "cake", "chips"]),
    P("anchovies", "an opened plain unbranded small flat tin of anchovy fillets in oil", ["anchovy", "anchovies", "anchovy fillets"], allow=CANS + ["oil", "jar"]),
    P("canned-salmon", "an opened plain unbranded metal tin of pink salmon with a fork", ["salmon", "red salmon", "pink salmon"], needs=CANS, allow=CANS),
    P("sardines-tin", "an opened plain unbranded flat tin of sardines in oil", ["sardine", "mackerel", "kipper"], needs=CANS + ["oil"], allow=CANS + ["oil", "smoked"]),
    P("crab-sticks", "a few crab sticks seafood extender on a simple plate", ["crab stick", "crab sticks", "seafood extender", "surimi", "imitation crab"]),
    # ---- more bakery
    F("baguette", "crusty french baguettes", ["baguette", "french stick", "french bread", "vienna loaf", "turkish bread", "pide"]),
    F("ciabatta", "a rustic ciabatta loaf, a few slices cut", ["ciabatta", "focaccia", "pane di casa", "italian bread"]),
    F("rye-bread", "a dark rye loaf, sliced, with caraway seeds", ["rye bread", "rye", "pumpernickel", "wholemeal bread", "multigrain bread", "grain bread", "seeded bread", "wholegrain bread", "brown bread", "spelt bread", "gluten free bread"], allow=["seeds"]),
    F("pita", "a stack of soft round pita pocket breads", ["pita", "pita bread", "pitta", "lebanese bread", "pocket bread"]),
    F("naan", "soft golden naan breads, one torn", ["naan", "nan bread", "roti", "chapati", "paratha", "flatbread"]),
    F("hot-cross-buns", "glossy hot cross buns", ["hot cross bun", "fruit bun", "iced bun", "finger bun", "chelsea bun"]),
    F("muffins", "golden blueberry muffins", ["muffin", "blueberry muffin", "choc chip muffin", "cupcake", "friand"], **{"not": ["english"]}),
    P("cake", "a slice of simple vanilla sponge cake on a plate", ["cake", "sponge cake", "chocolate cake", "carrot cake", "cheesecake", "mud cake", "birthday cake", "slice", "brownie", "lamington"], allow=["cake", "baked"], **{"not": ["rice", "fish", "crab", "pan", "cup", "potato", "corn", "cakes rice"]}),
    F("donuts", "glazed and cinnamon sugar donuts", ["donut", "doughnut"]),
    F("scones", "golden scones, one split with jam and cream", ["scone", "biscuit mix"]),
    P("pancakes", "a small stack of fluffy pancakes on a plate", ["pancake", "crepe", "pikelet", "waffle", "waffles"], allow=["frozen", "cooked"]),
    F("crumpets", "golden crumpets, one toasted with butter", ["crumpet"]),
    F("brioche", "a golden brioche loaf and brioche buns", ["brioche", "challah", "milk bun", "milk buns"]),
    P("pizza-bases", "plain uncooked pizza bases stacked on a board", ["pizza base", "pizza bases", "pizza dough", "pizza crust"], allow=["frozen"]),
    P("breadcrumbs", "a simple bowl of golden breadcrumbs and panko", ["breadcrumbs", "bread crumbs", "panko", "stuffing mix", "croutons"], allow=["dried"]),
    F("raisin-toast", "a sliced raisin fruit loaf", ["raisin toast", "fruit loaf", "raisin bread", "fruit toast", "banana bread", "cinnamon toast"]),
    F("cinnamon-scrolls", "iced cinnamon scrolls", ["cinnamon scroll", "cinnamon roll", "scroll", "danish scroll", "pain au chocolat", "apple turnover", "pastries"]),
    P("meat-pie", "golden baked meat pies, one cut showing filling", ["pie", "meat pie", "chicken pie", "pot pie", "pasty", "pasties", "empanada"], allow=["pie", "baked", "frozen"], **{"not": ["apple", "cherry", "lemon", "custard", "pastry", "mince pie", "pumpkin"]}),
    P("sausage-rolls", "golden flaky sausage rolls", ["sausage roll", "sausage rolls", "party pies", "spinach roll", "spanakopita"], allow=["frozen", "baked"]),
    P("quiche", "a golden quiche with a slice cut", ["quiche", "frittata", "tart", "fruit tart", "apple pie", "lemon tart", "custard tart", "egg tart"], allow=["baked", "pie"]),
    P("taco-shells", "crisp yellow taco shells on a simple plate", ["taco shell", "taco shells", "tortilla bowl", "tostada", "taco kit"]),
    # ---- more pantry: grains, baking, spreads, sweets
    P("brown-rice", "uncooked brown rice in a simple ceramic bowl", ["brown rice", "wild rice", "red rice", "black rice", "wholegrain rice"], allow=["dry"]),
    P("cooked-rice", "a simple bowl of steamed white rice", ["cooked rice", "steamed rice", "microwave rice", "rice pouch", "rice cup", "fried rice", "sushi rice cooked"], allow=["cooked", "fried", "leftover", "leftovers"]),
    P("polenta", "a simple bowl of yellow polenta cornmeal and semolina", ["polenta", "cornmeal", "semolina", "grits", "maize meal"], allow=["dry"]),
    P("barley", "a simple bowl of pearl barley", ["barley", "pearl barley", "buckwheat", "freekeh", "farro", "spelt", "millet", "amaranth"], allow=["dry"], **{"not": ["water", "bread", "flour"]}),
    P("instant-noodles", "a block of dried instant ramen noodles beside a plain unbranded cup noodle", ["instant noodle", "instant noodles", "cup noodle", "cup noodles", "two minute noodles", "2 minute noodles", "maggi", "mi goreng", "ramen noodles packet", "pot noodle"], allow=["noodles", "instant", "dried"]),
    P("gnocchi", "fresh potato gnocchi dusted with flour", ["gnocchi"], allow=["frozen"]),
    P("fresh-pasta", "fresh uncooked ravioli and tortellini dusted with flour", ["ravioli", "tortellini", "fresh pasta", "agnolotti", "cannelloni"], allow=["frozen"], **{"not": ["cooked", "sauce", "tin", "can"]}),
    P("rice-paper", "a stack of dry round rice paper sheets", ["rice paper", "spring roll wrappers", "wonton wrappers", "dumpling wrappers", "gow gee wrappers"], allow=["dry"]),
    P("dried-beans", "small simple bowls of dried beans: kidney, black and white beans", ["dried beans", "dried kidney beans", "dried black beans", "navy beans", "haricot beans", "pinto beans", "borlotti beans", "mung beans", "dried chickpeas"], needs=["dried", "dry", "navy", "haricot", "pinto", "borlotti", "mung"], allow=["dried", "dry"]),
    P("popcorn", "a simple bowl of fluffy popcorn", ["popcorn", "popping corn", "popcorn kernels"], allow=["salted"]),
    P("pretzels", "a simple bowl of salted pretzels", ["pretzel", "twists", "bread sticks", "grissini"], allow=["salted"]),
    P("muesli-bars", "a few plain unwrapped muesli granola bars on a board", ["muesli bar", "muesli bars", "granola bar", "granola bars", "cereal bar", "cereal bars", "protein bar", "protein bars", "nut bar", "nut bars", "snack bar", "bliss balls", "energy balls"]),
    P("granola", "a simple bowl of crunchy granola muesli with nuts", ["granola", "muesli", "bircher", "toasted muesli"], **{"not": ["bar", "bars"]}),
    P("pancake-mix", "a plain unlabelled shaker bottle of pancake mix and a small bowl of batter", ["pancake mix", "shake n bake", "batter mix", "cake mix", "brownie mix", "muffin mix"]),
    P("baking-powder", "small simple bowls of baking powder and bicarbonate of soda with a measuring spoon", ["baking powder", "baking soda", "bicarbonate", "bicarb soda", "bi carb", "cream of tartar", "cornflour", "cornstarch", "corn starch", "custard powder", "gelatine", "gelatin", "arrowroot"], allow=["powder"]),
    P("yeast", "a small simple bowl of dried yeast granules", ["yeast", "dried yeast", "instant yeast"], allow=["dried", "instant"], **{"not": ["spread", "extract", "nutritional"]}),
    P("cocoa", "a small simple bowl of cocoa powder with a spoon", ["cocoa", "cocoa powder", "cacao", "drinking chocolate", "hot chocolate", "milo"], allow=["powder"]),
    P("desiccated-coconut", "a small simple bowl of desiccated shredded coconut and coconut flakes", ["desiccated coconut", "shredded coconut", "coconut flakes", "coconut chips", "coconut threads"], allow=["flakes", "chips", "dried"]),
    P("almond-meal", "a small simple bowl of almond meal", ["almond meal", "ground almonds", "almond flour", "hazelnut meal", "coconut flour"], allow=["ground"]),
    P("almonds", "a simple bowl of whole raw almonds", ["almond", "almonds", "flaked almonds", "slivered almonds"], allow=["roasted", "salted", "flakes"], **{"not": ["milk", "butter", "meal", "flour", "oil", "bar", "croissant"]}),
    P("cashews", "a simple bowl of whole cashews", ["cashew"], allow=["roasted", "salted"], **{"not": ["milk", "butter", "cheese"]}),
    P("walnuts", "a simple bowl of walnut halves and a few whole walnuts", ["walnut", "pecan"], allow=["roasted"], **{"not": ["oil", "bread"]}),
    P("peanuts", "a simple bowl of roasted peanuts", ["peanut", "beer nuts"], allow=["roasted", "salted"], **{"not": ["butter", "oil", "sauce", "satay", "bar", "brittle"]}),
    P("pistachios", "a simple bowl of pistachios in shells", ["pistachio"], allow=["roasted", "salted"]),
    P("pine-nuts", "a small simple bowl of pine nuts", ["pine nut", "pinenut", "pignoli"], allow=["roasted"]),
    P("macadamias", "a simple bowl of macadamia nuts and hazelnuts", ["macadamia", "hazelnut", "brazil nut", "brazil nuts"], allow=["roasted", "salted"], **{"not": ["spread", "meal", "milk", "oil"]}),
    P("tahini", "an open plain unlabelled glass jar of tahini sesame paste with a spoon", ["tahini", "tahina", "sesame paste"], allow=["jar", "paste"]),
    P("choc-spread", "an open plain unlabelled glass jar of chocolate hazelnut spread with a knife", ["chocolate spread", "hazelnut spread", "nutella", "choc spread", "biscoff spread", "cookie butter"], allow=["spread", "jar"]),
    P("yeast-spread", "an open plain unlabelled small jar of dark yeast extract spread and a slice of buttered toast with it", ["vegemite", "marmite", "promite", "yeast extract", "yeast spread"], allow=["spread", "jar"]),
    P("marmalade", "an open plain unlabelled glass jar of orange marmalade with a spoon", ["marmalade", "lemon curd", "passionfruit curd", "fruit spread", "apricot jam"], allow=["jam", "jar", "spread"]),
    P("maple-syrup", "a plain unlabelled glass bottle of amber maple syrup and a small jug", ["maple syrup", "maple", "golden syrup", "agave", "rice malt syrup", "pancake syrup", "treacle", "molasses"], **{"not": ["bacon"]}),
    P("brown-sugar", "a simple bowl of soft brown sugar", ["brown sugar", "raw sugar", "coconut sugar", "demerara", "muscovado", "rapadura"]),
    P("icing-sugar", "a simple bowl of fine white icing sugar dusted around", ["icing sugar", "powdered sugar", "confectioners sugar", "icing mixture", "caster sugar"], allow=["powder"]),
    P("sweetener", "a small simple bowl of stevia sweetener granules", ["sweetener", "stevia", "erythritol", "splenda", "monk fruit", "xylitol", "equal"]),
    P("marshmallows", "a simple bowl of pink and white marshmallows", ["marshmallow"]),
    P("lollies", "a simple bowl of colourful jelly lollies gummy sweets", ["lollies", "lolly", "candy", "sweets", "gummies", "gummy", "jelly beans", "jelly babies", "snakes", "licorice", "liquorice", "mints", "toffee", "caramels"], **{"not": ["jelly crystals"]}),
    P("jelly", "a simple glass dish of red wobbly jelly dessert", ["jelly", "jelly crystals", "jello", "jelly cups"], **{"not": ["beans", "babies", "jam", "lollies", "fish"]}),
    P("protein-powder", "a plain unlabelled tub of protein powder with a scoop of powder", ["protein powder", "whey", "whey protein", "protein shake", "meal replacement", "collagen", "pre workout"], allow=["powder"]),
    P("coffee-pods", "a few plain unbranded silver coffee capsules pods on a saucer", ["coffee pods", "coffee pod", "coffee capsules", "coffee capsule", "nespresso", "pods"], **{"not": ["dishwasher", "laundry", "tea"]}),
    P("instant-coffee", "an open plain unlabelled glass jar of instant coffee granules with a spoon", ["instant coffee", "coffee granules", "nescafe", "coffee sachets", "decaf"], allow=["instant", "jar"]),
    P("green-tea", "a simple glass cup of green tea with loose green tea leaves beside", ["green tea", "matcha", "herbal tea", "chamomile", "peppermint tea", "rooibos", "chai", "earl grey"], allow=["powder"]),
    # ---- oils, vinegars
    P("vegetable-oil", "a plain unlabelled clear plastic bottle of pale golden vegetable oil", ["vegetable oil", "canola oil", "sunflower oil", "rice bran oil", "peanut oil", "cooking oil", "frying oil", "grapeseed oil", "oil spray", "cooking spray", "spray oil"], allow=["oil"]),
    P("sesame-oil", "a small plain unlabelled glass bottle of dark amber sesame oil", ["sesame oil", "chilli oil", "chili oil", "truffle oil", "walnut oil"], allow=["oil"]),
    P("coconut-oil", "an open plain unlabelled glass jar of white coconut oil with a spoon", ["coconut oil"], allow=["oil", "jar"]),
    P("balsamic", "a plain unlabelled glass bottle of dark balsamic vinegar with a small dish of it", ["balsamic", "balsamic vinegar", "balsamic glaze", "red wine vinegar", "sherry vinegar"]),
    P("cider-vinegar", "a plain unlabelled glass bottle of amber apple cider vinegar", ["apple cider vinegar", "cider vinegar", "white wine vinegar", "rice vinegar", "white vinegar", "malt vinegar"]),
    P("lemon-juice", "a plain unlabelled small glass bottle of lemon juice beside a small glass jug", ["lemon juice", "lime juice", "bottled lemon juice"], allow=["juice"]),
    # ---- more sauces and condiments
    P("sweet-chilli-sauce", "a plain unlabelled glass bottle of sweet chilli sauce with a small dish of it", ["sweet chilli sauce", "sweet chili sauce", "sweet chilli", "sweet chili"], allow=["sauce"]),
    P("hot-sauce", "a plain unlabelled small bottle of red hot sauce with a small dish", ["hot sauce", "sriracha", "tabasco", "chilli sauce", "chili sauce", "peri peri", "piri piri", "harissa", "sambal", "gochujang", "chipotle"], allow=["sauce", "paste", "jar"]),
    P("bbq-sauce", "a small simple dish of dark smoky barbecue sauce with a plain unlabelled bottle", ["bbq sauce", "barbecue sauce", "smoky bbq", "steak sauce", "brown sauce", "hp sauce"], allow=["sauce", "smoked"]),
    P("worcestershire", "a plain unlabelled narrow bottle of dark worcestershire sauce", ["worcestershire", "worcester sauce", "fish sauce", "maggi seasoning", "liquid aminos"], allow=["sauce"]),
    P("oyster-sauce", "a small simple dish of glossy dark oyster sauce with a plain unlabelled bottle", ["oyster sauce", "hoisin", "hoisin sauce", "plum sauce", "black bean sauce", "char siu", "xo sauce", "kecap manis"], allow=["sauce"]),
    P("teriyaki", "a small simple dish of glossy teriyaki sauce with a plain unlabelled bottle", ["teriyaki", "teriyaki sauce", "stir fry sauce", "honey soy", "satay sauce", "peanut sauce", "marinade"], allow=["sauce"]),
    P("curry-paste", "an open plain unlabelled small glass jar of red thai curry paste with a spoon", ["curry paste", "red curry paste", "green curry paste", "laksa paste", "tikka paste", "tikka masala paste", "korma paste", "rendang paste", "massaman", "butter chicken sauce", "simmer sauce", "curry sauce"], allow=["curry", "paste", "jar", "sauce"]),
    P("miso", "a small simple bowl of miso paste with a spoon", ["miso", "miso paste", "white miso", "red miso", "doenjang"], allow=["paste"], **{"not": ["soup"]}),
    P("gravy", "a small simple jug of rich brown gravy", ["gravy", "jus", "gravy sauce"], allow=["sauce"], **{"not": ["beef", "powder", "granules"]}),
    P("salad-dressing", "a plain unlabelled small glass bottle of creamy salad dressing and a small dish", ["dressing", "salad dressing", "caesar dressing", "ranch", "french dressing", "thousand island", "vinaigrette", "italian dressing"], allow=["dressing", "salad"]),
    P("apple-sauce", "a small simple bowl of smooth apple sauce", ["apple sauce", "applesauce", "cranberry sauce", "mint sauce", "mint jelly", "horseradish", "tartare sauce", "tartar sauce", "seafood sauce", "cocktail sauce"], allow=["sauce", "jelly", "jar"]),
    P("relish", "an open plain unlabelled glass jar of tomato relish chutney with a spoon", ["relish", "chutney", "tomato relish", "mango chutney", "onion jam", "pickle relish", "piccalilli", "tomato chutney"], allow=["jar", "jam"]),
    P("capers", "a small simple bowl of capers in brine", ["caper", "caperberries"], allow=["jar", "pickled"]),
    P("pickled-jalapenos", "an open plain unlabelled glass jar of sliced pickled green jalapenos", ["pickled jalapenos", "jalapeno slices", "sliced jalapenos", "banana peppers", "pepperoncini", "pickled chillies"], needs=["pickled", "sliced", "slices", "banana", "pepperoncini", "jar"], allow=["pickled", "jar"]),
    P("kimchi", "a simple bowl of red spicy kimchi", ["kimchi", "kimchee", "sauerkraut", "fermented cabbage"], allow=["jar"]),
    P("marinated-veg", "an open plain unlabelled glass jar of marinated artichoke hearts and roasted red capsicum strips", ["artichoke hearts", "marinated artichoke", "roasted capsicum", "roasted peppers", "roasted red peppers", "antipasto", "antipasti", "marinated", "char grilled vegetables", "chargrilled"], allow=["jar", "roasted", "oil"]),
    P("tomato-soup", "", [], skip=True),
    P("guacamole", "a simple bowl of chunky guacamole", ["guacamole", "guac", "avocado dip", "smashed avocado"], allow=["dip"]),
    P("tzatziki", "a simple bowl of creamy tzatziki with cucumber and dill", ["tzatziki", "raita", "french onion dip", "cob loaf dip", "spinach dip", "sour cream dip", "cream cheese dip", "beetroot dip", "baba ganoush", "taramasalata", "dip"], allow=["dip"]),
    # ---- more tins
    P("black-beans", "an opened plain unbranded metal tin of black beans with a spoon", ["black bean", "black beans"], allow=CANS, **{"not": ["sauce", "dried"]}),
    P("white-beans", "an opened plain unbranded metal tin of creamy cannellini beans with a spoon", ["cannellini", "cannellini beans", "butter beans", "white beans", "lima beans", "borlotti"], allow=CANS, **{"not": ["dried"]}),
    P("canned-lentils", "an opened plain unbranded metal tin of brown lentils with a spoon", ["lentil", "lentils", "brown lentils"], needs=CANS, allow=CANS),
    P("refried-beans", "an opened plain unbranded metal tin of refried beans with a spoon", ["refried beans", "refried bean", "chilli beans", "mexican beans"], allow=CANS),
    P("canned-pineapple", "an opened plain unbranded metal tin of pineapple rings in juice", ["pineapple", "pineapple pieces", "crushed pineapple", "pineapple rings"], needs=CANS + ["crushed", "rings", "pieces"], allow=CANS + ["juice"]),
    P("tinned-spaghetti", "an opened plain unbranded metal tin of spaghetti in tomato sauce", ["spaghetti", "tinned spaghetti", "canned spaghetti", "spaghetti hoops", "ravioli tin", "alphabet pasta"], needs=CANS + ["hoops"], allow=CANS + ["sauce"]),
    P("canned-soup-cream", "an opened plain unbranded metal tin beside a simple bowl of creamy mushroom soup", ["cream of mushroom", "cream of chicken", "chicken soup", "mushroom soup", "chowder", "minestrone", "vegetable soup", "lentil soup", "pea soup", "broth"], allow=CANS + ["soup"]),
    P("canned-chilli", "an opened plain unbranded metal tin of chilli con carne", ["chilli con carne", "chili con carne", "irish stew", "stew", "braised steak", "corned beef hash", "spam", "luncheon"], allow=CANS + ["stew"]),
    # ---- more frozen
    P("frozen-spinach", "frozen spinach portions with a light frost in a simple bowl", ["spinach", "kale"], needs=["frozen"], allow=["frozen"]),
    P("frozen-corn", "frozen golden corn kernels with a light frost in a simple bowl", ["corn", "corn kernels", "sweetcorn", "sweet corn"], needs=["frozen"], allow=["frozen"]),
    P("frozen-broccoli", "frozen broccoli florets with a light frost in a simple bowl", ["broccoli", "cauliflower", "brussels sprouts", "green beans", "beans", "cauliflower rice"], needs=["frozen"], allow=["frozen"]),
    P("edamame", "bright green edamame pods in a simple bowl with a sprinkle of salt", ["edamame", "soy beans", "soybeans"], allow=["frozen", "salted"]),
    P("frozen-mango", "frozen mango cubes with a light frost in a simple bowl", ["mango", "pineapple", "banana", "fruit", "tropical fruit", "smoothie mix", "acai"], needs=["frozen"], allow=["frozen"]),
    P("frozen-prawns", "frozen raw prawns with a light frost in a simple bowl", ["prawn", "shrimp", "seafood mix", "marinara mix"], needs=["frozen"], allow=["frozen"]),
    P("frozen-fish", "frozen fish fillets with a light frost on a simple tray", ["fish", "fish fillet", "salmon", "basa", "hoki", "hake", "cod"], needs=["frozen"], allow=["frozen"], **{"not": ["fingers", "finger", "cake", "cakes", "crumbed", "battered"]}),
    P("frozen-pizza", "a whole frozen margherita pizza with a light frost on a simple tray", ["pizza", "frozen pizza", "pizza pocket"], allow=["frozen"], **{"not": ["base", "bases", "dough", "sauce", "cheese"]}),
    P("hash-browns", "golden hash browns and potato gems on a simple tray", ["hash brown", "hash browns", "potato gems", "tater tots", "potato cakes", "croquettes", "rosti"], allow=["frozen", "cake"]),
    P("ice-blocks", "colourful fruit ice blocks popsicles on a simple plate with a light frost", ["ice block", "ice blocks", "icy pole", "ice pole", "popsicle", "ice lolly", "paddle pop", "choc top", "ice cream cone", "magnum", "drumstick ice cream"], allow=["frozen"]),
    P("spring-rolls", "golden spring rolls and samosas on a simple plate", ["spring roll", "spring rolls", "samosa", "samosas", "curry puff", "curry puffs", "money bags", "wontons"], allow=["frozen", "fried", "curry"]),
    P("frozen-garlic-bread", "a sliced garlic bread baguette with herb butter on a simple tray", ["garlic bread", "herb bread", "cheesy bread", "garlic naan"], allow=["frozen", "baked"]),
    P("falafel", "golden falafel balls in a simple bowl", ["falafel", "veggie burger", "vegie burger", "plant based burger", "beyond burger", "vegetarian sausages", "veggie sausages", "plant based mince", "vegan mince", "tempeh", "seitan"], allow=["frozen"]),
    # ---- more drinks
    P("apple-juice", "a plain unlabelled glass bottle of clear golden apple juice and a glass", ["apple juice", "pear juice", "grape juice", "cranberry juice", "pineapple juice", "tomato juice", "vegetable juice", "fruit juice", "juice box", "juice boxes"], allow=["juice"]),
    P("soft-drink", "a plain unbranded red aluminium can and a glass of cola with ice", ["soft drink", "soft drinks", "cola", "coke", "pepsi", "lemonade", "soda", "fizzy drink", "ginger ale", "ginger beer", "tonic", "tonic water", "sprite", "fanta", "solo"], **{"not": ["water"]}),
    P("iced-tea", "a plain unlabelled glass bottle of iced tea and a glass with ice", ["iced tea", "ice tea", "kombucha", "sparkling juice", "cold brew"]),
    P("coconut-water", "a halved green coconut and a glass of coconut water", ["coconut water"]),
    P("sports-drink", "a plain unlabelled plastic bottle of blue sports drink", ["sports drink", "gatorade", "powerade", "electrolyte", "energy drink", "red bull", "vitamin water"]),
    P("cordial", "a plain unlabelled glass bottle of red cordial syrup and a glass jug of diluted drink", ["cordial", "squash drink", "syrup drink", "ribena", "fruit syrup"]),
    P("red-wine", "a plain unlabelled bottle of red wine and a glass of red wine", ["red wine", "shiraz", "merlot", "cabernet", "pinot noir", "wine", "cooking wine", "port"], **{"not": ["vinegar", "white", "sparkling"]}),
    P("white-wine", "a plain unlabelled bottle of white wine and a glass of white wine", ["white wine", "chardonnay", "sauvignon blanc", "pinot gris", "riesling", "rose", "rosé", "sparkling wine", "prosecco", "champagne"], **{"not": ["vinegar"]}),
    P("beer", "a plain unlabelled brown glass beer bottle and a glass of golden beer", ["beer", "lager", "ale", "cider", "stout", "pale ale", "ipa"], **{"not": ["ginger", "nuts", "root", "vinegar"]}),
    P("spirits", "a plain unlabelled glass bottle of clear spirit and a small glass", ["vodka", "gin", "rum", "whisky", "whiskey", "brandy", "tequila", "liqueur", "spirits", "baileys"]),
    P("smoothie", "a plain unlabelled bottle of pink berry smoothie and a full glass", ["smoothie", "milkshake", "thickshake", "acai bowl", "breakfast drink"]),
    # ---- prepared, deli and ready to eat
    P("sushi", "a simple plate of salmon and avocado sushi rolls", ["sushi", "sushi roll", "hand roll", "nori roll", "onigiri", "poke bowl"]),
    P("coleslaw", "a simple bowl of creamy coleslaw", ["coleslaw", "slaw", "potato salad", "pasta salad", "egg salad", "rice salad", "tabouli", "tabbouleh", "salad kit", "caesar salad", "greek salad", "garden salad", "prepared salad"], allow=["salad", "dressing", "mayo"]),
    P("lasagne", "a baked beef lasagne with a portion cut, in a simple dish", ["lasagne", "lasagna", "moussaka", "pasta bake", "cannelloni bake", "mac and cheese", "macaroni cheese", "shepherds pie", "cottage pie"], allow=["baked", "bake", "frozen", "leftover", "leftovers", "pie", "cooked"], **{"not": ["sheets", "sheet"]}),
    P("curry-meal", "a simple bowl of chicken curry with rice", ["curry", "butter chicken", "tikka masala", "korma", "vindaloo", "rogan josh", "dal", "dhal", "laksa", "green curry", "red curry", "massaman curry"], allow=["curry", "leftover", "leftovers", "cooked", "frozen", "soup"], **{"not": ["paste", "powder", "leaves", "leaf", "puff", "puffs", "sauce"]}),
    P("stir-fry", "a simple bowl of cooked chicken and vegetable noodle stir fry", ["stir fry", "stirfry", "pad thai", "chow mein", "noodle stir fry", "fried noodles", "lo mein", "nasi goreng", "bibimbap"], allow=["noodles", "fried", "leftover", "leftovers", "cooked"], **{"not": ["mix", "veg", "vegetables", "sauce", "beef strips", "strips"]}),
    P("pasta-dish", "a simple bowl of spaghetti bolognese", ["bolognese", "spaghetti bolognese", "spag bol", "carbonara", "cooked pasta", "pasta leftovers", "pasta meal", "mince sauce", "ragu"], allow=["cooked", "leftover", "leftovers", "sauce"], **{"not": ["jar", "sheets"]}),
    P("soup-bowl", "a simple bowl of hearty homemade vegetable soup", ["homemade soup", "soup", "fresh soup", "pumpkin soup", "pea and ham soup", "chicken noodle soup", "ramen", "pho", "miso soup"], allow=["soup", "leftover", "leftovers", "cooked", "noodles"], **{"not": CANS + ["packet", "instant", "cup"]}),
    P("sandwich", "a simple plate with a fresh ham, cheese and salad sandwich cut in half", ["sandwich", "sandwiches", "sub", "baguette sandwich", "toastie", "wrap sandwich", "burrito", "roll filled", "salad roll", "bagel sandwich"], allow=["salad"]),
    P("dumplings-cooked", "", [], skip=True),
    P("baby-food", "a small plain unlabelled glass jar of orange vegetable baby food puree with a baby spoon", ["baby food", "baby puree", "puree pouch", "baby pouch", "baby cereal", "rusks", "teething rusks", "baby snacks", "kids pouch", "fruit pouch"], allow=["puree", "jar"]),
    P("cheese-platter", "a small cheese board with brie, cheddar, crackers, grapes and dried fruit", ["cheese platter", "cheese board", "grazing platter", "platter", "charcuterie"]),
    P("tofu-puffs", "golden fried tofu puffs in a simple bowl", ["tofu puffs", "fried tofu", "silken tofu", "marinated tofu", "smoked tofu"], allow=["fried", "smoked"]),
    # ---- snacks
    P("corn-chips", "a simple bowl of triangular corn tortilla chips", ["corn chips", "tortilla chips", "nachos", "doritos", "corn chip"], allow=["chips", "salted"]),
    P("rice-crackers", "a simple bowl of small japanese rice crackers", ["rice crackers", "rice cracker", "seaweed snack", "seaweed snacks", "nori snacks", "puffed rice", "corn thins", "rice thins", "vege chips", "veggie straws"], allow=["chips", "salted", "crisps"]),
    P("chocolate-bar", "a few plain unwrapped milk chocolate bars and chocolate pieces on a plate", ["chocolate bar", "chocolate bars", "choc bar", "kit kat", "kitkat", "mars bar", "snickers", "freddo", "chocolates", "easter egg", "easter eggs", "truffles", "pralines"], allow=["milk"]),
    P("cookies", "a small stack of chocolate chip cookies on a simple plate", ["cookie", "choc chip cookie", "chocolate chip cookie", "tim tam", "tim tams", "oreo", "anzac biscuits", "anzac", "cream biscuits", "shortbread"], allow=["chips"], **{"not": ["butter", "dough", "mix", "spread"]}),
    P("dried-seaweed", "sheets of dried nori seaweed on a board", ["nori", "seaweed", "kombu", "wakame", "dried seaweed", "nori sheets"], allow=["dried"], **{"not": ["snack", "snacks", "salad", "rolls", "roll"]}),
    P("pet-free", "", [], skip=True),
]
C2 = [c for c in C2 if not c[4].pop("skip", False)]
