// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class AppState {
  static const expiryAlertDays = ffai.ProjectAppStateFieldHandle(
    name: "expiryAlertDays",
    key: "expiryAlertDays",
    typeName: "Integer",
    persisted: false,
  );
  static const hasOpenedFridge = ffai.ProjectAppStateFieldHandle(
    name: "hasOpenedFridge",
    key: "er0xvbcu",
    typeName: "Boolean",
    persisted: true,
  );
  static const isMetric = ffai.ProjectAppStateFieldHandle(
    name: "isMetric",
    key: "isMetric",
    typeName: "Boolean",
    persisted: false,
  );
  static const searchQuery = ffai.ProjectAppStateFieldHandle(
    name: "searchQuery",
    key: "searchQuery",
    typeName: "String",
    persisted: false,
  );
  static const selectedCategory = ffai.ProjectAppStateFieldHandle(
    name: "selectedCategory",
    key: "selectedCategory",
    typeName: "String",
    persisted: false,
  );
  static const all = <ffai.ProjectAppStateFieldHandle>[
    expiryAlertDays,
    hasOpenedFridge,
    isMetric,
    searchQuery,
    selectedCategory,
  ];
}

