// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class AppState {
  static const aiCategory = ffai.ProjectAppStateFieldHandle(
    name: "aiCategory",
    key: "m3j1zfs7",
    typeName: "String",
    persisted: false,
  );
  static const aiName = ffai.ProjectAppStateFieldHandle(
    name: "aiName",
    key: "rsto5gmi",
    typeName: "String",
    persisted: false,
  );
  static const currentHouseholdId = ffai.ProjectAppStateFieldHandle(
    name: "currentHouseholdId",
    key: "pw82uhh2",
    typeName: "String",
    persisted: true,
  );
  static const editCategory = ffai.ProjectAppStateFieldHandle(
    name: "editCategory",
    key: "y8jdta11",
    typeName: "String",
    persisted: false,
  );
  static const editDateType = ffai.ProjectAppStateFieldHandle(
    name: "editDateType",
    key: "1ma0ziop",
    typeName: "String",
    persisted: false,
  );
  static const editItemId = ffai.ProjectAppStateFieldHandle(
    name: "editItemId",
    key: "1gxrwr9o",
    typeName: "String",
    persisted: false,
  );
  static const editLocationId = ffai.ProjectAppStateFieldHandle(
    name: "editLocationId",
    key: "xx3vcxjq",
    typeName: "String",
    persisted: false,
  );
  static const editName = ffai.ProjectAppStateFieldHandle(
    name: "editName",
    key: "1am4nn22",
    typeName: "String",
    persisted: false,
  );
  static const editPrintedDate = ffai.ProjectAppStateFieldHandle(
    name: "editPrintedDate",
    key: "dwi3shp3",
    typeName: "String",
    persisted: false,
  );
  static const editQuantity = ffai.ProjectAppStateFieldHandle(
    name: "editQuantity",
    key: "o55qfbfi",
    typeName: "Integer",
    persisted: false,
  );
  static const expiryAlertDays = ffai.ProjectAppStateFieldHandle(
    name: "expiryAlertDays",
    key: "expiryAlertDays",
    typeName: "Integer",
    persisted: false,
  );
  static const hasOpenedFridge = ffai.ProjectAppStateFieldHandle(
    name: "hasOpenedFridge",
    key: "er0xvbcu",
    typeName: "Boolean",
    persisted: true,
  );
  static const ideasAvoid = ffai.ProjectAppStateFieldHandle(
    name: "ideasAvoid",
    key: "mec5y09z",
    typeName: "String",
    persisted: true,
  );
  static const ideasKitchenOnly = ffai.ProjectAppStateFieldHandle(
    name: "ideasKitchenOnly",
    key: "3tjj53er",
    typeName: "Boolean",
    persisted: true,
  );
  static const ideasLeaveOut = ffai.ProjectAppStateFieldHandle(
    name: "ideasLeaveOut",
    key: "96n8z4ty",
    typeName: "String",
    persisted: true,
  );
  static const ideasLoading = ffai.ProjectAppStateFieldHandle(
    name: "ideasLoading",
    key: "mly1u32k",
    typeName: "Boolean",
    persisted: false,
  );
  static const ideasMeal = ffai.ProjectAppStateFieldHandle(
    name: "ideasMeal",
    key: "7osxz9ok",
    typeName: "String",
    persisted: true,
  );
  static const ideasMinutes = ffai.ProjectAppStateFieldHandle(
    name: "ideasMinutes",
    key: "lc0s1vrl",
    typeName: "Integer",
    persisted: true,
  );
  static const ideasServings = ffai.ProjectAppStateFieldHandle(
    name: "ideasServings",
    key: "s1ab0afq",
    typeName: "Integer",
    persisted: true,
  );
  static const isMetric = ffai.ProjectAppStateFieldHandle(
    name: "isMetric",
    key: "isMetric",
    typeName: "Boolean",
    persisted: false,
  );
  static const keptIdeas = ffai.ProjectAppStateFieldHandle(
    name: "keptIdeas",
    key: "ls7wkxx9",
    typeName: "List<DataStruct<MealIdea>>",
    persisted: true,
  );
  static const mapFoods = ffai.ProjectAppStateFieldHandle(
    name: "mapFoods",
    key: "i3b2e5x2",
    typeName: "List<DataStruct<MapFood>>",
    persisted: false,
  );
  static const mapPhotos = ffai.ProjectAppStateFieldHandle(
    name: "mapPhotos",
    key: "8z3gtg21",
    typeName: "List<String>",
    persisted: false,
  );
  static const mapPlace = ffai.ProjectAppStateFieldHandle(
    name: "mapPlace",
    key: "ewr5wc0w",
    typeName: "String",
    persisted: false,
  );
  static const mapReading = ffai.ProjectAppStateFieldHandle(
    name: "mapReading",
    key: "ab13g4cd",
    typeName: "Boolean",
    persisted: false,
  );
  static const mealIdeas = ffai.ProjectAppStateFieldHandle(
    name: "mealIdeas",
    key: "7flyrry1",
    typeName: "List<DataStruct<MealIdea>>",
    persisted: false,
  );
  static const scanBarcode = ffai.ProjectAppStateFieldHandle(
    name: "scanBarcode",
    key: "pne0944b",
    typeName: "String",
    persisted: false,
  );
  static const scanBrand = ffai.ProjectAppStateFieldHandle(
    name: "scanBrand",
    key: "4y1iv0y6",
    typeName: "String",
    persisted: false,
  );
  static const scanCategory = ffai.ProjectAppStateFieldHandle(
    name: "scanCategory",
    key: "396caw0t",
    typeName: "String",
    persisted: false,
  );
  static const scanImageUrl = ffai.ProjectAppStateFieldHandle(
    name: "scanImageUrl",
    key: "g7sxj2x3",
    typeName: "String",
    persisted: false,
  );
  static const scanName = ffai.ProjectAppStateFieldHandle(
    name: "scanName",
    key: "tve6kjbt",
    typeName: "String",
    persisted: false,
  );
  static const scanQuantity = ffai.ProjectAppStateFieldHandle(
    name: "scanQuantity",
    key: "w1mv4c3p",
    typeName: "String",
    persisted: false,
  );
  static const scanReading = ffai.ProjectAppStateFieldHandle(
    name: "scanReading",
    key: "hwqb0kc8",
    typeName: "Boolean",
    persisted: false,
  );
  static const scannedFoods = ffai.ProjectAppStateFieldHandle(
    name: "scannedFoods",
    key: "uixotph4",
    typeName: "List<DataStruct<ScannedFood>>",
    persisted: false,
  );
  static const scannedFrom = ffai.ProjectAppStateFieldHandle(
    name: "scannedFrom",
    key: "meba38tt",
    typeName: "String",
    persisted: false,
  );
  static const searchQuery = ffai.ProjectAppStateFieldHandle(
    name: "searchQuery",
    key: "searchQuery",
    typeName: "String",
    persisted: false,
  );
  static const selectedCategory = ffai.ProjectAppStateFieldHandle(
    name: "selectedCategory",
    key: "selectedCategory",
    typeName: "String",
    persisted: false,
  );
  static const wasteBinnedCount = ffai.ProjectAppStateFieldHandle(
    name: "wasteBinnedCount",
    key: "q1zte4rv",
    typeName: "Integer",
    persisted: false,
  );
  static const wasteDetail = ffai.ProjectAppStateFieldHandle(
    name: "wasteDetail",
    key: "ofrklz0j",
    typeName: "String",
    persisted: false,
  );
  static const wasteHasData = ffai.ProjectAppStateFieldHandle(
    name: "wasteHasData",
    key: "kzg1sg7v",
    typeName: "Boolean",
    persisted: false,
  );
  static const wasteHeadline = ffai.ProjectAppStateFieldHandle(
    name: "wasteHeadline",
    key: "p72vr258",
    typeName: "String",
    persisted: false,
  );
  static const wasteLoaded = ffai.ProjectAppStateFieldHandle(
    name: "wasteLoaded",
    key: "2qz4wz5x",
    typeName: "Boolean",
    persisted: false,
  );
  static const wasteTrend = ffai.ProjectAppStateFieldHandle(
    name: "wasteTrend",
    key: "b40jlw8q",
    typeName: "String",
    persisted: false,
  );
  static const wasteUsedCount = ffai.ProjectAppStateFieldHandle(
    name: "wasteUsedCount",
    key: "d2j2sf2p",
    typeName: "Integer",
    persisted: false,
  );
  static const wasteWorst = ffai.ProjectAppStateFieldHandle(
    name: "wasteWorst",
    key: "7nj80m9i",
    typeName: "String",
    persisted: false,
  );
  static const all = <ffai.ProjectAppStateFieldHandle>[
    aiCategory,
    aiName,
    currentHouseholdId,
    editCategory,
    editDateType,
    editItemId,
    editLocationId,
    editName,
    editPrintedDate,
    editQuantity,
    expiryAlertDays,
    hasOpenedFridge,
    ideasAvoid,
    ideasKitchenOnly,
    ideasLeaveOut,
    ideasLoading,
    ideasMeal,
    ideasMinutes,
    ideasServings,
    isMetric,
    keptIdeas,
    mapFoods,
    mapPhotos,
    mapPlace,
    mapReading,
    mealIdeas,
    scanBarcode,
    scanBrand,
    scanCategory,
    scanImageUrl,
    scanName,
    scanQuantity,
    scanReading,
    scannedFoods,
    scannedFrom,
    searchQuery,
    selectedCategory,
    wasteBinnedCount,
    wasteDetail,
    wasteHasData,
    wasteHeadline,
    wasteLoaded,
    wasteTrend,
    wasteUsedCount,
    wasteWorst,
  ];
}

