// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'components/empty_state_card.dart' show EmptyStateCardComponentHandle;
import 'components/feature_panel.dart' show FeaturePanelComponentHandle;
import 'components/food_card.dart' show FoodCardComponentHandle;
import 'components/section_heading.dart' show SectionHeadingComponentHandle;
import 'components/status_badge.dart' show StatusBadgeComponentHandle;

abstract final class Components {
  static final emptyStateCard = EmptyStateCardComponentHandle();
  static final featurePanel = FeaturePanelComponentHandle();
  static final foodCard = FoodCardComponentHandle();
  static final sectionHeading = SectionHeadingComponentHandle();
  static final statusBadge = StatusBadgeComponentHandle();
  static final all = <ffai.ProjectComponentHandle>[
    emptyStateCard,
    featurePanel,
    foodCard,
    sectionHeading,
    statusBadge,
  ];
}
