// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'components/bottom_navigation.dart' show BottomNavigationComponentHandle;

abstract final class Components {
  static final bottomNavigation = BottomNavigationComponentHandle();
  static final all = <ffai.ProjectComponentHandle>[
    bottomNavigation,
  ];
}
