// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'pages/add_food_item_page.dart' show addFoodItemPageHandle;
import 'pages/home_page.dart' show homePageHandle;
import 'pages/household_setup_page.dart' show householdSetupPageHandle;
import 'pages/inventory_page.dart' show inventoryPageHandle;
import 'pages/onboarding_page.dart' show onboardingPageHandle;
import 'pages/profile_page.dart' show profilePageHandle;
import 'pages/recipes_page.dart' show recipesPageHandle;
import 'pages/reset_password_page.dart' show resetPasswordPageHandle;
import 'pages/scan_add_page.dart' show scanAddPageHandle;
import 'pages/sign_in_page.dart' show signInPageHandle;
import 'pages/sign_up_page.dart' show signUpPageHandle;
import 'pages/storage_locations_page.dart' show storageLocationsPageHandle;
import 'pages/update_password_page.dart' show updatePasswordPageHandle;
import 'pages/welcome_page.dart' show welcomePageHandle;

abstract final class Pages {
  static final addFoodItemPage = addFoodItemPageHandle;
  static final homePage = homePageHandle;
  static final householdSetupPage = householdSetupPageHandle;
  static final inventoryPage = inventoryPageHandle;
  static final onboardingPage = onboardingPageHandle;
  static final profilePage = profilePageHandle;
  static final recipesPage = recipesPageHandle;
  static final resetPasswordPage = resetPasswordPageHandle;
  static final scanAddPage = scanAddPageHandle;
  static final signInPage = signInPageHandle;
  static final signUpPage = signUpPageHandle;
  static final storageLocationsPage = storageLocationsPageHandle;
  static final updatePasswordPage = updatePasswordPageHandle;
  static final welcomePage = welcomePageHandle;
  static final all = <ffai.ProjectPageHandle>[
    addFoodItemPage,
    homePage,
    householdSetupPage,
    inventoryPage,
    onboardingPage,
    profilePage,
    recipesPage,
    resetPasswordPage,
    scanAddPage,
    signInPage,
    signUpPage,
    storageLocationsPage,
    updatePasswordPage,
    welcomePage,
  ];
}
