// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

abstract final class Project {
  static const id = "fridge-wise-gvpy0s";
  static const name = "UseItFresh";
  static const sdkMetaVersion = 3;
}
