// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'dart:collection';

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class Enums {
  static const all = <ffai.EnumHandle>[];
}

abstract final class Structs {
  static const all = <ffai.StructHandle>[];
}

abstract final class Collections {
  static const all = <ffai.ProjectCollectionHandle>[];
}

abstract final class Tables {
  static final foodCareGuides = ffai.ProjectTableHandle<FoodCareGuidesFields>(
    name: "food_care_guides",
    description: "",
    isView: false,
    fields: FoodCareGuidesFields(),
  );
  static final foodItemEvents = ffai.ProjectTableHandle<FoodItemEventsFields>(
    name: "food_item_events",
    description: "",
    isView: false,
    fields: FoodItemEventsFields(),
  );
  static final foodItems = ffai.ProjectTableHandle<FoodItemsFields>(
    name: "food_items",
    description: "",
    isView: false,
    fields: FoodItemsFields(),
  );
  static final foodItemsStatus = ffai.ProjectTableHandle<FoodItemsStatusFields>(
    name: "food_items_status",
    description: "",
    isView: true,
    fields: FoodItemsStatusFields(),
  );
  static final freshnessAssessments = ffai.ProjectTableHandle<FreshnessAssessmentsFields>(
    name: "freshness_assessments",
    description: "",
    isView: false,
    fields: FreshnessAssessmentsFields(),
  );
  static final householdMembers = ffai.ProjectTableHandle<HouseholdMembersFields>(
    name: "household_members",
    description: "",
    isView: false,
    fields: HouseholdMembersFields(),
  );
  static final households = ffai.ProjectTableHandle<HouseholdsFields>(
    name: "households",
    description: "",
    isView: false,
    fields: HouseholdsFields(),
  );
  static final notificationPreferences = ffai.ProjectTableHandle<NotificationPreferencesFields>(
    name: "notification_preferences",
    description: "",
    isView: false,
    fields: NotificationPreferencesFields(),
  );
  static final profiles = ffai.ProjectTableHandle<ProfilesFields>(
    name: "profiles",
    description: "",
    isView: false,
    fields: ProfilesFields(),
  );
  static final savedRecipes = ffai.ProjectTableHandle<SavedRecipesFields>(
    name: "saved_recipes",
    description: "",
    isView: false,
    fields: SavedRecipesFields(),
  );
  static final scanCandidates = ffai.ProjectTableHandle<ScanCandidatesFields>(
    name: "scan_candidates",
    description: "",
    isView: false,
    fields: ScanCandidatesFields(),
  );
  static final scanSessions = ffai.ProjectTableHandle<ScanSessionsFields>(
    name: "scan_sessions",
    description: "",
    isView: false,
    fields: ScanSessionsFields(),
  );
  static final shoppingListItems = ffai.ProjectTableHandle<ShoppingListItemsFields>(
    name: "shopping_list_items",
    description: "",
    isView: false,
    fields: ShoppingListItemsFields(),
  );
  static final shoppingLists = ffai.ProjectTableHandle<ShoppingListsFields>(
    name: "shopping_lists",
    description: "",
    isView: false,
    fields: ShoppingListsFields(),
  );
  static final storageLocations = ffai.ProjectTableHandle<StorageLocationsFields>(
    name: "storage_locations",
    description: "",
    isView: false,
    fields: StorageLocationsFields(),
  );
  static final all = <ffai.ProjectTableHandle>[
    foodCareGuides,
    foodItemEvents,
    foodItems,
    foodItemsStatus,
    freshnessAssessments,
    householdMembers,
    households,
    notificationPreferences,
    profiles,
    savedRecipes,
    scanCandidates,
    scanSessions,
    shoppingListItems,
    shoppingLists,
    storageLocations,
  ];
}

final class FoodCareGuidesFields extends MapBase<String, ffai.PostgresTableField> {
  final category = ffai.ProjectTableFieldHandle(
    name: "category",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final defaultShelfDays = ffai.ProjectTableFieldHandle(
    name: "default_shelf_days",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int4",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final displayName = ffai.ProjectTableFieldHandle(
    name: "display_name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  final isHighRisk = ffai.ProjectTableFieldHandle(
    name: "is_high_risk",
    key: "",
    typeName: "Boolean",
    type: ffai.bool_,
    description: "",
    postgresType: "bool",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final openedDays = ffai.ProjectTableFieldHandle(
    name: "opened_days",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int4",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final openedShelfLife = ffai.ProjectTableFieldHandle(
    name: "opened_shelf_life",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final safetyNotes = ffai.ProjectTableFieldHandle(
    name: "safety_notes",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final storageTips = ffai.ProjectTableFieldHandle(
    name: "storage_tips",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final typicalShelfLife = ffai.ProjectTableFieldHandle(
    name: "typical_shelf_life",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final updatedAt = ffai.ProjectTableFieldHandle(
    name: "updated_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final useSoonDays = ffai.ProjectTableFieldHandle(
    name: "use_soon_days",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int4",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "category",
    "created_at",
    "default_shelf_days",
    "display_name",
    "id",
    "is_high_risk",
    "opened_days",
    "opened_shelf_life",
    "safety_notes",
    "storage_tips",
    "typical_shelf_life",
    "updated_at",
    "use_soon_days",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "category" => category,
    "created_at" => createdAt,
    "default_shelf_days" => defaultShelfDays,
    "display_name" => displayName,
    "id" => id,
    "is_high_risk" => isHighRisk,
    "opened_days" => openedDays,
    "opened_shelf_life" => openedShelfLife,
    "safety_notes" => safetyNotes,
    "storage_tips" => storageTips,
    "typical_shelf_life" => typicalShelfLife,
    "updated_at" => updatedAt,
    "use_soon_days" => useSoonDays,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class FoodItemEventsFields extends MapBase<String, ffai.PostgresTableField> {
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final eventType = ffai.ProjectTableFieldHandle(
    name: "event_type",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final foodItemId = ffai.ProjectTableFieldHandle(
    name: "food_item_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "food_items.id",
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final fromValue = ffai.ProjectTableFieldHandle(
    name: "from_value",
    key: "",
    typeName: "JSON",
    type: ffai.json,
    description: "",
    postgresType: "jsonb",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  final profileId = ffai.ProjectTableFieldHandle(
    name: "profile_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "profiles.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final toValue = ffai.ProjectTableFieldHandle(
    name: "to_value",
    key: "",
    typeName: "JSON",
    type: ffai.json,
    description: "",
    postgresType: "jsonb",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "created_at",
    "event_type",
    "food_item_id",
    "from_value",
    "id",
    "profile_id",
    "to_value",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "created_at" => createdAt,
    "event_type" => eventType,
    "food_item_id" => foodItemId,
    "from_value" => fromValue,
    "id" => id,
    "profile_id" => profileId,
    "to_value" => toValue,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class FoodItemsFields extends MapBase<String, ffai.PostgresTableField> {
  final archivedAt = ffai.ProjectTableFieldHandle(
    name: "archived_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final barcode = ffai.ProjectTableFieldHandle(
    name: "barcode",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final brand = ffai.ProjectTableFieldHandle(
    name: "brand",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final category = ffai.ProjectTableFieldHandle(
    name: "category",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final confidence = ffai.ProjectTableFieldHandle(
    name: "confidence",
    key: "",
    typeName: "Double",
    type: ffai.double_,
    description: "",
    postgresType: "numeric",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final cookedAt = ffai.ProjectTableFieldHandle(
    name: "cooked_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final createdBy = ffai.ProjectTableFieldHandle(
    name: "created_by",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "profiles.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final estimatedExpiryAt = ffai.ProjectTableFieldHandle(
    name: "estimated_expiry_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final expirySource = ffai.ProjectTableFieldHandle(
    name: "expiry_source",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final frozenAt = ffai.ProjectTableFieldHandle(
    name: "frozen_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final householdId = ffai.ProjectTableFieldHandle(
    name: "household_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "households.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  final imageUrl = ffai.ProjectTableFieldHandle(
    name: "image_url",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final name = ffai.ProjectTableFieldHandle(
    name: "name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final notes = ffai.ProjectTableFieldHandle(
    name: "notes",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final openedAt = ffai.ProjectTableFieldHandle(
    name: "opened_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final printedDate = ffai.ProjectTableFieldHandle(
    name: "printed_date",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "date",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final printedDateType = ffai.ProjectTableFieldHandle(
    name: "printed_date_type",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final purchaseDate = ffai.ProjectTableFieldHandle(
    name: "purchase_date",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "date",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final quantity = ffai.ProjectTableFieldHandle(
    name: "quantity",
    key: "",
    typeName: "Double",
    type: ffai.double_,
    description: "",
    postgresType: "numeric",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final sourceType = ffai.ProjectTableFieldHandle(
    name: "source_type",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final status = ffai.ProjectTableFieldHandle(
    name: "status",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final storageLocationId = ffai.ProjectTableFieldHandle(
    name: "storage_location_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "storage_locations.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final unit = ffai.ProjectTableFieldHandle(
    name: "unit",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final updatedAt = ffai.ProjectTableFieldHandle(
    name: "updated_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );

  @override
  Iterable<String> get keys => const <String>[
    "archived_at",
    "barcode",
    "brand",
    "category",
    "confidence",
    "cooked_at",
    "created_at",
    "created_by",
    "estimated_expiry_at",
    "expiry_source",
    "frozen_at",
    "household_id",
    "id",
    "image_url",
    "name",
    "notes",
    "opened_at",
    "printed_date",
    "printed_date_type",
    "purchase_date",
    "quantity",
    "source_type",
    "status",
    "storage_location_id",
    "unit",
    "updated_at",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "archived_at" => archivedAt,
    "barcode" => barcode,
    "brand" => brand,
    "category" => category,
    "confidence" => confidence,
    "cooked_at" => cookedAt,
    "created_at" => createdAt,
    "created_by" => createdBy,
    "estimated_expiry_at" => estimatedExpiryAt,
    "expiry_source" => expirySource,
    "frozen_at" => frozenAt,
    "household_id" => householdId,
    "id" => id,
    "image_url" => imageUrl,
    "name" => name,
    "notes" => notes,
    "opened_at" => openedAt,
    "printed_date" => printedDate,
    "printed_date_type" => printedDateType,
    "purchase_date" => purchaseDate,
    "quantity" => quantity,
    "source_type" => sourceType,
    "status" => status,
    "storage_location_id" => storageLocationId,
    "unit" => unit,
    "updated_at" => updatedAt,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class FoodItemsStatusFields extends MapBase<String, ffai.PostgresTableField> {
  final archivedAt = ffai.ProjectTableFieldHandle(
    name: "archived_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final barcode = ffai.ProjectTableFieldHandle(
    name: "barcode",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final brand = ffai.ProjectTableFieldHandle(
    name: "brand",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final category = ffai.ProjectTableFieldHandle(
    name: "category",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final categoryDisplayName = ffai.ProjectTableFieldHandle(
    name: "category_display_name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final computedStatus = ffai.ProjectTableFieldHandle(
    name: "computed_status",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final confidence = ffai.ProjectTableFieldHandle(
    name: "confidence",
    key: "",
    typeName: "Double",
    type: ffai.double_,
    description: "",
    postgresType: "numeric",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final cookedAt = ffai.ProjectTableFieldHandle(
    name: "cooked_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final createdBy = ffai.ProjectTableFieldHandle(
    name: "created_by",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final daysLeft = ffai.ProjectTableFieldHandle(
    name: "days_left",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int4",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final estimatedExpiryAt = ffai.ProjectTableFieldHandle(
    name: "estimated_expiry_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final expirySource = ffai.ProjectTableFieldHandle(
    name: "expiry_source",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final frozenAt = ffai.ProjectTableFieldHandle(
    name: "frozen_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final hasUnknowns = ffai.ProjectTableFieldHandle(
    name: "has_unknowns",
    key: "",
    typeName: "Boolean",
    type: ffai.bool_,
    description: "",
    postgresType: "bool",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final householdId = ffai.ProjectTableFieldHandle(
    name: "household_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final imageUrl = ffai.ProjectTableFieldHandle(
    name: "image_url",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final isHighRisk = ffai.ProjectTableFieldHandle(
    name: "is_high_risk",
    key: "",
    typeName: "Boolean",
    type: ffai.bool_,
    description: "",
    postgresType: "bool",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final locationName = ffai.ProjectTableFieldHandle(
    name: "location_name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final locationType = ffai.ProjectTableFieldHandle(
    name: "location_type",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final name = ffai.ProjectTableFieldHandle(
    name: "name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final notes = ffai.ProjectTableFieldHandle(
    name: "notes",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final openedAt = ffai.ProjectTableFieldHandle(
    name: "opened_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final printedDate = ffai.ProjectTableFieldHandle(
    name: "printed_date",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "date",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final printedDateType = ffai.ProjectTableFieldHandle(
    name: "printed_date_type",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final purchaseDate = ffai.ProjectTableFieldHandle(
    name: "purchase_date",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "date",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final quantity = ffai.ProjectTableFieldHandle(
    name: "quantity",
    key: "",
    typeName: "Double",
    type: ffai.double_,
    description: "",
    postgresType: "numeric",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final safetyNotes = ffai.ProjectTableFieldHandle(
    name: "safety_notes",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final sourceType = ffai.ProjectTableFieldHandle(
    name: "source_type",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final status = ffai.ProjectTableFieldHandle(
    name: "status",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final statusBasis = ffai.ProjectTableFieldHandle(
    name: "status_basis",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final statusDetail = ffai.ProjectTableFieldHandle(
    name: "status_detail",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final statusIcon = ffai.ProjectTableFieldHandle(
    name: "status_icon",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final statusLabel = ffai.ProjectTableFieldHandle(
    name: "status_label",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final storageLocationId = ffai.ProjectTableFieldHandle(
    name: "storage_location_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final storageTips = ffai.ProjectTableFieldHandle(
    name: "storage_tips",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final unit = ffai.ProjectTableFieldHandle(
    name: "unit",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final updatedAt = ffai.ProjectTableFieldHandle(
    name: "updated_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final urgencyRank = ffai.ProjectTableFieldHandle(
    name: "urgency_rank",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int2",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "archived_at",
    "barcode",
    "brand",
    "category",
    "category_display_name",
    "computed_status",
    "confidence",
    "cooked_at",
    "created_at",
    "created_by",
    "days_left",
    "estimated_expiry_at",
    "expiry_source",
    "frozen_at",
    "has_unknowns",
    "household_id",
    "id",
    "image_url",
    "is_high_risk",
    "location_name",
    "location_type",
    "name",
    "notes",
    "opened_at",
    "printed_date",
    "printed_date_type",
    "purchase_date",
    "quantity",
    "safety_notes",
    "source_type",
    "status",
    "status_basis",
    "status_detail",
    "status_icon",
    "status_label",
    "storage_location_id",
    "storage_tips",
    "unit",
    "updated_at",
    "urgency_rank",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "archived_at" => archivedAt,
    "barcode" => barcode,
    "brand" => brand,
    "category" => category,
    "category_display_name" => categoryDisplayName,
    "computed_status" => computedStatus,
    "confidence" => confidence,
    "cooked_at" => cookedAt,
    "created_at" => createdAt,
    "created_by" => createdBy,
    "days_left" => daysLeft,
    "estimated_expiry_at" => estimatedExpiryAt,
    "expiry_source" => expirySource,
    "frozen_at" => frozenAt,
    "has_unknowns" => hasUnknowns,
    "household_id" => householdId,
    "id" => id,
    "image_url" => imageUrl,
    "is_high_risk" => isHighRisk,
    "location_name" => locationName,
    "location_type" => locationType,
    "name" => name,
    "notes" => notes,
    "opened_at" => openedAt,
    "printed_date" => printedDate,
    "printed_date_type" => printedDateType,
    "purchase_date" => purchaseDate,
    "quantity" => quantity,
    "safety_notes" => safetyNotes,
    "source_type" => sourceType,
    "status" => status,
    "status_basis" => statusBasis,
    "status_detail" => statusDetail,
    "status_icon" => statusIcon,
    "status_label" => statusLabel,
    "storage_location_id" => storageLocationId,
    "storage_tips" => storageTips,
    "unit" => unit,
    "updated_at" => updatedAt,
    "urgency_rank" => urgencyRank,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class FreshnessAssessmentsFields extends MapBase<String, ffai.PostgresTableField> {
  final answers = ffai.ProjectTableFieldHandle(
    name: "answers",
    key: "",
    typeName: "JSON",
    type: ffai.json,
    description: "",
    postgresType: "jsonb",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final confidence = ffai.ProjectTableFieldHandle(
    name: "confidence",
    key: "",
    typeName: "Double",
    type: ffai.double_,
    description: "",
    postgresType: "numeric",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final foodItemId = ffai.ProjectTableFieldHandle(
    name: "food_item_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "food_items.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final guidance = ffai.ProjectTableFieldHandle(
    name: "guidance",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final householdId = ffai.ProjectTableFieldHandle(
    name: "household_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "households.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  final missingInformation = ffai.ProjectTableFieldHandle(
    name: "missing_information",
    key: "",
    typeName: "JSON",
    type: ffai.json,
    description: "",
    postgresType: "jsonb",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final modelVersion = ffai.ProjectTableFieldHandle(
    name: "model_version",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final profileId = ffai.ProjectTableFieldHandle(
    name: "profile_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "profiles.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final reasoningSummary = ffai.ProjectTableFieldHandle(
    name: "reasoning_summary",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final resultCategory = ffai.ProjectTableFieldHandle(
    name: "result_category",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "answers",
    "confidence",
    "created_at",
    "food_item_id",
    "guidance",
    "household_id",
    "id",
    "missing_information",
    "model_version",
    "profile_id",
    "reasoning_summary",
    "result_category",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "answers" => answers,
    "confidence" => confidence,
    "created_at" => createdAt,
    "food_item_id" => foodItemId,
    "guidance" => guidance,
    "household_id" => householdId,
    "id" => id,
    "missing_information" => missingInformation,
    "model_version" => modelVersion,
    "profile_id" => profileId,
    "reasoning_summary" => reasoningSummary,
    "result_category" => resultCategory,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class HouseholdMembersFields extends MapBase<String, ffai.PostgresTableField> {
  final householdId = ffai.ProjectTableFieldHandle(
    name: "household_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "households.id",
    isPrimaryKey: true,
    isRequired: true,
    hasDefault: false,
  );
  final joinedAt = ffai.ProjectTableFieldHandle(
    name: "joined_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final profileId = ffai.ProjectTableFieldHandle(
    name: "profile_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "profiles.id",
    isPrimaryKey: true,
    isRequired: true,
    hasDefault: false,
  );
  final role = ffai.ProjectTableFieldHandle(
    name: "role",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );

  @override
  Iterable<String> get keys => const <String>[
    "household_id",
    "joined_at",
    "profile_id",
    "role",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "household_id" => householdId,
    "joined_at" => joinedAt,
    "profile_id" => profileId,
    "role" => role,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class HouseholdsFields extends MapBase<String, ffai.PostgresTableField> {
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  final inviteCode = ffai.ProjectTableFieldHandle(
    name: "invite_code",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final name = ffai.ProjectTableFieldHandle(
    name: "name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final ownerId = ffai.ProjectTableFieldHandle(
    name: "owner_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "profiles.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final updatedAt = ffai.ProjectTableFieldHandle(
    name: "updated_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );

  @override
  Iterable<String> get keys => const <String>[
    "created_at",
    "id",
    "invite_code",
    "name",
    "owner_id",
    "updated_at",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "created_at" => createdAt,
    "id" => id,
    "invite_code" => inviteCode,
    "name" => name,
    "owner_id" => ownerId,
    "updated_at" => updatedAt,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class NotificationPreferencesFields extends MapBase<String, ffai.PostgresTableField> {
  final expiryDaysBefore = ffai.ProjectTableFieldHandle(
    name: "expiry_days_before",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int4",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final expiryEnabled = ffai.ProjectTableFieldHandle(
    name: "expiry_enabled",
    key: "",
    typeName: "Boolean",
    type: ffai.bool_,
    description: "",
    postgresType: "bool",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final openedItemEnabled = ffai.ProjectTableFieldHandle(
    name: "opened_item_enabled",
    key: "",
    typeName: "Boolean",
    type: ffai.bool_,
    description: "",
    postgresType: "bool",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final profileId = ffai.ProjectTableFieldHandle(
    name: "profile_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "profiles.id",
    isPrimaryKey: true,
    isRequired: true,
    hasDefault: false,
  );
  final quietHoursEnd = ffai.ProjectTableFieldHandle(
    name: "quiet_hours_end",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "time",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final quietHoursStart = ffai.ProjectTableFieldHandle(
    name: "quiet_hours_start",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "time",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final updatedAt = ffai.ProjectTableFieldHandle(
    name: "updated_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final weeklySummaryEnabled = ffai.ProjectTableFieldHandle(
    name: "weekly_summary_enabled",
    key: "",
    typeName: "Boolean",
    type: ffai.bool_,
    description: "",
    postgresType: "bool",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );

  @override
  Iterable<String> get keys => const <String>[
    "expiry_days_before",
    "expiry_enabled",
    "opened_item_enabled",
    "profile_id",
    "quiet_hours_end",
    "quiet_hours_start",
    "updated_at",
    "weekly_summary_enabled",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "expiry_days_before" => expiryDaysBefore,
    "expiry_enabled" => expiryEnabled,
    "opened_item_enabled" => openedItemEnabled,
    "profile_id" => profileId,
    "quiet_hours_end" => quietHoursEnd,
    "quiet_hours_start" => quietHoursStart,
    "updated_at" => updatedAt,
    "weekly_summary_enabled" => weeklySummaryEnabled,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class ProfilesFields extends MapBase<String, ffai.PostgresTableField> {
  final allergens = ffai.ProjectTableFieldHandle(
    name: "allergens",
    key: "",
    typeName: "JSON",
    type: ffai.json,
    description: "",
    postgresType: "jsonb",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final avatarUrl = ffai.ProjectTableFieldHandle(
    name: "avatar_url",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final countryCode = ffai.ProjectTableFieldHandle(
    name: "country_code",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final dietaryPreferences = ffai.ProjectTableFieldHandle(
    name: "dietary_preferences",
    key: "",
    typeName: "JSON",
    type: ffai.json,
    description: "",
    postgresType: "jsonb",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final displayName = ffai.ProjectTableFieldHandle(
    name: "display_name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "users.id",
    isPrimaryKey: true,
    isRequired: true,
    hasDefault: false,
  );
  final locale = ffai.ProjectTableFieldHandle(
    name: "locale",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final unitSystem = ffai.ProjectTableFieldHandle(
    name: "unit_system",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final updatedAt = ffai.ProjectTableFieldHandle(
    name: "updated_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );

  @override
  Iterable<String> get keys => const <String>[
    "allergens",
    "avatar_url",
    "country_code",
    "created_at",
    "dietary_preferences",
    "display_name",
    "id",
    "locale",
    "unit_system",
    "updated_at",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "allergens" => allergens,
    "avatar_url" => avatarUrl,
    "country_code" => countryCode,
    "created_at" => createdAt,
    "dietary_preferences" => dietaryPreferences,
    "display_name" => displayName,
    "id" => id,
    "locale" => locale,
    "unit_system" => unitSystem,
    "updated_at" => updatedAt,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class SavedRecipesFields extends MapBase<String, ffai.PostgresTableField> {
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final householdId = ffai.ProjectTableFieldHandle(
    name: "household_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "households.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  final inventoryItemIds = ffai.ProjectTableFieldHandle(
    name: "inventory_item_ids",
    key: "",
    typeName: "JSON",
    type: ffai.json,
    description: "",
    postgresType: "jsonb",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final profileId = ffai.ProjectTableFieldHandle(
    name: "profile_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "profiles.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final recipeData = ffai.ProjectTableFieldHandle(
    name: "recipe_data",
    key: "",
    typeName: "JSON",
    type: ffai.json,
    description: "",
    postgresType: "jsonb",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final title = ffai.ProjectTableFieldHandle(
    name: "title",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "created_at",
    "household_id",
    "id",
    "inventory_item_ids",
    "profile_id",
    "recipe_data",
    "title",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "created_at" => createdAt,
    "household_id" => householdId,
    "id" => id,
    "inventory_item_ids" => inventoryItemIds,
    "profile_id" => profileId,
    "recipe_data" => recipeData,
    "title" => title,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class ScanCandidatesFields extends MapBase<String, ffai.PostgresTableField> {
  final accepted = ffai.ProjectTableFieldHandle(
    name: "accepted",
    key: "",
    typeName: "Boolean",
    type: ffai.bool_,
    description: "",
    postgresType: "bool",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final boundingBox = ffai.ProjectTableFieldHandle(
    name: "bounding_box",
    key: "",
    typeName: "JSON",
    type: ffai.json,
    description: "",
    postgresType: "jsonb",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final confidence = ffai.ProjectTableFieldHandle(
    name: "confidence",
    key: "",
    typeName: "Double",
    type: ffai.double_,
    description: "",
    postgresType: "numeric",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final createdFoodItemId = ffai.ProjectTableFieldHandle(
    name: "created_food_item_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "food_items.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  final scanSessionId = ffai.ProjectTableFieldHandle(
    name: "scan_session_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "scan_sessions.id",
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final suggestedBrand = ffai.ProjectTableFieldHandle(
    name: "suggested_brand",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final suggestedCategory = ffai.ProjectTableFieldHandle(
    name: "suggested_category",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final suggestedDateType = ffai.ProjectTableFieldHandle(
    name: "suggested_date_type",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final suggestedName = ffai.ProjectTableFieldHandle(
    name: "suggested_name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final suggestedPrintedDate = ffai.ProjectTableFieldHandle(
    name: "suggested_printed_date",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "date",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final suggestedQuantity = ffai.ProjectTableFieldHandle(
    name: "suggested_quantity",
    key: "",
    typeName: "Double",
    type: ffai.double_,
    description: "",
    postgresType: "numeric",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final suggestedStorageType = ffai.ProjectTableFieldHandle(
    name: "suggested_storage_type",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final suggestedUnit = ffai.ProjectTableFieldHandle(
    name: "suggested_unit",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "accepted",
    "bounding_box",
    "confidence",
    "created_food_item_id",
    "id",
    "scan_session_id",
    "suggested_brand",
    "suggested_category",
    "suggested_date_type",
    "suggested_name",
    "suggested_printed_date",
    "suggested_quantity",
    "suggested_storage_type",
    "suggested_unit",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "accepted" => accepted,
    "bounding_box" => boundingBox,
    "confidence" => confidence,
    "created_food_item_id" => createdFoodItemId,
    "id" => id,
    "scan_session_id" => scanSessionId,
    "suggested_brand" => suggestedBrand,
    "suggested_category" => suggestedCategory,
    "suggested_date_type" => suggestedDateType,
    "suggested_name" => suggestedName,
    "suggested_printed_date" => suggestedPrintedDate,
    "suggested_quantity" => suggestedQuantity,
    "suggested_storage_type" => suggestedStorageType,
    "suggested_unit" => suggestedUnit,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class ScanSessionsFields extends MapBase<String, ffai.PostgresTableField> {
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final householdId = ffai.ProjectTableFieldHandle(
    name: "household_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "households.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  final imageUrl = ffai.ProjectTableFieldHandle(
    name: "image_url",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final profileId = ffai.ProjectTableFieldHandle(
    name: "profile_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "profiles.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final rawAiResponse = ffai.ProjectTableFieldHandle(
    name: "raw_ai_response",
    key: "",
    typeName: "JSON",
    type: ffai.json,
    description: "",
    postgresType: "jsonb",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final scanType = ffai.ProjectTableFieldHandle(
    name: "scan_type",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final status = ffai.ProjectTableFieldHandle(
    name: "status",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );

  @override
  Iterable<String> get keys => const <String>[
    "created_at",
    "household_id",
    "id",
    "image_url",
    "profile_id",
    "raw_ai_response",
    "scan_type",
    "status",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "created_at" => createdAt,
    "household_id" => householdId,
    "id" => id,
    "image_url" => imageUrl,
    "profile_id" => profileId,
    "raw_ai_response" => rawAiResponse,
    "scan_type" => scanType,
    "status" => status,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class ShoppingListItemsFields extends MapBase<String, ffai.PostgresTableField> {
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final createdBy = ffai.ProjectTableFieldHandle(
    name: "created_by",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "profiles.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  final isPurchased = ffai.ProjectTableFieldHandle(
    name: "is_purchased",
    key: "",
    typeName: "Boolean",
    type: ffai.bool_,
    description: "",
    postgresType: "bool",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final name = ffai.ProjectTableFieldHandle(
    name: "name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final quantity = ffai.ProjectTableFieldHandle(
    name: "quantity",
    key: "",
    typeName: "Double",
    type: ffai.double_,
    description: "",
    postgresType: "numeric",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final shoppingListId = ffai.ProjectTableFieldHandle(
    name: "shopping_list_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "shopping_lists.id",
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final source = ffai.ProjectTableFieldHandle(
    name: "source",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final sourceRecipeId = ffai.ProjectTableFieldHandle(
    name: "source_recipe_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "saved_recipes.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final unit = ffai.ProjectTableFieldHandle(
    name: "unit",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "created_at",
    "created_by",
    "id",
    "is_purchased",
    "name",
    "quantity",
    "shopping_list_id",
    "source",
    "source_recipe_id",
    "unit",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "created_at" => createdAt,
    "created_by" => createdBy,
    "id" => id,
    "is_purchased" => isPurchased,
    "name" => name,
    "quantity" => quantity,
    "shopping_list_id" => shoppingListId,
    "source" => source,
    "source_recipe_id" => sourceRecipeId,
    "unit" => unit,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class ShoppingListsFields extends MapBase<String, ffai.PostgresTableField> {
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final householdId = ffai.ProjectTableFieldHandle(
    name: "household_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "households.id",
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  final name = ffai.ProjectTableFieldHandle(
    name: "name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );

  @override
  Iterable<String> get keys => const <String>[
    "created_at",
    "household_id",
    "id",
    "name",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "created_at" => createdAt,
    "household_id" => householdId,
    "id" => id,
    "name" => name,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class StorageLocationsFields extends MapBase<String, ffai.PostgresTableField> {
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final householdId = ffai.ProjectTableFieldHandle(
    name: "household_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "households.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  final isDefault = ffai.ProjectTableFieldHandle(
    name: "is_default",
    key: "",
    typeName: "Boolean",
    type: ffai.bool_,
    description: "",
    postgresType: "bool",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final locationType = ffai.ProjectTableFieldHandle(
    name: "location_type",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final name = ffai.ProjectTableFieldHandle(
    name: "name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "created_at",
    "household_id",
    "id",
    "is_default",
    "location_type",
    "name",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "created_at" => createdAt,
    "household_id" => householdId,
    "id" => id,
    "is_default" => isDefault,
    "location_type" => locationType,
    "name" => name,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

abstract final class CustomCode {
  static const functions = <String>[
    "belongsToHousehold",
    "emptyIconFor",
    "filterInventory",
    "firstHouseholdId",
    "firstHouseholdName",
    "firstInviteCode",
    "firstListId",
    "foodImage",
    "greetingLine",
    "greetingName",
    "hasHousehold",
    "hasRows",
    "heroImage",
    "hiLine",
    "householdRole",
    "itemField",
    "itemPhoto",
    "kitchenCount",
    "listCount",
    "listState",
    "profileInitial",
    "profileIsImperial",
    "profileName",
    "quantityLabel",
    "reviewLine",
    "shoppingEmpty",
    "urgentCount",
    "useFirstLine",
  ];
  static const actions = <String>[
    "AddItemToShoppingList",
    "AddNameToShoppingList",
    "AskNotificationPermission",
    "CaptureFoodPhoto",
    "CreateFoodItem",
    "CreateHousehold",
    "LetTapsThroughVideos",
    "LoadWasteSummary",
    "LookupBarcode",
    "RecogniseFood",
    "ScheduleExpiryReminders",
    "SettleFoodItem",
    "WarmImageCache",
  ];
  static const widgets = <String>[
    "AnimatedRemoteImage",
    "AppIcon",
    "FoodStatusBadge",
    "FridgeEntrance",
    "KitchenIcon",
    "LoopingRemoteImage",
    "StatusIcon",
  ];
}

