// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

/// Existing Test Pilot groups + tests on this project, with their
/// real ids. To EDIT one in place (instead of creating a
/// duplicate), pass its id: app.testGroup(id: ...) /
/// app.qaTest(id: ...). Run/manage via the testpilot.* MCP tools
/// or `flutterflow ai test-pilot ...`.
abstract final class TestPilotTests {
  const TestPilotTests._();

  /// Every Test Pilot group on this project.
  static const groups = <({String id, String name, List<({String id, String name})> tests})>[
    (
      id: 'HBEqXToGMgg8VRZFaA0l',
      name: 'Use It Fresh end-to-end (build 8 redesign)',
      tests: [
        (id: '5xOpa47mrrHSu9Zoaij9', name: '05 Recipes: find, open, filter, keep'),
        (id: 'JiwEUDgZZxvojONq9mKJ', name: '04 (merged into 02)'),
        (id: 'MeqtF2smPqtXIhwncb1S', name: '02 Fix, use and put back a food'),
        (id: 'OsmOKaOTX0KnAn7n6ABG', name: '07 (merged into 02 and 06)'),
        (id: 'VIy4AjQ443x2ffivDaZV', name: '03 Your kitchen: places, search, pictures'),
        (id: 'W5NXLHF4OsRbCasMcWHk', name: '09 Sign out and back in'),
        (id: 'aCVqfaXzFiOnu5TLEbEO', name: '06 Shopping list, basket, throw out'),
        (id: 'aoKthsMWfrsma3GrHqzu', name: '08 Profile rows open their screens'),
        (id: 'tooWt0Qprp86y8gsQytF', name: '01 Sign in and Home'),
      ],
    ),
    (
      id: 'UW7MFeIJUdcbM7cd7IEu',
      name: 'Smoke: sign in only',
      tests: [
        (id: 'SunIJHmN7aJxPCa9KJoq', name: 'Sign in lands on Home'),
      ],
    ),
  ];
}
